noetic/distribution.yaml
Increasing version of package(s) in repository `jackal_robot` to `0.7.3-1`:
- previous version for package: `0.7.2-1`
- No changes
```
* Added TIM551 to launch and package.xml
* Added Hokuyo UTM30 (#48 <https://github.com/jackal/jackal_robot/issues/48>)
* Add UTM30 to the bringup launch
* Fixed typo in secondary lidar launch
* [jackal_bringup] Removed unnecessary udev rule.
* Contributors: Luis Camero, Tony Baltovski, luis-camero
```
- No changes
=> jackal_robot: 0.7.3-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `jackal_robot` to `0.7.4-1`:
- previous version for package: `0.7.3-1`
- No changes
```
* Use python3 for the install script
Since removing python-is-python3 from the ISO this script appears to fail on a fresh Noetic install.
```
- No changes
=> jackal_robot: 0.7.4-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `flir_camera_driver` to `0.2.0-1`:
```
* Bumped flir_camera_description verison.
* Changes.
* Merge pull request #91 <https://github.com/ros-drivers/flir_camera_driver/issues/91> from luis-camero/noetic-devel
ROS Industrial CI
* Removed launch and rviz folders from CMakeLists
* URDF Description, Diagnostics, ISP Enable, and Launch Files (#81 <https://github.com/ros-drivers/flir_camera_driver/issues/81>)
* Changes required to use …
```
=> flir_camera_driver: 0.2.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `dingo_robot` to `0.2.1-1`:
- No changes
```
* [dingo_bringup] Updated install script to explicitly use Python3.
* Switch usage of ifconfig (net-tools) to ip (iproute2) (#12 <https://github.com/dingo-cpr/dingo_robot/issues/12>)
* Switch usage of ifconfig (net-tools) to ip (iproute2)
* Remove unnecessary "sudo"
* Contributors: Joey Yang, Tony Baltovski
```
- No changes
=> dingo_robot: 0.2.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky_robot` to `0.6.4-1`:
- previous version for package: `0.6.3-1`
- No changes
```
* [husky_bringup] Updated compute_calibration script to explicitly use Python3.
* [husky_bringup] Updated install script to explicitly use Python3.
```
- No changes
=> husky_robot: 0.6.4-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `ridgeback_robot` to `0.4.1-1`:
- No changes
```
* [ridgeback_bringup] Updated install script to explicitly use Python3.
* Change the can-udp-bringup to use ip instead of ifconfig (#35 <https://github.com/ridgeback/ridgeback_robot/issues/35>)
* Change the can-udp-bringup to use ip instead of ifconfig
* Fix the txqueue length
* For consistency stick with "link set can0" and not "link set dev can0"
* Contributors: Chris I-B, Tony Baltovski
```
- No changes
=> ridgeback_robot: 0.4.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `warthog_robot` to `0.2.2-1`:
- No changes
```
* [warthog_bringup] Updated install script to explicitly use Python3.
```
- No changes
=> warthog_robot: 0.2.2-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `occupancy_grid_utils` to `0.0.11-1`:
- upstream repository: https://github.com/clearpathrobotics/occupancy_grid_utils
- release repository: https://github.com/clearpath-gbp/occupancy_grid_utils-release.git
```
* Drop signals boost component.
```
=> occupancy_grid_utils: 0.0.11-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `occupancy_grid_utils` to `0.1.0-1`:
- upstream repository: https://github.com/clearpathrobotics/occupancy_grid_utils
- release repository: https://github.com/clearpath-gbp/occupancy_grid_utils-release.git
- previous version for package: `0.0.11-1`
```
* changes for building in ROS Noetic
```
=> occupancy_grid_utils: 0.1.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `piksi_rtk_msgs` to `1.8.3-1`:
- upstream repository: https://github.com/eshahrivar-cpr/earth_rover_piksi.git
- release repository: https://github.com/clearpath-gbp/earth_rover_piksi-release.git
```
* changelog
```
```
* changelog
```
```
* version
* changelog
* upgrade msgs
* upgrade msgs to v1.11.0
```
=> piksi_rtk_msgs: 1.8.3-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_gps_common` to `0.1.13-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/gps-navigation/cpr_gps_common.git
```
* Upgrade to ROS Noetic
```
```
* Upgrade to ROS Noetic
```
```
* Upgrade to ROS Noetic
* Contributors: José Mastrangelo, Michael Hosmar
```
```
* Upgrade to ROS Noetic
```
```
* Upgrade to ROS Noetic
```
```
* Upgrade to ROS Noetic
```
```
* Upgrade to ROS Noetic …
```
=> cpr_gps_common: 0.1.13-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.31-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/gps-navigation/cpr_gps_navigation.git
```
* Upgrade to ROS Noetic
```
```
* Upgrade to ROS Noetic
* adde localization monitor for lidar odometry
* Contributors: Ebrahim Shahrivar, José Mastrangelo, Michael Hosmar
```
```
* Upgrade to ROS Noetic
* Added lidar odometry (LOAM)
```
```
* Upgrade to ROS Noetic
* Contributors: Ebrahim Shahrivar, José …
```
=> cpr_gps_navigation: 0.1.31-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `gps_mpc_navigation` to `0.1.11-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/gps-navigation/gps_mpc_navigation.git
```
* Upgrade to ROS Noetic
```
```
* Upgrade to ROS Noetic
* path progress now fills to 100% when goal completed
* Contributors: José Mastrangelo, Stephen Phillips
```
```
* Upgrade to ROS Noetic
```
```
* Upgrade to ROS Noetic
```
=> gps_mpc_navigation: 0.1.11-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_gps_tasks` to `0.0.5-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/gps-navigation/cpr_gps_tasks.git
- release repository: https://gitlab.clearpathrobotics.com/gbp/cpr_gps_tasks-gbp.git
```
* Upgrade to ROS Noetic
* Contributors: José Mastrangelo, Michael Hosmar
```
```
* Upgrade to ROS Noetic
```
```
* Upgrade to ROS Noetic
```
=> cpr_gps_tasks: 0.0.5-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.32-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/gps-navigation/cpr_gps_navigation.git
- previous version for package: `0.1.31-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* fix safety monitor script runtime error by changing shebang
```
- No changes
- No changes
=> cpr_gps_navigation: 0.1.32-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `yperio` to `0.1.5-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/research/yperio.git
- release repository: https://gitlab.clearpathrobotics.com/gbp/yperio-gbp.git
```
* Added check to payload confirmatioon
* Removed redundant confirm state
* Fixed 'reset' not having config to reset to
* Added .py extension to TIM551 scripts
* Added platform _parmas, missing in TIM551
* Added Hokuyo UTM30
* Added SICK TIM551
* Fixed typos in default secondary UST10
* Added help commands to all user inputs
* Updated __nonzero__ to __bool__ for Python3
* Added default check function
* Fixed bugs and updated default check
* Added yes …
```
=> yperio: 0.1.5-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `flir_camera_driver` to `0.2.3-1`:
```
* 0.2.2
* Changes.
* 0.2.1
* Changes.
* 0.2.0
* Changes.
* Bumped flir_camera_description verison.
* Changes.
* Removed launch and rviz folders from CMakeLists
* URDF Description, Diagnostics, ISP Enable, and Launch Files (#81 <https://github.com/ros-drivers/flir_camera_driver/issues/81>)
* Changes required to use GigE Blackfly S version
* Added blackfly mesh
* Added URDF of blackflys and …
```
=> flir_camera_driver: 0.2.3-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `warthog_firmware` to `0.0.4-1`:
```
* Apply fixes from Jackal to compile for Bionic/Melodic
```
=> warthog_firmware: 0.0.4-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `warthog_firmware` to `0.1.0-1`:
```
* Removed ros_lib and genpy deps.
* Apply fixes from Jackal to compile for Bionic/Melodic
```
=> warthog_firmware: 0.1.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_gps_common` to `0.2.0-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/cpr-outdoornav/cpr_gps_common.git
- previous version for package: `0.1.13-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Debug message change to match convention
```
- No changes
=> cpr_gps_common: 0.2.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_gps_navigation` to `0.2.0-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/cpr-outdoornav/cpr_gps_navigation.git
- previous version for package: `0.1.32-1`
- No changes
- No changes
- No changes
- No changes
```
* added missing dynamic_reconfigure dependency
```
- No changes
- No changes
- No changes
- No changes
=> cpr_gps_navigation: 0.2.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_gps_tasks` to `0.1.0-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/cpr-outdoornav/cpr_gps_tasks.git
- release repository: https://gitlab.clearpathrobotics.com/gbp/cpr_gps_tasks-gbp.git
- No changes
- No changes
- No changes
=> cpr_gps_tasks: 0.1.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `gps_mpc_navigation` to `0.2.0-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/cpr-outdoornav/gps_mpc_navigation.git
- previous version for package: `0.1.11-1`
- No changes
```
* Fixed stop distance issue when larger than local_costmap
```
- No changes
- No changes
=> gps_mpc_navigation: 0.2.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_gps_common` to `0.2.0-3`:
- upstream repository: https://gitlab.clearpathrobotics.com/cpr-outdoornav/cpr_gps_common.git
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Debug message change to match convention
```
- No changes
=> cpr_gps_common: 0.2.0-3 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `gps_mpc_navigation` to `0.2.0-2`:
- upstream repository: https://gitlab.clearpathrobotics.com/cpr-outdoornav/gps_mpc_navigation.git
- No changes
```
* Fixed stop distance issue when larger than local_costmap
```
- No changes
- No changes
=> gps_mpc_navigation: 0.2.0-2 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_base` to `0.3.0-1`:
```
```
=> cpr_indoornav_base: 0.3.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_jackal` to `0.3.0-1`:
```
```
=> cpr_indoornav_jackal: 0.3.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
As part of migrating from Gitlab to Github we're breaking several packages out into their own repos.  This section is not needed as the core cpr_indoornav package has been replaced with cpr_indoornav_base and the _tests package has its own repo (which I'm trying to bloom right now, but hitting an assertion error because of the duplication).
=> Remove cpr_indoornav

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_tests` to `0.3.0-2`:
```
```
=> cpr_indoornav_tests: 0.3.0-2 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_ridgeback` to `0.3.0-1`:
```
```
=> cpr_indoornav_ridgeback: 0.3.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `jackal` to `0.8.4-1`:
- previous version for package: `0.8.3-1`
```
* Disable absolute yaw in default imu configuration
* Set subst_value=true when loading the control_extras file to allow envar-defined configuration inside the file
* Contributors: Chris I-B, Chris Iverach-Brereton
```
- No changes
- No changes
- No changes
- No changes
=> jackal: 0.8.4-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_gazebo` to `0.2.1-1`:
- No changes
```
* Disable the water physics; UUV does not appear to be released for Noetic yet. Will re-enable later if possible
```
- No changes
- No changes
- No changes
- No changes
=> cpr_gazebo: 0.2.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_gazebo` to `0.2.1-2`:
- No changes
```
* Disable the water physics; UUV does not appear to be released for Noetic yet. Will re-enable later if possible
```
- No changes
- No changes
- No changes
- No changes
=> cpr_gazebo: 0.2.1-2 in 'noetic/distribution.yaml' [bloom]

melodic/distribution.yaml
Increasing version of package(s) in repository `dingo_firmware_components` to `2.9.12-1`:
- previous version for package: `2.9.11-1`
```
```
=> dingo_firmware_components: 2.9.12-1 in 'melodic/distribution.yaml' [bloom]

melodic/distribution.yaml
Increasing version of package(s) in repository `dingo_firmware_components` to `2.9.12-2`:
- previous version for package: `2.9.12-1`
```
```
=> dingo_firmware_components: 2.9.12-2 in 'melodic/distribution.yaml' [bloom]

melodic/distribution.yaml
Increasing version of package(s) in repository `dingo_firmware` to `0.1.6-1`:
```
```
=> dingo_firmware: 0.1.6-1 in 'melodic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_common_msgs` to `0.0.1-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/Boxer/cpr_common_msgs.git
- release repository: http://gitlab.clearpathrobotics.com/boxer_gbp/cpr_common_msgs.git
```
```
```
```
```
```
```
```
=> cpr_common_msgs: 0.0.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_base` to `0.3.1-1`:
```
* Add additional relays to expose IndoorNav backpack topics to external hosts
* Add a simple tf republisher to ensure the tf between map and odom is visible
externally
```
=> cpr_indoornav_base: 0.3.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `dingo_firmware_components` to `2.9.12-1`:
```
```
=> dingo_firmware_components: 2.9.12-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `dingo_firmware` to `0.2.0-1`:
```
* Changes for Noetic.
* 0.1.6
* Changes.
```
=> dingo_firmware: 0.2.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_base` to `0.3.2-1`:
```
* Use python3 not python for the tf republisher script
```
=> cpr_indoornav_base: 0.3.2-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_platform_tests` to `0.3.0-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/research/cpr_platform_tests.git
- release repository: https://gitlab.clearpathrobotics.com/gbp/cpr_platform_tests-gbp.git
```
* Update package version; remove old CHANGELOG for dingo_tests
* Cleanup package.xml; list dependencies in alphabetical order; remove unused dependencies
* Merge branch 'wip-wheel-joints' into 'noetic-devel'
Output linear displacement from wheel joints for driveTest()
See merge request research/cpr_platform_tests!1
* Output linear displacement from wheel joints for driveTest()
* Apply adcTest() changes from previous …
```
=> cpr_platform_tests: 0.3.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky` to `0.6.3-1`:
- previous version for package: `0.6.2-1`
```
* Enable subst_value when loading config_extras. (#226 <https://github.com/husky/husky/issues/226>)
* Remove whitespace
* Re-add base_frame_id and velocity_rolling_window_size
* Update DiffDriveController params
- Remove estimate_velocity_from_position: false because it does not exist as a param in DiffDriveController, or anywhere in ros-controllers
- Remove base_frame_id: base_link because the default value of base_frame_id is already base_link, as per …
```
=> husky: 0.6.3-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky_robot` to `0.6.5-1`:
- previous version for package: `0.6.4-1`
- No changes
```
* Added Blackfly entry to install script
* Added Blackfly launch file
* Added spinnaker_camera_driver to package.xml
* Add HUSKY_REALSENSE_TOPIC envar for choosing prefix namespace for all realsense topics
* Update realsense launch file based on changes from realsense2_camera
* Contributors: Joey Yang, Luis Camero
```
- No changes
=> husky_robot: 0.6.5-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky_robot` to `0.6.6-1`:
- previous version for package: `0.6.5-1`
- No changes
- No changes
```
* WIP - Add dependency for husky_tests
```
=> husky_robot: 0.6.6-1 in 'noetic/distribution.yaml' [bloom]

melodic/distribution.yaml
Increasing version of package(s) in repository `dingo` to `0.1.11-1`:
```
* Enable subst_value in dingo_config_extras
This should get cherry-picked into Noetic too.
```
```
* Added Velodyne HDL32E and Microstrain GX5
* Updated URDF to disable mount
* Update VLP16 with disable tower and set angle on mount
* Add Velodyne HDL32e URDF and meshes
```
- No changes
- No changes
=> dingo: 0.1.11-1 in 'melodic/distribution.yaml' [bloom]

melodic/distribution.yaml
Increasing version of package(s) in repository `dingo_robot` to `0.1.6-1`:
- No changes
```
* Fix realsense double namespace error
* Update realsense launch file based on changes from realsense2_camera
* Remove unused rs_model argument
* Switch usage of ifconfig (net-tools) to ip (iproute2) (#12 <https://github.com/dingo-cpr/dingo_robot/issues/12>)
* Switch usage of ifconfig (net-tools) to ip (iproute2)
* Remove unnecessary "sudo"
```
- No changes
=> dingo_robot: 0.1.6-1 in 'melodic/distribution.yaml' [bloom]

foxy/distribution.yaml
Increasing version of package(s) in repository `husky` to `1.0.5-2`:
- previous version for package: `1.0.5-1`
```
* Split teleop launch into two files since simulation doesn't need actual joystick and will spam warmings.
* [husky_base] Fixed spawner.py bug.
* [husky_base] Added missing includes for base_launch.py.
* Revamped tele-op launch.
* Fix chnaged dependency in rolling.
* Contributors: Denis Štogl, Tony Baltovski
```
```
* Updated package versions for un-released packages.
* [husky_bringup] Disabled gps bringup for now since nmea_navsat_driver isn't released.
* Initial accessories launch …
```
=> husky: 1.0.5-2 in 'foxy/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `dingo_robot` to `0.2.2-1`:
- No changes
```
* Fix realsense double namespace error
* Updated Bringup (#14 <https://github.com/dingo-cpr/dingo_robot/issues/14>)
* Added Velodyne HDL32E and Microstrain GX5
* Added ros_mscl as run_depend in package.xml
* Alphabetically sort package.xml
* Update realsense launch file based on changes from realsense2_camera
* Remove unused rs_model argument
* Contributors: Joey Yang, luis-camero
```
- No changes
=> dingo_robot: 0.2.2-1 in 'noetic/distribution.yaml' [bloom]

melodic/distribution.yaml
Increasing version of package(s) in repository `ridgeback_robot` to `0.3.2-1`:
- No changes
```
* Change the can-udp-bringup to use ip instead of ifconfig (#35 <https://github.com/ridgeback/ridgeback_robot/issues/35>)
* Change the can-udp-bringup to use ip instead of ifconfig
* Fix the txqueue length
* For consistency stick with "link set can0" and not "link set dev can0"
```
- No changes
=> ridgeback_robot: 0.3.2-1 in 'melodic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `ridgeback_robot` to `0.4.2-1`:
- No changes
- No changes
```
* Add dependency for ridgeback_tests (#36 <https://github.com/ridgeback/ridgeback_robot/issues/36>)
This PR should only be merged once the test package is released.
```
=> ridgeback_robot: 0.4.2-1 in 'noetic/distribution.yaml' [bloom]

foxy/distribution.yaml
Increasing version of package(s) in repository `husky` to `1.0.7-1`:
- previous version for package: `1.0.6-1`
```
* Renamed all launch files to *.launch.py.
```
```
* Renamed all launch files to *.launch.py.
```
```
* [husky_control] Fixed joy device param.
* Renamed all launch files to *.launch.py.
```
```
* Renamed all launch files to *.launch.py.
```
- No changes
```
* Renamed all launch files to *.launch.py.
```
- No changes
- No changes …
=> husky: 1.0.7-1 in 'foxy/distribution.yaml' [bloom]

foxy/distribution.yaml
Increasing version of package(s) in repository `interactive_marker_twist_server` to `2.0.0-2`:
- upstream repository: https://github.com/ros-visualization/interactive_marker_twist_server.git
- release repository: https://github.com/ros-gbp/interactive_marker_twist_server-release.git
```
* Add license, contributing, and copyright headers for linter
* Style changes for linter
* List dependencies in alphabetical order
* add missing tick
* add basic usage instructions
* create ROS2 XML launch file
* add config argument
* initial README
* Re-include standard library headers
* Cleanup
* Use SingleThreadedExecutor; change topic name from global to relative; remove logging
* Remove duplicate …
```
=> interactive_marker_twist_server: 2.0.0-2 in 'foxy/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_platform_tests` to `0.3.1-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/research/cpr_platform_tests.git
- release repository: https://gitlab.clearpathrobotics.com/gbp/cpr_platform_tests-gbp.git
```
* Update safety clearance requirements for rotate and drive tests to be consistent with VKS.
* Wipe README file, and add link to tutorial documentation.
```
```
* Update safety clearance requirements for rotate and drive tests to be consistent with VKS.
* Wipe README file, and add link to tutorial documentation.
* Load rotateTest() on condition that an external IMU device is detected for …
```
=> cpr_platform_tests: 0.3.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_tests` to `0.3.1-1`:
- previous version for package: `0.3.0-2`
```
* Change the ROS1->2 bridge's domain to 91 instead of 121
```
=> cpr_indoornav_tests: 0.3.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_ridgeback` to `0.3.1-1`:
```
* Change the ROS1->2 bridge domain to 91
* Update the Ridgeback graphics
```
=> cpr_indoornav_ridgeback: 0.3.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_jackal` to `0.3.1-1`:
```
* Change the ROS1->2 bridge domain to 91
```
=> cpr_indoornav_jackal: 0.3.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_husky` to `0.3.1-1`:
```
* Change the ROS1->2 bridge domain to 91.
* Update the Husky graphics
```
=> cpr_indoornav_husky: 0.3.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_dingo` to `0.3.1-1`:
```
* Change the ROS1->2 bridge domain to 91.
```
=> cpr_indoornav_dingo: 0.3.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_base` to `0.3.3-1`:
```
* Update the ROS2 domain IDs since they've changed on the latest IndoorNav ISO
```
=> cpr_indoornav_base: 0.3.3-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `axis_camera` to `0.4.1-1`:
```
* Fix the #! lines to use python3, decode the utf8 bytes into a string to suppress a warning when parsing the camera position
```
=> axis_camera: 0.4.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_tests` to `0.3.1-2`:
```
* Change the ROS1->2 bridge's domain to 91 instead of 121
```
=> cpr_indoornav_tests: 0.3.1-2 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_base` to `0.3.3-2`:
```
* Update the ROS2 domain IDs since they've changed on the latest IndoorNav ISO
```
=> cpr_indoornav_base: 0.3.3-2 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_dingo` to `0.3.1-2`:
```
* Change the ROS1->2 bridge domain to 91.
```
=> cpr_indoornav_dingo: 0.3.1-2 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_jackal` to `0.3.1-2`:
```
* Change the ROS1->2 bridge domain to 91
```
=> cpr_indoornav_jackal: 0.3.1-2 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky` to `0.6.4-2`:
- previous version for package: `0.6.3-1`
- No changes
```
* Fixes for velodyne prefix
* PACS Brackets (#238 <https://github.com/husky/husky/issues/238>)
* Added STL models for brackets
* Added brackets to URDF
* Added bracket environment variables
* Fixed issues with find
* Added README with all Environment Variables
* Duplicate URDF for every standard sensor
* Added fath pivot mount as dependency
* Added URDF of Blackfly on top of fath_pivot_mount
* Added prefix to name parameter to differentiate between primary and …
```
=> husky: 0.6.4-2 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky_robot` to `0.6.7-1`:
- previous version for package: `0.6.6-1`
- No changes
```
* Fixes for velodyne prefix
* Secondary sensors (#24 <https://github.com/husky/husky_robot/issues/24>)
* Added second blackfly to launch
* Fixed prefix in UST10 launch
* Added remap to launch file to get desired topics
* Launch file now launches 2 Reaslenses directly using Nodelet launch
* Added second 3D laser to launch file
* Added entries for secondary sensors
* Added new line at EOF
* Use configurable laser prefix
husky_description supports …
```
=> husky_robot: 0.6.7-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `video_recorder` to `0.0.1-1`:
```
```
```
```
=> video_recorder: 0.0.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `video_recorder` to `0.0.2-1`:
```
* Add an optional parameter to set a hard maximum duration on videos recorded by the node.
```
- No changes
=> video_recorder: 0.0.2-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `dingo_firmware_components` to `2.9.13-1`:
- previous version for package: `2.9.12-1`
```
* Removed exec depend on python-tftpy since it is not installable on Focal.
```
=> dingo_firmware_components: 2.9.13-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_gps_common` to `0.2.1-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/cpr-outdoornav/cpr_gps_common.git
- previous version for package: `0.2.0-3`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* added support script to collect data from customer's robot PC related to OutdoorNav
* Contributors: David, Teresi, José Mastrangelo
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
=> cpr_gps_common: 0.2.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_gps_tasks` to `0.2.0-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/cpr-outdoornav/cpr_gps_tasks.git
- release repository: https://gitlab.clearpathrobotics.com/gbp/cpr_gps_tasks-gbp.git
- No changes
- No changes
- No changes
=> cpr_gps_tasks: 0.2.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_gps_navigation` to `0.2.1-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/cpr-outdoornav/cpr_gps_navigation.git
- No changes
```
* EKF node names have changed
```
- No changes
- No changes
```
* Predocking will now use Dubins
* changed parameter name to match changes in gps_mpc_navigation
* Update goal tolerance parameters based on testing results
* Remove deprecated function to call tasks as services
* traking service renamed and changed to std_srvs/Trigger
``` …
=> cpr_gps_navigation: 0.2.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `gps_mpc_navigation` to `0.2.1-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/cpr-outdoornav/gps_mpc_navigation.git
- previous version for package: `0.2.0-2`
- No changes
```
* Update goal tolerance parameters based on testing results
```
- No changes
- No changes
=> gps_mpc_navigation: 0.2.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_gazebo` to `0.2.2-1`:
- previous version for package: `0.2.1-2`
- No changes
```
* Add the water mesh to the visualization since UUV is disabled. This way the water at least renders, even if it doesn't have any physics
```
- No changes
- No changes
```
* Add the install directive to the orchard world
```
- No changes
=> cpr_gazebo: 0.2.2-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky` to `0.6.4-4`:
- previous version for package: `0.6.4-2`
- No changes
```
* Fixes for velodyne prefix
* PACS Brackets (#238 <https://github.com/husky/husky/issues/238>)
* Added STL models for brackets
* Added brackets to URDF
* Added bracket environment variables
* Fixed issues with find
* Added README with all Environment Variables
* Duplicate URDF for every standard sensor
* Added fath pivot mount as dependency
* Added URDF of Blackfly on top of fath_pivot_mount
* Added prefix to name parameter to differentiate between primary and …
```
=> husky: 0.6.4-4 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_jackal` to `0.3.2-1`:
- previous version for package: `0.3.1-2`
```
* Fix the python interpreter to force python3
```
=> cpr_indoornav_jackal: 0.3.2-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `axis_camera` to `0.4.2-1`:
```
* Explicitly use Python3 in shebang for teleop nodes; remove unnecessary shebang in setup.py (#72 <https://github.com/ros-drivers/axis_camera/issues/72>)
```
=> axis_camera: 0.4.2-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_gps_common` to `0.3.0-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/cpr-outdoornav/cpr_gps_common.git
- No changes
- No changes
```
* Allow autonomy metrics to be used on OEM vehicles.
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
=> cpr_gps_common: 0.3.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_gps_navigation` to `0.3.0-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/cpr-outdoornav/cpr_gps_navigation.git
- No changes
- No changes
- No changes
- No changes
```
* Parametrize the wait time between missions
```
- No changes
```
* Allow Safety monitor node to use safety topic from any OEM vehicle
```
- No changes
- No changes
=> cpr_gps_navigation: 0.3.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `gps_mpc_navigation` to `0.3.0-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/cpr-outdoornav/gps_mpc_navigation.git
- No changes
```
* Parametrized MPC corner state to allow slowdown multiplier and
* corner lookahead to be user configurable.
```
- No changes
- No changes
=> gps_mpc_navigation: 0.3.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_gps_tasks` to `0.3.0-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/cpr-outdoornav/cpr_gps_tasks.git
- release repository: https://gitlab.clearpathrobotics.com/gbp/cpr_gps_tasks-gbp.git
- No changes
- No changes
- No changes
=> cpr_gps_tasks: 0.3.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `axis_camera` to `0.4.3-1`:
```
* Merge pull request #73 <https://github.com/ros-drivers/axis_camera/issues/73> from jhiggins-cpr/noetic-devel
Add frames-per-second (fps) as a configurable option
* Reverting package change as it happens automatically
* Add frames-per-second (fps) as a configurable option
* Contributors: Jason Higgins, Tony Baltovski
```
=> axis_camera: 0.4.3-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `video_recorder` to `0.0.3-1`:
```
* Update the docs, add the is_recording + default filename to the audio recorder
* Add the first-pass audio-recorder action server. Very similar format to the video recorder, but for dumping ALSA input to wav files.
```
```
* Add the first-pass audio-recorder action server. Very similar format to the video recorder, but for dumping ALSA input to wav files
```
```
* …
```
=> video_recorder: 0.0.3-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `boxer` to `0.1.2-1`:
- upstream repository: https://github.com/boxer-cpr/boxer.git
- release repository: https://github.com/clearpath-gbp/boxer-release.git
```
* Merge pull request #1 <https://github.com/boxer-cpr/boxer/issues/1> from boxer-cpr/missing-depends
Add missing dependencies to package.xml
* Add missing exec_depends. Should resolve the warnings with releasing cpr_gazebo
```
```
* Merge pull request #2 <https://github.com/boxer-cpr/boxer/issues/2> from boxer-cpr/jyang-patch
* Update README
* Add BOXER_PC_XYZ and BOXER_PC_RPY envars to support relocating backpack computer …
```
=> boxer: 0.1.2-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `video_recorder` to `0.0.4-1`:
- No changes
- No changes
```
* Make sure the node is actually installed correctly
```
- No changes
=> video_recorder: 0.0.4-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_ridgeback` to `0.3.2-1`:
- previous version for package: `0.3.1-2`
```
* Add the additional manual input topic to the twist_mux
```
=> cpr_indoornav_ridgeback: 0.3.2-1 in 'noetic/distribution.yaml' [bloom]

foxy/distribution.yaml
Increasing version of package(s) in repository `jackal` to `1.0.0-1`:
```
* Updated all packages to 0.8.5.
* Added sim support
* Use Substitions for launch files
Added back CHANGELOG.rst
* Fixed imu filter node name
Updated scan topic to use /front/scan by default
* Control fixes
* Use IMU filter
* Minor cleanup
* 50Hz controller
* ROS2 jackal_control
* ROS 2 Port
* Contributors: David V. Lu, Roni Kreinin, Tony Baltovski
```
```
* Updated all packages to 0.8.5.
* Added sim support
* Added Nav2 and slam_toolbox to jackal_navigation
* Control fixes
* Minor …
```
=> jackal: 1.0.0-1 in 'foxy/distribution.yaml' [bloom]

foxy/distribution.yaml
Increasing version of package(s) in repository `jackal_desktop` to `1.0.1-1`:
- upstream repository: https://github.com/jackal/jackal_desktop.git
- release repository: https://github.com/clearpath-gbp/jackal_desktop-release.git
- No changes
```
* [jackal_viz] Changes rviz to rviz2.
```
=> jackal_desktop: 1.0.1-1 in 'foxy/distribution.yaml' [bloom]

foxy/distribution.yaml
Increasing version of package(s) in repository `jackal_simulator` to `1.0.0-1`:
- upstream repository: https://github.com/jackal/jackal_simulator
- release repository: https://github.com/clearpath-gbp/jackal_simulator-release.git
```
* Cleanup
* Working gazebo
```
```
* Working gazebo
```
=> jackal_simulator: 1.0.0-1 in 'foxy/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_jackal` to `0.3.3-1`:
```
* Add separate bridge params for GX5 vs UM7 setups
* Add the web GUI input to the twist_mux
* tune dock distance without actual receiver attached
* added launch file for docking. added argument to create docking job
* remove controller launch
* made hokuyo the default laser
* added dock controller launch file
* added section to start indoornav docking and docking setup script
* Contributors: Chris Iverach-Brereton, José …
```
=> cpr_indoornav_jackal: 0.3.3-1 in 'noetic/distribution.yaml' [bloom]

foxy/distribution.yaml
Increasing version of package(s) in repository `jackal` to `1.0.1-1`:
```
* [jackal_control] Fixed wrong dependency.
```
- No changes
- No changes
- No changes
=> jackal: 1.0.1-1 in 'foxy/distribution.yaml' [bloom]

foxy/distribution.yaml
Increasing version of package(s) in repository `wireless` to `1.0.0-1`:
```
* Minor fixes
* Updated wireless_msgs for ROS2.
Updated wireless_watcher for ROS2.
```
```
* Minor fixes
* Added previous changelogs
* Updated wireless_msgs for ROS2.
Updated wireless_watcher for ROS2.
```
=> wireless: 1.0.0-1 in 'foxy/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `jackal` to `0.8.6-1`:
- previous version for package: `0.8.4-1`
- No changes
```
* Set the GPS plugin's reference heading to 90 so it's ENU
* Use xacro properties defined from environment variables for Microstrain URDF (#123 <https://github.com/jackal/jackal/issues/123>)
* Add GAZEBO_WORLD_{LAT|LON} envars to change the reference coordinate of the robot's integral GPS
* Contributors: Chris Iverach-Brereton, Joey Yang
```
- No changes
- No changes
- No changes
=> jackal: 0.8.6-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `jackal_robot` to `0.7.5-1`:
- previous version for package: `0.7.4-1`
```
* use quiet_NaN for C++03 compatibility
* Changed method JackalHardware::copyJointsFromHardware() so that the robot
odomety resets to zero upon restart of the node.
Previously, old state information would be retained, leading to
incorrect localization behavior.
* Change sensor_msgs/MagneticField member to magnetic_field from vector
* Contributors: Blake Anderson, Stijn Eijndhoven
```
```
* Replace ros_mscl with microstrain_inertial_driver
* Add Blackfly to …
```
=> jackal_robot: 0.7.5-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `dingo` to `0.2.0-1`:
- No changes
```
* Customizable PACS riser heights
* Added Flir Blackfly
* Updated Realsense comments and include parameter
* Fixed typo in material name
* Added secondary realsense
* Added README with all URDF environment variables
* Force upper case for environment variables (#21 <https://github.com/dingo-cpr/dingo/issues/21>)
* Added PACS
* Changed enable envvar name
* Added EOL
* All caps for envvars
* Added PACS (#20 <https://github.com/dingo-cpr/dingo/issues/20>)
* Added …
```
=> dingo: 0.2.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `dingo_robot` to `0.2.3-1`:
- No changes
```
* Added Blackfly Camera
* Replace ros_mscl with microstrain_inertial_driver
* Added secondary realsense
* Contributors: Joey Yang, Luis Camero
```
- No changes
=> dingo_robot: 0.2.3-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `dingo_robot` to `0.2.4-1`:
- No changes
```
* Fixed point_cloud parameter
```
- No changes
=> dingo_robot: 0.2.4-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_jackal` to `0.3.4-1`:
```
* Use a 30-sample rolling average for the battery percentage instead of single samples. On Jackal this equates to ~30s averages
* Add a group for wireless charge docking if applicable
* Reduce the upper limit for the full battery voltage to 28.8V. See OPG02-76
```
=> cpr_indoornav_jackal: 0.3.4-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_dingo` to `0.3.2-1`:
- previous version for package: `0.3.1-2`
```
* Add the web GUI manual control input
```
=> cpr_indoornav_dingo: 0.3.2-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_base` to `0.3.4-1`:
- previous version for package: `0.3.3-2`
```
* Update docking controller file
* Add wireless docking support
* Assume always 2 lasers in indoornav
* Fix value to default in launch
* Moved controller launch to each repo since envvars relative to each robot
* Added lanuch files for running indoornav docking
* Add instructions for building the ROS2 SDK examples since they require manual fixes
```
=> cpr_indoornav_base: 0.3.4-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky` to `0.6.5-1`:
- previous version for package: `0.6.4-4`
```
* Fixed all scan topics to use front/scan.
* Disable keyboard input by default; on a normal robot this is launched by the systemd job, where there will never be any keyboard input.
* Separate the keyboard teleop to a separate topic, add the new topic to the twist_mux
* Move the keyboard teleop launch into the main teleop file, add an arg to optionally disable it
* Update package.xml
* Update CHANGELOG.rst
* Update CMakeLists.txt
* Update package.xml
* Update CHANGELOG.rst
* Update …
```
=> husky: 0.6.5-1 in 'noetic/distribution.yaml' [bloom]

melodic/distribution.yaml
Increasing version of package(s) in repository `husky` to `0.4.13-1`:
- previous version for package: `0.4.12-1`
- No changes
```
* Add HUSKY_REALSENSE_TOPIC envar for choosing prefix namespace for all realsense topics
* Update realsense launch file based on changes from realsense2_camera
```
```
* Fixed all scan topics to use front/scan.
* Remove whitespace
* Merge pull request #217 <https://github.com/husky/husky/issues/217> from husky/jyang-cpr-patch-1
Update DiffDriveController params
* Contributors: Joey Yang, Tony Baltovski
```
```
* Added Wibotic mesh and STL …
```
=> husky: 0.4.13-1 in 'melodic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_gazebo` to `0.2.4-1`:
```
* Add a new accessories package with the charge dock and base station. Add view_world.launch files to all relevant packages so you can view the environment without spinning up Gazebo. Add the wireless charge dock and base station to the agriculture world
```
```
* Move the wireless charge dock back outside
* Fix the world geometry to use ENU, fix the sun direction so it makes sense for the world
* Update the datum …
```
=> cpr_gazebo: 0.2.4-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `jackal_robot` to `0.7.6-1`:
- previous version for package: `0.7.5-1`
- No changes
```
* Microstrain uses microstrain.yaml instead of deprecated ROS launch arguments.
```
- No changes
=> jackal_robot: 0.7.6-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `valence_bms` to `0.0.2-1`:
- release repository: http://gitlab.clearpathrobotics.com/gbp/valence_bms-gbp.git
```
* Updated license and installed files.
```
```
* Updated license and installed files.
```
=> valence_bms: 0.0.2-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `jackal_robot` to `0.7.7-1`:
- previous version for package: `0.7.6-1`
```
* [jackal_base] Added support for checking for $GNRMC in NMEA sentence and also removed ROS param for which sentence to look for.
```
- No changes
- No changes
=> jackal_robot: 0.7.7-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky_robot` to `0.6.8-1`:
- previous version for package: `0.6.7-1`
```
* [husky_base] Updated diagnostics for motor and motor driver temperatures.
```
```
* Removed manual definition of base_frame_id
* [husky_bringup] Updated compute_calibration to use MagneticField message.
* Fix MagneticField msg reading
* Contributors: Luis Camero, Saurav Agarwal, Tony Baltovski
```
- No changes
=> husky_robot: 0.6.8-1 in 'noetic/distribution.yaml' [bloom]

melodic/distribution.yaml
Increasing version of package(s) in repository `moose_firmware` to `0.1.0-2`:
- upstream repository: http://gitlab.clearpathrobotics.com/research/moose_firmware.git
- release repository: http://gitlab.clearpathrobotics.com/gbp/moose_firmware-gbp.git
```
* Updated generator start logic.
```
=> moose_firmware: 0.1.0-2 in 'melodic/distribution.yaml' [bloom]

melodic/distribution.yaml
Increasing version of package(s) in repository `moose_firmware` to `0.2.0-2`:
- upstream repository: http://gitlab.clearpathrobotics.com/research/moose_firmware.git
- release repository: http://gitlab.clearpathrobotics.com/gbp/moose_firmware-gbp.git
- previous version for package: `0.1.0-2`
```
* Updated for melodic on bionic.
```
=> moose_firmware: 0.2.0-2 in 'melodic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_gazebo` to `0.2.5-1`:
```
* Merge pull request #19 <https://github.com/clearpathrobotics/cpr_gazebo/issues/19> from mhosmar-cpr/gzweb
Add Gzweb Support
* add missing newlines
* Add model.config to install target
* Add GZweb support
* Contributors: Chris Iverach-Brereton, Michael Hosmar
```
```
* Merge pull request #19 <https://github.com/clearpathrobotics/cpr_gazebo/issues/19> from mhosmar-cpr/gzweb
Add Gzweb Support
* add missing newlines
* Add model.config to install target
* …
```
=> cpr_gazebo: 0.2.5-1 in 'noetic/distribution.yaml' [bloom]

foxy/distribution.yaml
Increasing version of package(s) in repository `simple_term_menu_vendor` to `1.5.5-1`:
- upstream repository: https://github.com/clearpathrobotics/simple-term-menu.git
- release repository: https://github.com/clearpath-gbp/simple_term_menu_vendor-release.git
```
* Added ament_cmake_python buildtool_depend
```
=> simple_term_menu_vendor: 1.5.5-1 in 'foxy/distribution.yaml' [bloom]

foxy/distribution.yaml
Increasing version of package(s) in repository `simple_term_menu_vendor` to `1.5.6-1`:
- upstream repository: https://github.com/clearpathrobotics/simple-term-menu.git
- release repository: https://github.com/clearpath-gbp/simple_term_menu_vendor-release.git
- previous version for package: `1.5.5-1`
```
* Removed unused files
Added testing dependencies
```
=> simple_term_menu_vendor: 1.5.6-1 in 'foxy/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `warthog_robot` to `0.2.3-1`:
```
* [warthog_base] Added Valence BMS.
```
- No changes
```
* Merge branch 'warthog_tests' into 'noetic-devel'
Add dependency for warthog_tests
See merge request research/warthog_robot!9
* Add dependency for warthog_tests
* Contributors: Joey Yang, Tony Baltovski
```
=> warthog_robot: 0.2.3-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `flir_camera_driver` to `0.2.4-1`:
- No changes
- No changes
```
* Fixed typo in arm64 arch.
```
=> flir_camera_driver: 0.2.4-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `flir_camera_driver` to `0.2.5-1`:
- No changes
- No changes
```
* Fixed arm64 folder name.
```
=> flir_camera_driver: 0.2.5-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_gazebo` to `0.2.6-1`:
- No changes
```
* Fix the location of the base station in the agriculture world
```
- No changes
- No changes
- No changes
- No changes
- No changes
=> cpr_gazebo: 0.2.6-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `warthog` to `0.1.6-1`:
- No changes
```
* Change the GPS plugin reference heading to 90 so it's ENU
* Add missing xacro tags for ROS Noetic (and backwards compatability)
* Add GAZEBO_WORLD_{LAT|LON} envars to change the reference coordinate of the robot's integral GPS
* Contributors: Chris Iverach-Brereton, Joey Yang
```
- No changes
=> warthog: 0.1.6-1 in 'noetic/distribution.yaml' [bloom]

melodic/distribution.yaml
Increasing version of package(s) in repository `warthog` to `0.1.6-1`:
- No changes
```
* Change the GPS plugin reference heading to 90 so it's ENU
* Add missing xacro tags for ROS Noetic (and backwards compatability)
* Add GAZEBO_WORLD_{LAT|LON} envars to change the reference coordinate of the robot's integral GPS
* Contributors: Chris Iverach-Brereton, Joey Yang
```
- No changes
=> warthog: 0.1.6-1 in 'melodic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky` to `0.6.6-2`:
- previous version for package: `0.6.5-1`
- No changes
- No changes
- No changes
```
* Merge pull request #270 <https://github.com/husky/husky/issues/270> from husky/rename-empty-world
* Rename husky_empty_world.launch to empty_world.launch to make it consistent with other platforms
```
- No changes
- No changes
- No changes
- No changes
=> husky: 0.6.6-2 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_gazebo` to `0.2.7-1`:
- No changes
```
* Fix a typo in almost every readme, add the new empty world with support for all platforms
```
```
* Initial commit of the new empty world
```
```
* Fix a typo in almost every readme, add the new empty world with support for all platforms
```
- No changes
```
* Fix a typo in almost every readme, add the new empty world with …
```
=> cpr_gazebo: 0.2.7-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky` to `0.6.6-3`:
- previous version for package: `0.6.6-2`
- No changes
- No changes
- No changes
```
* Merge pull request #270 <https://github.com/husky/husky/issues/270> from husky/rename-empty-world
* Rename husky_empty_world.launch to empty_world.launch to make it consistent with other platforms
```
- No changes
- No changes
- No changes
- No changes
=> husky: 0.6.6-3 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `jackal_firmware` to `0.4.6-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/research/jackal_firmware.git
- previous version for package: `0.4.5-1`
```
* Added motor controller enabled for hardware revision 1.
* Made fan enable temperature a static const.
* Added hardware ID checking.
* Added navsat configuration for new GPS module.
* Populated driver_fault from hardware.
```
=> jackal_firmware: 0.4.6-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `dingo_firmware_components` to `2.9.14-1`:
- previous version for package: `2.9.13-2`
```
* Firmware flash fixes for python3
```
=> dingo_firmware_components: 2.9.14-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_tests` to `0.3.2-1`:
- previous version for package: `0.3.1-2`
```
* Add tests for EKF since it must be enabled for IndoorNav to operate properly
```
=> cpr_indoornav_tests: 0.3.2-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `wibotic-ros-can-connector` to `0.0.1-1`:
- upstream repository: https://github.com/clearpathrobotics/wibotic-ros-can-connector.git
- release repository: https://github.com/clearpath-gbp/wibotic-ros-can-connector_release.git
```
* Updated CMakeLists and package.xml
* Updated uavcan dependency
* Added load_peak script and udev rules
* Added charging state publisher
* Update repository to Rev_19
* Update repository to Rev_18
* Update repository to Rev_15
* Adds installation directives to wibotic_connector_can CMakeLists.
* Update repository to Rev_14
* Update repository to Rev_12
* Added sample launch file
* Changed wiboticros.py …
```
=> wibotic-ros-can-connector: 0.0.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `wibotic-ros-can-connector` to `0.0.2-1`:
- upstream repository: https://github.com/clearpathrobotics/wibotic-ros-can-connector.git
- release repository: https://github.com/clearpath-gbp/wibotic-ros-can-connector_release.git
```
* Changed data info logs to debug logs
```
- No changes
=> wibotic-ros-can-connector: 0.0.2-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `dingo` to `0.3.0-1`:
- No changes
```
* Change Microstrain IMU default parent link from imu_link to base_link
```
```
* Added Hardware ID's
Added shore_power_ov and manual_charger_connected status for D150
```
- No changes
=> dingo: 0.3.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `dingo_firmware` to `0.3.0-1`:
```
* Dingo 1.5
```
=> dingo_firmware: 0.3.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `dingo_robot` to `0.3.0-1`:
```
* Updated reset and low battery lighting patterns
* Added D150 battery levels
* Added Wibotic charging status to dingo_lighting
Renamed PUMA can interface to vcan0
Added Wibotic launch to accessories.launch
* Fixed pulse pattern to properly pulse between any two colours
* Added shore and charging lighting pattern
Ignore puma bridge fault when EStopped
Map lights to motors for puma faults
* Green pulse for charging
* Updated how lighting state is determined …
```
=> dingo_robot: 0.3.0-1 in 'noetic/distribution.yaml' [bloom]

foxy/distribution.yaml
Increasing version of package(s) in repository `jackal` to `1.0.2-1`:
```
* Uncomment dependency on imu_filter_madgwick; it is now installable as a deb in Foxy.
```
```
* Add missing dependency to velodyne_description.
```
```
* Added SetDomainId service
```
- No changes
=> jackal: 1.0.2-1 in 'foxy/distribution.yaml' [bloom]

foxy/distribution.yaml
Increasing version of package(s) in repository `jackal_robot` to `1.0.1-1`:
```
* Added ExecuteProcess action to set the domain ID at launch
* Added robot_upstart dependency
* Added dependencies.repos file
```
=> jackal_robot: 1.0.1-1 in 'foxy/distribution.yaml' [bloom]

foxy/distribution.yaml
Increasing version of package(s) in repository `jackal` to `1.0.3-1`:
- previous version for package: `1.0.2-1`
- No changes
```
* Fixed gazebo_ros_laser plugin
```
- No changes
- No changes
=> jackal: 1.0.3-1 in 'foxy/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `dingo_firmware` to `0.3.1-1`:
```
* Added low voltage cutoff
```
=> dingo_firmware: 0.3.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_husky` to `0.3.5-1`:
```
* Fix the PI variable; husky_description uses M_PI, not PI
```
=> cpr_indoornav_husky: 0.3.5-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky` to `0.6.7-1`:
- previous version for package: `0.6.6-3`
- No changes
```
* Fixed Realsense URDF
* Cleared up launch from description variables
* Changed 'true' and '1' to 1
* Switched all enables to true
```
- No changes
- No changes
- No changes
```
* Add a scan_topic argument to the gmapping_demo
This just exposes the gmapping.launch file's argument to the gmapping_demo.launch to make it easier to use non-standard topics.
```
- No changes
- No changes
=> husky: 0.6.7-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky_robot` to `0.6.9-1`:
- previous version for package: `0.6.8-1`
- No changes
```
* Updated Secondary Realsense Variables
* Create README.md
* Change HUSKY_IMU_MICROSTRAIN_PORT to HUSKY_IMU_PORT for Microstrain IMU to maintain backwards compatability with legacy microstrain launch file.
* Replace ros_mscl with microstrain_inertial_driver
* Contributors: Joey Yang, luis-camero
```
- No changes
=> husky_robot: 0.6.9-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_onav_description` to `0.1.0-1`:
```
* Added STL files for Starter Kit, Velodynes and Realsense D435s
* Added urdf files for starter and standard kits
```
=> cpr_onav_description: 0.1.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `axis_camera` to `0.4.4-1`:
- previous version for package: `0.4.3-1`
```
* Improve support for the F34 multi-camera controller by adding default values for the camera index (1-4). Change the camera arg in view_axis to camera_name, change its default IP address to better-match with the main axis.launch file
* Merge latest changes in master into noetic-devel
* Merge Q62 support into noetic-devel branch (#76 <https://github.com/ros-drivers/axis_camera/issues/76>)
* Add support for the Q6215 IR mode, defogger, and wiper
* Ensure …
```
=> axis_camera: 0.4.4-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `flir_ptu` to `0.2.2-1`:
- upstream repository: https://github.com/ros-drivers/flir_ptu.git
- release repository: https://github.com/clearpath-gbp/flir_ptu-release.git
```
* Merge pull request #50 <https://github.com/ros-drivers/flir_ptu/issues/50> from ros-drivers/wip-simulation
Add Gazebo Support
* Use a pair of JointPositionControllers to provide gazebo simulation support for the PTU
```
```
* Linting
* Merge pull request #50 <https://github.com/ros-drivers/flir_ptu/issues/50> from ros-drivers/wip-simulation
Add Gazebo Support
* Add additional dependencies
* Merge pull request #51 …
```
=> flir_ptu: 0.2.2-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `axis_camera` to `0.4.5-1`:
- previous version for package: `0.4.4-1`
```
* Enable digest authentication by default
```
=> axis_camera: 0.4.5-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `numato_relay_interface` to `0.1.0-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/research/numato_relay_interface.git
- release repository: https://github.com/clearpath-gbp/numato_relay_interface-release.git
```
* Contributors: Chris Iverach-Brereton, Joey Yang, Rhys Faultless, Tony Baltovski
```
=> numato_relay_interface: 0.1.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `video_recorder` to `0.0.5-1`:
```
* Add ability to record meta-data about each recording
* Initial implementation of audio_recorder metadata to match the video_recorder implementation
* Create the output directory for the audio recorder node to keep the behaviour consistent with the video recorder
```
- No changes
```
* Add ability to record meta-data about each recording
* Add exception handling if the tf lookup fails
* Switch from Mat …
```
=> video_recorder: 0.0.5-1 in 'noetic/distribution.yaml' [bloom]

foxy/distribution.yaml
Increasing version of package(s) in repository `husky` to `1.0.9-1`:
- previous version for package: `1.0.7-1`
```
* [husky_base] Added status topic publishing.
* [husky_base] Fixed typo.
* [husky_base] Added xacro as dep.
* Moved accessories launch into base launch and removed from robot_upstart install.
* [husky_base] Removed old ROS1 launch file.
```
```
* [husky_bringup] Fixed bug in accessories launch.
* Added realsense accessory, updated velodyne accessories.
* Moved accessories launch into base launch and removed from robot_upstart install. …
```
=> husky: 1.0.9-1 in 'foxy/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `numato_relay_interface` to `0.1.1-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/research/numato_relay_interface.git
- release repository: https://github.com/clearpath-gbp/numato_relay_interface-release.git
```
* Linter fixes
```
=> numato_relay_interface: 0.1.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `numato_relay_interface` to `0.1.2-1`:
- upstream repository: https://github.com/clearpathrobotics/numato_relay_interface.git
- release repository: https://github.com/clearpath-gbp/numato_relay_interface-release.git
```
* Fix required components in the cmake file, update the maintainer
```
=> numato_relay_interface: 0.1.2-1 in 'noetic/distribution.yaml' [bloom]

foxy/distribution.yaml
Increasing version of package(s) in repository `jackal` to `1.0.4-1`:
- previous version for package: `1.0.3-1`
```
* Remove gravitational acceleration in ekf_node
```
```
* [jackal_description] Changed the output type of the gazebo_ros_ray_sensor to LaserScan.
```
- No changes
- No changes
=> jackal: 1.0.4-1 in 'foxy/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `dingo_firmware_components` to `2.9.15-1`:
- previous version for package: `2.9.14-1`
```
* Added python3-tftpy as dep.
* MPU9x50 calibrate only once
* Calculate accel bias during calibration
```
=> dingo_firmware_components: 2.9.15-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `dingo_firmware` to `0.3.2-1`:
```
* Changed dingo_firmware_components to depend.
```
=> dingo_firmware: 0.3.2-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `dingo` to `0.3.1-1`:
- No changes
```
* Adding Sick TIM551 lidar
* Standard mounting locations persist in PACS
* Update README
* Contributors: Hilary Luo, luis-camero
```
- No changes
- No changes
=> dingo: 0.3.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `dingo_robot` to `0.3.1-1`:
```
* Adding Sick TIM551 lidar
* Added mapping for Dingo-D wheel names
* Contributors: Hilary Luo, Roni Kreinin
```
```
* Adding Sick TIM551 lidar
* Updated realsense initial_reset
Missing the prefix realsense_
* Contributors: Hilary Luo, luis-camero
```
- No changes
=> dingo_robot: 0.3.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `dingo_simulator` to `0.1.2-1`:
- upstream repository: https://github.com/dingo-cpr/dingo_simulator.git
- release repository: https://github.com/clearpath-gbp/dingo_simulator-release.git
```
```
```
```
=> dingo_simulator: 0.1.2-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `dingo_desktop` to `0.1.2-1`:
```
```
```
```
=> dingo_desktop: 0.1.2-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `ridgeback_robot` to `0.4.3-1`:
- No changes
```
* Add microstrain_inertial_driver to support current Microstrain IMU models (#37 <https://github.com/ridgeback/ridgeback_robot/issues/37>)
* Add microstrain_inertial_driver for supporting current Microstrain IMU models.
* Remove accidental copy
* Clearer comments for RIDGEBACK_IMU_MICROSTRAIN.
```
- No changes
=> ridgeback_robot: 0.4.3-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `ridgeback` to `0.3.3-1`:
- No changes
```
* Added README to ridgeback description
* Add comments to clarify between RIDGEBACK_MICROSTRAIN_IMU and RIDGEBACK_IMU_MICROSTRAIN.
* Add URDF link and joint for microstrain_inertial_driver Microstrain IMU.
* Contributors: Joey Yang, luis-camero
```
- No changes
- No changes
=> ridgeback: 0.3.3-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `jackal_robot` to `0.7.9-1`:
- previous version for package: `0.7.8-1`
- No changes
```
* [jackal_bringup] Added script to automatically set wireless interface.
```
- No changes
=> jackal_robot: 0.7.9-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `ridgeback` to `0.3.3-2`:
- No changes
```
* Added README to ridgeback description
* Add comments to clarify between RIDGEBACK_MICROSTRAIN_IMU and RIDGEBACK_IMU_MICROSTRAIN.
* Add URDF link and joint for microstrain_inertial_driver Microstrain IMU.
* Contributors: Joey Yang, luis-camero
```
- No changes
- No changes
=> ridgeback: 0.3.3-2 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `dingo` to `0.3.1-2`:
- No changes
```
* Adding Sick TIM551 lidar
* Standard mounting locations persist in PACS
* Update README
* Contributors: Hilary Luo, luis-camero
```
- No changes
- No changes
=> dingo: 0.3.1-2 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `jackal` to `0.8.7-3`:
- previous version for package: `0.8.7-2`
- No changes
```
* Added Environment Variables
```
- No changes
- No changes
- No changes
=> jackal: 0.8.7-3 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `axis_camera` to `0.4.6-1`:
- previous version for package: `0.4.5-1`
```
* Wait until camera is online before connecting (#78 <https://github.com/ros-drivers/axis_camera/issues/78>)
* Add a wait loop to prevent execution until the camera responds to a ping. This should prevent issues where the node starts while the camera is still powering-on, resulting in some excessive errors
* Clear the camera position after publishing the state to avoid issues where we republush the same state ad nauseum if there's an error …
```
=> axis_camera: 0.4.6-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `ptz_action_server` to `0.1.2-1`:
```
* Re-send the axis command if the camera isn't moving after 5s
* Add some additional logging, handle camera disconnections better
* Abort the action in-progress if the Axis camera stops publishing state messages
* Use format strings instead of .format
```
- No changes
=> ptz_action_server: 0.1.2-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky` to `0.6.8-1`:
- previous version for package: `0.6.7-1`
- No changes
```
* Only Included Realsense if Enabled
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
=> husky: 0.6.8-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_msg` to `0.0.2-1`:
- No changes
```
* [clearpath_platform_msgs] Fixed typo in Power msg enum.
* [clearpath_platform_msgs] Added size constants for A200 values.
```
=> clearpath_msg: 0.0.2-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_platform_tests` to `0.3.3-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/research/cpr_platform_tests.git
- release repository: https://gitlab.clearpathrobotics.com/gbp/cpr_platform_tests-gbp.git
```
* Added front and rear e-stop test for Boxer.
* Update rotate test and drive test prompts to indicate that travel displacements are approximate
* Increase rotate test acceptable error since OTTO onboard IMU has low accuracy; remove unused response_delay variable
* Contributors: Joey Yang, Tony Baltovski
```
```
* Change references of E-Stop to Motion Stop for all platforms except for Boxer
* Increase passable voltage …
```
=> cpr_platform_tests: 0.3.3-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `axis_camera` to `0.4.7-1`:
- previous version for package: `0.4.6-1`
```
* Fix a bug that caused the ptz node to crash if the camera has fixed brightness
```
=> axis_camera: 0.4.7-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `ridgeback` to `0.3.4-1`:
- previous version for package: `0.3.3-2`
- No changes
```
* Take the thickness of the deck into consideration so that the riser link has the correct origin and the top link sits atop it correctly. Change the riser colour to light grey to match the unfinished aluminium extrusion used for this component
* Initial commit of adding a customizable riser height to the URDF
```
- No changes
- No changes
=> ridgeback: 0.3.4-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `microhard_snmp` to `0.0.3-1`:
```
* Allow changing device ID
* Contributors: Michael Hosmar
```
=> microhard_snmp: 0.0.3-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `0.0.3-2`:
```
* Fixed parsing issues
* Added python3-yaml to dependencies
* Removed old parser
* Removed unused code
* Added updates to change indexing based on serial number
* Added sensors to property system
* Added __init__ to all subfolders
* Added mounts to main config
* Moved mount types to separate folder
* Added read and write functions to ClearpathConfig
* Added accessories to property method
* Updated all configs to use properties instead …
```
=> clearpath_config: 0.0.3-2 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `0.0.4-1`:
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
=> clearpath_common: 0.0.4-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `0.0.3-3`:
- previous version for package: `0.0.3-2`
```
* Fixed parsing issues
* Added python3-yaml to dependencies
* Removed old parser
* Removed unused code
* Added updates to change indexing based on serial number
* Added sensors to property system
* Added __init__ to all subfolders
* Added mounts to main config
* Moved mount types to separate folder
* Added read and write functions to ClearpathConfig
* Added accessories to property method
* Updated all configs to use properties instead …
```
=> clearpath_config: 0.0.3-3 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `0.0.5-1`:
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* [clearpath_platform_description] Fixed unused dependency in CMakeLists.txt.
```
- No changes
=> clearpath_common: 0.0.5-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `clearpath_msgs` to `0.9.0-1`:
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
```
=> clearpath_msgs: 0.9.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `dingo_firmware_components` to `2.9.15-2`:
- previous version for package: `2.9.15-1`
```
* Added python3-tftpy as dep.
* MPU9x50 calibrate only once
* Calculate accel bias during calibration
```
=> dingo_firmware_components: 2.9.15-2 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_nav2_demos` to `0.0.1-1`:
```
* Added space to package.xml.
* Updated package.xml order.
* Added test dependencies.
* Added Github actions.
* Config updates
* Namespacing fixes
* Updated odom topics
* Fixed footprint and adjusted velocity/accel limits on J100
* Use config to set namespace and platform model
* Current best parameters for Husky
* Cleanup
* Jackal params
* Contributors: Hilary Luo, Roni Kreinin, Tony Baltovski …
```
=> clearpath_nav2_demos: 0.0.1-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `0.0.4-1`:
- previous version for package: `0.0.3-3`
```
* Added __init__ to common
* Only run pytest on clearpath_config
* Linting errors
* Added samples to installed share
* Removed parser
* Updated pytests
* Renamed configs
* Added license file
* Added license headers
* Renamed accessories to links in top level config
* Replaced accessories module with links
* Renamed decorations and accessories
* Standard lists
* Removed all old samples
* Added workspace setter
* Added workspaces
* Fixed …
```
=> clearpath_config: 0.0.4-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `dingo_simulator` to `0.1.2-2`:
- upstream repository: https://github.com/dingo-cpr/dingo_simulator.git
- release repository: https://github.com/clearpath-gbp/dingo_simulator-release.git
```
```
```
```
=> dingo_simulator: 0.1.2-2 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `wireless` to `1.0.1-2`:
- No changes
```
* [wireless_watcher] Switched to underscores to get rid of usage of dash-separated warning.
```
=> wireless: 1.0.1-2 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `0.0.7-1`:
- No changes
- No changes
- No changes
```
* Renamed description to attachments
* Rnamed accessories to links
```
- No changes
- No changes
```
* Renamed URDF and meshes directories
```
- No changes
=> clearpath_common: 0.0.7-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `flir_camera_driver` to `2.0.0-1`:
```
* [flir_camera_description] Changed unused depends to exec_depends.
* Merge pull request #113 <https://github.com/ros-drivers/flir_camera_driver/issues/113> from berndpfrommer/humble-devel-new
new driver for ROS2
* resize image and move to top
* update licensing comment
* modify the description package for ROS2, add documentation
* Contributors: Bernd Pfrommer, Tony Baltovski
```
```
* Merge pull request #113 …
```
=> flir_camera_driver: 2.0.0-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `0.0.1-2`:
```
* Set use_sim_time to false
* Updated namespace and domain id service call
* Updates for how launch files are written
* Namespacing support
* Moved clearpath_platform to clearpath_common
Added clearpath_generator_robot
Created clearpath_robot metapackage
Moved scripts and services into clearpath_robot
```
```
* [clearpath_platform] Added J100 MCU, FTDI and Logitech joy udev rules.
* Moved clearpath_platform to …
```
=> clearpath_robot: 0.0.1-2 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `micro_ros_msgs` to `3.0.0-1`:
- upstream repository: https://github.com/micro-ROS/micro_ros_msgs.git
- release repository: https://github.com/clearpath-gbp/micro_ros_msgs-release.git
- No changes
=> micro_ros_msgs: 3.0.0-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `micro_ros_agent` to `3.0.5-1`:
- upstream repository: https://github.com/micro-ROS/micro-ROS-Agent.git
- release repository: https://github.com/clearpath-gbp/micro-ROS-Agent-release.git
- No changes
=> micro_ros_agent: 3.0.5-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `flir_camera_driver` to `2.0.1-1`:
- No changes
- No changes
```
* use cmake find_program to detect lsb_release
* Contributors: Bernd Pfrommer
```
=> flir_camera_driver: 2.0.1-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `0.0.8-1`:
- previous version for package: `0.0.7-1`
- No changes
- No changes
- No changes
```
* Linting
* use_sim_time support
* Description and Bash generator cleanup
* Minor cleanup
* Param generator
* Launch generator cleanup
```
- No changes
- No changes
```
* Updated J100 imu and navsat links
```
- No changes
=> clearpath_common: 0.0.8-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_simulator` to `0.0.3-1`:
```
* Linting
* Added prefix launch arg for A200
* Updated param generator 'use_sim_time' implementation
* Launch generator cleanup
```
```
* Linting
```
```
* Linting
```
=> clearpath_simulator: 0.0.3-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `flir_camera_driver` to `2.0.2-1`:
- No changes
- No changes
```
* [spinnaker_camera_driver] Added lsb-release as dep.
```
=> flir_camera_driver: 2.0.2-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `serial` to `2.0.0-1`:
- upstream repository: https://github.com/clearpathrobotics/serial-ros2.git
```
* Revert "Merge branch 'ament_cmake'"
This reverts commit 8e0effcd36b855701d9327aecff949d7f2b20e31.
* Revert "Remove test that breaks the build"
This reverts commit 7fe3be8d5f24db9837fff7e5b2fc45dcb464eef0.
* Remove test that breaks the build
* Convert package to ament_cmake
* Fix the build and cleanup CMakeLists
* Add setupapi to ament_export_libraries
This prevents dependent libraries from failing with something like: serial.lib(list_ports_win.obj) : error …
```
=> serial: 2.0.0-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `umx_drver` to `1.0.0-1`:
- upstream repository: https://github.com/ros-drivers/um7
- release repository: https://github.com/ros-drivers-gbp/um7-release.git
```
* Reverted versioning to continue where it left off
* Add instructions and update log for ros 2 version
* Fixed inclusion of serial library in CI
* Updated CI setup-ros tooling version
* Add github ci
* Setup custom tests
* Linting changes
* Updated test files
* Updating for ROS 2 Linting
* Updating to hpp file naming for linting
* Added UM6_driver
* Optimized for speed
* Update structure for separateUM6 and 7 nodes
* More detailed error message
* Setup for ROS 2 and UM7
* folder …
```
=> umx_drver: 1.0.0-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `0.0.2-1`:
- previous version for package: `0.0.1-2`
```
* Sensor namespace
* Param generator
* Launch generator cleanup
* NMEA navsat driver
* Import paths
```
```
* Config update
```
```
* Sensor namespace
* Microstrain namespacing
LMS1xx parameters
```
=> clearpath_robot: 0.0.2-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_onav_description` to `0.1.3-1`:
```
* fix: move lms1xx link back into correct location. this bug was resolve in the intall script. update hokuyo prefix
```
=> cpr_onav_description: 0.1.3-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_nav2_demos` to `0.0.2-1`:
```
* Updated sensor namespace
* Linter fix
```
=> clearpath_nav2_demos: 0.0.2-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `flir_camera_driver` to `2.0.2-2`:
- No changes
- No changes
```
* replace lsb-release with python3-distro
* add dependencies for spinnaker download
* Contributors: Bernd Pfrommer
```
=> flir_camera_driver: 2.0.2-2 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `0.0.5-1`:
```
* Split novatel GPS
* PyTest issues
* Linter issues
* Node names and flatten dictionaries
* Added ros_parameters to extras
* Added Garmin and Novatel gps
* Added node names to rosparameters in sensors
* Update hostname and namespace to match serial
* Resolved indexing issue
```
=> clearpath_config: 0.0.5-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `0.0.9-1`:
- previous version for package: `0.0.8-1`
- No changes
```
* Update platform nodes from extra ros parameters
Flattened default parameter files
```
- No changes
```
* Added Garmin 18x, Novatel smart 6 and 7
* Update platform nodes from extra ros parameters
Flattened default parameter files
```
- No changes
- No changes
- No changes
```
* Added Garmin 18x, Novatel smart 6 and 7
```
=> clearpath_common: 0.0.9-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `dingo_desktop` to `0.1.2-2`:
```
```
```
```
=> dingo_desktop: 0.1.2-2 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `ptz_action_server` to `0.1.3-1`:
- No changes
- No changes
```
* Add the simulated PTZ action server package for Gazebo support
```
=> ptz_action_server: 0.1.3-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_onav_description` to `0.1.4-1`:
```
* fix urdf issue related to including multiple realsense cameras. moved all includes into custom block. each of the standard/starter sub-urdfs have their own include lines for the required sensors.
* 0.1.3
* Changes.
* fix: move lms1xx link back into correct location. this bug was resolve in the intall script. update hokuyo prefix
* Contributors: José Mastrangelo, Tony Baltovski
```
=> cpr_onav_description: 0.1.4-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `ridgeback_firmware` to `0.3.1-1`:
```
* Implement 20s grace period after startup to allow networking startup
```
=> ridgeback_firmware: 0.3.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `axis_camera` to `0.4.8-1`:
- previous version for package: `0.4.7-1`
```
* Fix the image_transport node to publish theora frames of the enable_theora argument is enabled.
* Add fps as an additional argument to the launch file
```
=> axis_camera: 0.4.8-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `0.0.3-1`:
```
* Removed micros-ros-agent as dep.
* Renamed UST10 to UST
Cleaned up generators
* Move author in all package.xml to pass xml linter.
* [clearpath_generator_robot] Added author to package.xml.
* Added UM6/7
* Added Garmin 18x, Smart6 and Smart7
```
```
* Linter
* Move author in all package.xml to pass xml linter.
```
```
* Renamed UST10 to UST
Cleaned …
```
=> clearpath_robot: 0.0.3-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `video_recorder` to `0.0.6-1`:
```
* Latch the is_recording topic
* Improve the default filename formatting
```
- No changes
```
* Latch the is_recording topic
* Use dynamic subscribers to the video topic to preserve bandwidth
* Improve the default filename formatting
```
- No changes
=> video_recorder: 0.0.6-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `numato_relay_interface` to `0.1.3-1`:
- upstream repository: https://github.com/clearpathrobotics/numato_relay_interface.git
- release repository: https://github.com/clearpath-gbp/numato_relay_interface-release.git
```
* Sleep if the specified serial port file doesn't exist (yet)
* Change the relay state topics to be latched and only publish their initial states + new state on change
```
=> numato_relay_interface: 0.1.3-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `realsense_ros` to `2.3.3-1`:
- upstream repository: https://github.com/clearpathrobotics/realsense_ros.git
- release repository: https://github.com/clearpath-gbp/realsense_ros-release.git
```
* Merge branch 'scottnothing-package-includes' into development
* Allow the catkin package to be included in other projects
* Merge pull request #2239 <https://github.com/clearpathrobotics/realsense_ros/issues/2239> from fredotran/development
fix std::find_if issues
* fix std::find_if issues
* Merge pull request #2235 <https://github.com/clearpathrobotics/realsense_ros/issues/2235> from doronhi/fix_metadata_timestamp
Fix Metadata timestamps
* set …
```
=> realsense_ros: 2.3.3-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `0.1.0-1`:
- previous version for package: `0.0.9-1`
- No changes
```
* Formatting
* Removed joy_teleop namespace, remap topics to that namespace instead
```
- No changes
```
* Removed joy_teleop namespace, remap topics to that namespace instead
* Added fenders for J100
* Renamed UST10 to UST
Added parameter node list
* Removed disk import
* Added disk and post
Set default values to model dictionaries
* Inverted and upright sick stand
* Added UM6/7 …
```
=> clearpath_common: 0.1.0-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_simulator` to `0.1.0-1`:
```
* Renamed UST10 to UST
```
```
* Linter
* Renamed UST10 to UST
```
- No changes
=> clearpath_simulator: 0.1.0-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `ptz_action_server` to `0.1.4-1`:
```
* Add the ability to publish the Axis camera's joint states
```
- No changes
- No changes
=> ptz_action_server: 0.1.4-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `clearpath_msgs` to `0.9.1-1`:
- previous version for package: `0.9.0-1`
- No changes
- No changes
```
* Add message field to service response
* Added error message to service response
```
- No changes
- No changes
- No changes
- No changes
```
* Add comments to Waypoint message to match documentation
* Added Metrics.msg
```
```
* Add the stack light messages to the platform messages
* Contributors: Chris Iverach-Brereton, José …
```
=> clearpath_msgs: 0.9.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `microhard_snmp` to `0.0.4-1`:
```
* Add bandwidth throughput to microhard message
* Use px2 by default.
* Better error handling
* Contributors: Michael Hosmar, Mike Hosmar
```
=> microhard_snmp: 0.0.4-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `sevcon_ros` to `0.2.2-1`:
- No changes
```
* Fixed sign on battery current.
```
=> sevcon_ros: 0.2.2-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `clearpath_microhard_gateway` to `0.0.1-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/research/clearpath_microhard_gateway.git
- release repository: https://gitlab.clearpathrobotics.com/gbp/clearpath_microhard_gateway-gbp.git
```
* Initial Release
* Contributors: Michael Hosmar, Mike Hosmar
```
=> clearpath_microhard_gateway: 0.0.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `video_recorder` to `0.0.7-1`:
```
* Fix a typo in the audio recorder node
```
- No changes
- No changes
- No changes
=> video_recorder: 0.0.7-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_onav_description` to `0.1.5-1`:
```
* Add support for Husky Observer
* Add a new macro for the GNSS antennas, including collision bodies
* Add Husky Observer backpack model, Q62 meshes, support for observer configuration
* Fix the path for the Hokuyo mesh, add simplified collision geometry
```
=> cpr_onav_description: 0.1.5-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `video_recorder` to `0.0.8-1`:
- previous version for package: `0.0.7-1`
```
* Add a dependency on alsa-utils
```
- No changes
- No changes
- No changes
=> video_recorder: 0.0.8-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky_observer` to `0.0.2-1`:
- No changes
```
* Clean package dependencies
* Remove the video_recorder dependency since we don't launch video_recorder nodes from here
* Remove dependencies on the NEC, wibotic, and pdu packages; we don't launch them from packageshere and their services can be provided by other sources
* Fix the install path of the peak udev rule
* Fix audio recorder output filepath to save in same location as video/images
* Contributors: Chris …
```
=> husky_observer: 0.0.2-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky_observer` to `0.0.3-1`:
- No changes
- No changes
- No changes
```
* Remove the config directory from the install files since it no longer exists
```
- No changes
- No changes
- No changes
- No changes
- No changes
=> husky_observer: 0.0.3-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `microhard_snmp` to `0.0.5-1`:
```
* properly process cell data
* More error catching
* Contributors: Mike Hosmar
```
=> microhard_snmp: 0.0.5-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_onav_description` to `0.1.6-1`:
```
* Fix the path to the wibotic antenna mesh
```
=> cpr_onav_description: 0.1.6-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `microhard_snmp` to `0.0.6-1`:
```
* syntax error
* Contributors: Mike Hosmar
```
=> microhard_snmp: 0.0.6-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_desktop` to `0.1.0-1`:
- No changes
- No changes
```
* Update scan topic to match other packages
* Update scan topic to match other packages
```
=> clearpath_desktop: 0.1.0-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `0.1.1-1`:
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Update gps and imu names to fix generated topic
* Added Ignition frame names to simulate the real robot
```
```
* Added Ignition frame names to simulate the real robot
```
=> clearpath_common: 0.1.1-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_simulator` to `0.1.1-1`:
```
* Linting
* Added additional supported IMUs and GPSs
* Fix imu and gps bridge topic remapping
* Remove static tf nodes, no longer necessary
* Update topic names to match other packages
```
- No changes
- No changes
=> clearpath_simulator: 0.1.1-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `microhard_snmp` to `0.0.7-1`:
```
* Fix: Handle edge cases for throughput unit parsing
- Previous method relied on the 'units' component being 2 characters which would cause crashes when the incoming value was in bytes (e.g., 100.0B)
```
=> microhard_snmp: 0.0.7-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `0.1.0-1`:
```
* Updated samples to include workspace
```
=> clearpath_config: 0.1.0-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky_observer` to `0.0.4-1`:
- No changes
```
* Slow rotation even more
* Add the cron job to fix the clearpath_files directory permissions
* Unset the wibotic bumper envar as this removes the standard front bumper
* Contributors: Chris Iverach-Brereton, Michael Hosmar
```
```
* Add support for single & dual lidar diagnostics based on envar.
* Add additional topic diagnostics to check for BMS, PDU, and MCU
```
- No …
=> husky_observer: 0.0.4-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `video_recorder` to `0.0.9-1`:
- previous version for package: `0.0.8-1`
```
* Don't abort if we get a double-record or double-stop; treat these as successesful action invocation (but with .success set to false to indicate no new recording was made) and send the existing path if appropriate.
```
- No changes
```
* Don't abort if we get a double-record or double-stop; treat these as successesful action invocation (but with .success set to false to indicate no new recording was …
```
=> video_recorder: 0.0.9-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_onav_description` to `0.1.7-1`:
```
* Expand the readme, add setup scripts for the starter kit on Jackal, Warthog, and Husky.
* Add setup script for the Husky Observer
* Add the RealSense gazebo plugins to the starter kit
```
=> cpr_onav_description: 0.1.7-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `0.1.1-1`:
```
* [clearpath_generator_robot] Re-added micro-ros-agent as exec depend.
```
- No changes
- No changes
=> clearpath_robot: 0.1.1-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky_observer` to `0.0.5-1`:
- No changes
- No changes
- No changes
- No changes
- No changes
```
* The 5V rail is rewired to provide 24V and has the microhard connected; leave it on.
```
- No changes
- No changes
- No changes
=> husky_observer: 0.0.5-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `flir_ptu` to `0.2.3-1`:
- upstream repository: https://github.com/ros-drivers/flir_ptu.git
- release repository: https://github.com/clearpath-gbp/flir_ptu-release.git
- No changes
```
* Expose joint_name_prefix as an arg in the launch file.  This makes it easier to add multiple PTUs.
```
- No changes
=> flir_ptu: 0.2.3-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_nav2_demos` to `0.1.0-1`:
```
* Updated get model function and remapped scan topics
* Update get model function to match clearpath config
* Remap to correct namespacing on scan topics
```
=> clearpath_nav2_demos: 0.1.0-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `clearpath_microhard_gateway` to `0.0.2-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/research/clearpath_microhard_gateway.git
- release repository: https://gitlab.clearpathrobotics.com/gbp/clearpath_microhard_gateway-gbp.git
```
* Merge branch 'ssh-again' into 'main'
Use SSH to change load balancer priority and to monitor current proportion
See merge request research/clearpath_microhard_gateway!2
* Contributors: Michael Hosmar, Mike Hosmar
```
=> clearpath_microhard_gateway: 0.0.2-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky_observer` to `0.0.6-1`:
- No changes
- No changes
```
* Fix the max rate for the wireless connection topic
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
=> husky_observer: 0.0.6-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_onav_description` to `0.1.8-1`:
```
* Don't pull in axis q62 meshes for all axis ptz camera integrations; a new mesh for dome-style cameras will be added in a future release
```
=> cpr_onav_description: 0.1.8-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `warthog` to `0.1.8-1`:
```
* [warthog_contorl] Updated diff_drive_controller parameters.
```
- No changes
- No changes
=> warthog: 0.1.8-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `clearpath_microhard_gateway` to `0.0.3-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/research/clearpath_microhard_gateway.git
- release repository: https://gitlab.clearpathrobotics.com/gbp/clearpath_microhard_gateway-gbp.git
```
* Merge branch 'mod/observer_updates' into 'main'
Mod: Refactoring based on observer testing
See merge request research/clearpath_microhard_gateway!4
* Mod: Refactoring based on observer testing
* Merge branch 'mod/topic_latching' into 'main'
Mod: Latch ~use_lte topic and only publish on change
See merge request research/clearpath_microhard_gateway!3
* Mod: Latch ~use_lte topic and only …
```
=> clearpath_microhard_gateway: 0.0.3-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_onav_description` to `0.1.9-1`:
```
* Add the ground truth odometry plugin for simulation support
* Reduce the target FPS of the RealSense simulations to 6FPS, to match with physical hardware configuration
```
=> cpr_onav_description: 0.1.9-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `0.1.1-1`:
```
* Removed micro_ros_ws
* Velodyne changes
* clearpath_config/sensors/types/lidars_2d.py
* FPS expected as float
* Added ros_parameter_template
```
=> clearpath_config: 0.1.1-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `0.1.2-1`:
- No changes
- No changes
- No changes
```
* Adds Blackfly camera to sensor description (#33 <https://github.com/clearpathrobotics/clearpath_common/issues/33>)
* Adds Blackfly camera to sensor description
---------
Co-authored-by: fazzrazz <mailto:danielduranrojas@gmail.com>
```
- No changes
- No changes
- No changes
```
* Adds Blackfly camera to sensor description (#33 …
```
=> clearpath_common: 0.1.2-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `0.1.3-1`:
- No changes
```
* Run platform and sensor services as user
```
```
* Removed 'platform' from default namespace
* Added image proc as container
* Missing comma
* Correct debayer node and add remapping
* Added debayer node
* Removed errant bracket
* add serial number to yaml
* Initial Blackfly addition
```
=> clearpath_robot: 0.1.3-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_simulator` to `0.1.2-1`:
```
* Initial addition of Blackfly (#19 <https://github.com/clearpathrobotics/clearpath_simulator/issues/19>)
* Initial addition of Blackfly
```
- No changes
- No changes
=> clearpath_simulator: 0.1.2-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `flir_camera_driver` to `2.0.7-2`:
- previous version for package: `2.0.3-1`
- No changes
- No changes
```
* Restricted the device permissions
* Added Teledyne to udev as requested
* Added udev rule
```
=> flir_camera_driver: 2.0.7-2 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_desktop` to `0.1.1-1`:
```
* [clearpath_config_live] Removed unused import.
* [clearpath_config_live] Added periods to all comments for pep257.
```
```
* Added config live dependency
```
- No changes
=> clearpath_desktop: 0.1.1-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_desktop` to `0.1.2-1`:
```
* Pass setup path to clearpath_config
```
- No changes
```
* rqt_robot_monitor dep
* View diagnostics
Added license
* Pass setup path to clearpath_config
* Contributors: Luis Camero, Roni Kreinin
```
=> clearpath_desktop: 0.1.2-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `clearpath_msgs` to `0.9.2-1`:
- previous version for package: `0.9.1-1`
```
* Fix over & underline length in changelogs
```
```
* Fix over & underline length in changelogs
```
```
* Use raw JSON strings for import & export; don't bother gzipping & base-64 encoding them
* Add import/export services for docking
* Fix over & underline length in changelogs
```
```
* Add: .srv definition for …
```
=> clearpath_msgs: 0.9.2-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
We're adding humble support to the Numato Relay Interface package, so the Noetic branch is changing from `main` to `noetic-devel`
=> Change branch for numato_relay_interface

noetic/distribution.yaml
Increasing version of package(s) in repository `clearpath_msgs` to `0.9.3-1`:
- previous version for package: `0.9.2-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Added trigger_type field and include in message generation
```
=> clearpath_msgs: 0.9.3-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `clearpath_msgs` to `0.9.4-1`:
- previous version for package: `0.9.3-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Remove dependencies on packages not released to OSRF
```
- No changes
- No changes
- No changes
=> clearpath_msgs: 0.9.4-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `clearpath_onav_examples` to `0.0.2-1`:
- upstream repository: https://github.com/cpr-application/clearpath_onav_examples.git
- release repository: https://github.com/clearpath-gbp/clearpath_onav_examples-release.git
- No changes
```
* Modify the coordinate_lat_lon class to use pyproj instead of the utm package
```
- No changes
=> clearpath_onav_examples: 0.0.2-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_onav_backup` to `0.0.1-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/cpr-outdoornav/cpr_onav_backup.git
- release repository: https://gitlab.clearpathrobotics.com/gbp/cpr_onav_backup-release.git
```
* Initial Release
* Contributors: Chris Iverach-Brereton, Drew O'Brien
```
```
```
=> cpr_onav_backup: 0.0.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky_observer` to `0.0.8-1`:
```
* Add dependencies on clearpath_msgs and onav_backup_msgs
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
=> husky_observer: 0.0.8-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_onav_description` to `0.1.10-1`:
```
* Add: Custom 3d_lidar.urdf.xacro for simulating VLP16 / 3d lidars
* Mod: Decrease Hokuyo update rate from 50->10 Hz
```
=> cpr_onav_description: 0.1.10-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `clearpath_msgs` to `0.9.5-1`:
- previous version for package: `0.9.4-1`
```
* Merge remote-tracking branch 'origin/noetic-devel' into ONAV-1771/on_start_stop_tasks
```
```
* Merge remote-tracking branch 'origin/noetic-devel' into ONAV-1771/on_start_stop_tasks
```
```
* Merge remote-tracking branch 'origin/noetic-devel' into ONAV-1771/on_start_stop_tasks
```
```
* Merge remote-tracking branch 'origin/noetic-devel' into …
```
=> clearpath_msgs: 0.9.5-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_simulator` to `0.1.3-1`:
- No changes
```
* closes #16 <https://github.com/clearpathrobotics/clearpath_simulator/issues/16> (#17 <https://github.com/clearpathrobotics/clearpath_simulator/issues/17>)
Fixes Lidar rays when running without a GPU, still works with GPU
* Contributors: Arthur Gomes
```
- No changes
=> clearpath_simulator: 0.1.3-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `0.1.3-1`:
- No changes
- No changes
- No changes
- No changes
```
* Load bracket XYZ from block
```
- No changes
```
* [clearpath_platform_description] Removed un-used ros2_control params.
```
- No changes
=> clearpath_common: 0.1.3-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `clearpath_onav_examples` to `0.0.4-1`:
- upstream repository: https://github.com/cpr-application/clearpath_onav_examples.git
- release repository: https://github.com/clearpath-gbp/clearpath_onav_examples-release.git
- No changes
```
* Fix adding tasks to waypoints
* Added updates to Mission action and Task failure
* Added from_start and start_waypoint defaults
* Remove default values for start_waypoint_num and from_start mission argument
* Added allow_failure to Task class. Fix ordering of defualt parameters of MIsion class
* Added from_start and start waypoint information to Mission class
```
- No …
=> clearpath_onav_examples: 0.0.4-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky_observer` to `0.0.10-1`:
- previous version for package: `0.0.9-1`
```
* Add can-utils to the bringup package's dependencies, add additional messages to the metapackage
```
```
* Add can-utils to the bringup package's dependencies, add additional messages to the metapackage
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
=> husky_observer: 0.0.10-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `axis_camera` to `0.5.0-1`:
- previous version for package: `0.4.8-1`
```
* Major overhaul for better PTZ support (#80 <https://github.com/ros-drivers/axis_camera/issues/80>)
* Move the messages out of the driver and into their own package
* Migrating essential components into the src folder so we can use a single ROS node to contain both the video & ptz functionality. Start filling necessary messages & services for incoming features
* Remove the old axis and axis_ptz nodes, roll both into the new axis_camera_node script with the …
```
=> axis_camera: 0.5.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `ptz_action_server` to `0.1.6-1`:
```
* Major overhaul to add new control modes (#4 <https://github.com/clearpathrobotics/ptz_action_server/issues/4>)
* Rename PtzPosition.msg to PtzState.msg, add support for velocity control. Rename .../move_ptz action to .../position, add .../velocity to Axis camera to allow velocity control
* Add support for move_ptz/position_abs and move_ptz/position_rel actions
* Update the readme
* Add support for absolute & relative positions for …
```
=> ptz_action_server: 0.1.6-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky_observer` to `0.0.12-1`:
- previous version for package: `0.0.10-1`
- No changes
- No changes
```
* Fix the actions that the diagnostics monitor checks for
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
=> husky_observer: 0.0.12-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky_observer` to `0.0.13-1`:
- previous version for package: `0.0.12-1`
- No changes
```
* Add husky_observer_bringup/scripts/environment to /etc/ros/setup.bash
```
```
* Revert changes to RealSense sensor topic names
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
=> husky_observer: 0.0.13-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `sevcon_ros` to `1.0.0-1`:
```
* Initial pass at ROS 2.
```
```
* Initial pass at ROS 2.
```
=> sevcon_ros: 1.0.0-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `axis_camera` to `0.5.1-1`:
- previous version for package: `0.5.0-1`
```
* Remove an unnecessary import
```
- No changes
- No changes
=> axis_camera: 0.5.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `ptz_action_server` to `0.1.7-1`:
- No changes
```
* Fix the dependencies for the Flir PTU action server
```
- No changes
- No changes
=> ptz_action_server: 0.1.7-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky_observer` to `0.0.14-1`:
- previous version for package: `0.0.13-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Improve exception-handling for the buzzer on/off service calls. Resolves ONAV-1912
```
- No changes
- No changes
=> husky_observer: 0.0.14-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `sevcon_ros` to `1.0.1-1`:
- No changes
```
* Updated dep.
```
=> sevcon_ros: 1.0.1-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `sevcon_ros` to `1.0.2-1`:
- No changes
```
* Added boost include dirs.
```
=> sevcon_ros: 1.0.2-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky_robot` to `0.6.10-2`:
- previous version for package: `0.6.9-1`
- No changes
```
* Update realsense.launch
```
- No changes
=> husky_robot: 0.6.10-2 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `canfestival_ros` to `1.0.1-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/research/canfestival_ros.git
- release repository: https://gitlab.clearpathrobotics.com/gbp/canfestival_ros-gbp.git
```
* Reduced logging.
```
=> canfestival_ros: 1.0.1-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_msgs` to `0.2.0-1`:
- No changes
```
* Added charger connected status to Power message
* Removed 48V current
* Removed HMI msg
* Renamed platform constants to use platform code
Added HMI message
```
=> clearpath_msgs: 0.2.0-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `axis_camera` to `0.5.2-1`:
- previous version for package: `0.5.1-1`
```
* Add the config directory to the install targets
```
- No changes
- No changes
=> axis_camera: 0.5.2-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `0.2.0-2`:
```
* Added wheel parameter to platform
* Fixed typo
* Added dd150 samples
* Added dd100 samples
* Fixed origin of pacs mounts
* Renamed SLA on Dingo
* Added entries for all dingo
* Updated sample to match attachments rework
* Fixed merge issues
* Added more warthog samples
* Updated sample default_mount
* Removed duplicate
* Added W200 attachments
* Updated default mounts on j100
* Updated default mounts on a200
* Changed default parent …
```
=> clearpath_config: 0.2.0-2 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_simulator` to `0.2.1-1`:
```
* Added all dingo to generator
```
- No changes
- No changes
=> clearpath_simulator: 0.2.1-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `0.2.0-1`:
```
* Added S1P2 battery configuration
* Set battery charging status
* Added dingo to battery state control
* Added D100 and D150 to generator and battery node
* Generate lighting node
* Fixed status message firmware version
* J100 -> W200
* Removed shebang
* Use battery model and configuration from clearpath_config
* Removed HMI msg, encode Uint8 instead
* Initial battery control node
* Renamed to battery_state_estimator
Added to robot …
```
=> clearpath_robot: 0.2.0-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `sevcon_ros` to `1.0.3-1`:
- previous version for package: `1.0.2-1`
- No changes
```
* Added boost as dep.
* Revert "Always reset command timer if any command is recieved."
This reverts commit d992bf072e0a119cba394cf277941ebd0b0b81f4
* Reduced log to debug.
* Changed error log to use hex value.
* Always reset command timer if any command is recieved.
* Fixed typo.
* Added error code log.
* Increased command timeout.
```
=> sevcon_ros: 1.0.3-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky_observer` to `0.0.15-1`:
- previous version for package: `0.0.14-1`
- No changes
```
* Add dependency on husky_observer_teleop
```
```
* Modify diagnostics topic for both AXIS PTZ changes and for using uncompressed images
```
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Add D-Pad support to control front/rear driving lights
```
- No changes
=> husky_observer: 0.0.15-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `0.2.1-1`:
- No changes
```
* Added missing dependency
```
- No changes
- No changes
=> clearpath_robot: 0.2.1-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `clearpath_msgs` to `0.9.6-1`:
- previous version for package: `0.9.5-1`
- No changes
- No changes
- No changes
- No changes
```
* Add a new service for deleting multiple IDs at once
* Add a new service to import entire mission objects, including their associated tasks & waypoints
```
- No changes
- No changes
- No changes
- No changes
- No changes
=> clearpath_msgs: 0.9.6-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `0.2.1-1`:
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* PACS top plate was not centred with generated frames
```
- No changes
=> clearpath_common: 0.2.1-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `video_recorder` to `0.0.10-1`:
- previous version for package: `0.0.9-1`
```
* Add the mount_path argument & parameter to the audio recorder node to allow remapping the result directory if e.g. this node is run inside a docker container
```
- No changes
```
* Add the mount_path argument & parameter to the vidio recorder node to allow remapping the result directory if e.g. this node is run inside a docker container
```
- No changes
=> video_recorder: 0.0.10-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_ridgeback` to `0.4.0-1`:
```
* Update to use Otto's 2.26 release
```
=> cpr_indoornav_ridgeback: 0.4.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_dingo` to `0.4.0-1`:
```
* Update to use Otto's 2.26 release
```
=> cpr_indoornav_dingo: 0.4.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_husky` to `0.4.0-1`:
- previous version for package: `0.3.5-1`
```
* Update to work with Otto's 2.26 release
* Add improved support for Husky Observer
```
=> cpr_indoornav_husky: 0.4.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_jackal` to `0.4.0-1`:
```
* Update to use Otto's 2.26 release
```
=> cpr_indoornav_jackal: 0.4.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_base` to `0.4.0-1`:
```
* Create common installation classes to reduce code duplication in dependent packages
* Update base package to use Otto's 2.26 release
```
=> cpr_indoornav_base: 0.4.0-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `0.2.2-1`:
- No changes
- No changes
- No changes
```
* Enable extras urdf and meshes to be linked by package (#53 <https://github.com/clearpathrobotics/clearpath_common/issues/53>)
```
- No changes
```
* Fixed status topic names
```
- No changes
- No changes
=> clearpath_common: 0.2.2-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `0.2.2-1`:
```
* Fix how blank urdf extras is handled
```
=> clearpath_config: 0.2.2-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `0.2.3-1`:
- No changes
- No changes
- No changes
```
* Handle file paths with no directory (files in root directory of the package)
```
- No changes
- No changes
- No changes
- No changes
=> clearpath_common: 0.2.3-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `ptz_action_server` to `0.1.8-1`:
```
* Apply the logical -> physical zoom scaling when sending the absolute zoom level to the Axis driver. Remove an unnecessary debug print
```
- No changes
- No changes
- No changes
=> ptz_action_server: 0.1.8-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `ptz_action_server` to `0.1.9-1`:
```
* Fix a bug in translating the zoom level from the logical to hardware range
```
- No changes
- No changes
- No changes
=> ptz_action_server: 0.1.9-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `sevcon_ros` to `1.0.4-1`:
- previous version for package: `1.0.3-1`
- No changes
```
* Dropped pytho2 dep since not generating object dict anymore.
* Updated logging level.
* Removed generating objdictgen files.
```
=> sevcon_ros: 1.0.4-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `0.2.2-1`:
```
* Get topic without namespace to address duplicate namespacing
```
```
* [clearpath_generator_robot] Re-added sevcon_traction as dependency.
```
- No changes
- No changes
=> clearpath_robot: 0.2.2-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `0.2.3-1`:
```
* Give option to get topic without namespace
```
=> clearpath_config: 0.2.3-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `0.2.4-1`:
- No changes
- No changes
- No changes
```
* [clearpath_generator_common] Added package description.
```
- No changes
```
* Fixed lighting lib install
```
- No changes
- No changes
=> clearpath_common: 0.2.4-1 in 'humble/distribution.yaml' [bloom]

rosdep/noetic.yaml
Add `onav_cli` dependency for new OutdoorNav command-line tools
=> Add onav-cli as a rosdep

noetic/distribution.yaml
Increasing version of package(s) in repository `nav_mode_switcher` to `0.0.1-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/research/nav_mode_switcher.git
- release repository: https://gitlab.clearpathrobotics.com/gbp/nav_mode_switcher-release.git
```
```
```
```
=> nav_mode_switcher: 0.0.1-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `0.2.5-1`:
- No changes
- No changes
- No changes
```
* switch finding meshes to use the package:// command
```
- No changes
- No changes
```
* switch finding meshes to use the package:// command
```
- No changes
=> clearpath_common: 0.2.5-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_simulator` to `0.2.2-1`:
- No changes
```
* Add all sourced ros packages to gazebo resource path to address user workspaces with custom meshes
```
- No changes
=> clearpath_simulator: 0.2.2-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `axis_camera` to `0.5.3-1`:
- previous version for package: `0.5.2-1`
```
* Use the legacy IR URL by default, falling back to the new one if it's not available; on legacy cameras the new URL returns status 200, even though it doesn't do anything (#81 <https://github.com/ros-drivers/axis_camera/issues/81>)
```
- No changes
- No changes
=> axis_camera: 0.5.3-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `0.2.3-1`:
- No changes
```
* Removed namespaced tf_static
```
- No changes
- No changes
=> clearpath_robot: 0.2.3-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `0.2.6-1`:
- No changes
```
* Disable tf_frame_prefix_enable
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
=> clearpath_common: 0.2.6-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_simulator` to `0.2.3-1`:
```
* Removed print
* Removed namespaced tf_static
* 0.2.2
* Changes.
* 0.2.1
* Changes.
* Added all dingo to generator
* 0.2.0
* Changes.
* Added Warthog and Dingo to generator
* Added Generic robot components
* Sensor static tf should use robot namespace
* Contributors: Luis Camero, Roni Kreinin, Tony Baltovski, luis-camero
```
```
* 0.2.2
* Changes.
* Add all sourced ros packages to gazebo resource path to address user …
```
=> clearpath_simulator: 0.2.3-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `0.2.4-1`:
- No changes
- No changes
```
* [clearpath_robot] Added udev rule for STM32 ROM bootloader.
```
- No changes
=> clearpath_robot: 0.2.4-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `0.2.4-1`:
```
* Install the W200 samples.
* Fixed j100 and w200 laser sample
```
=> clearpath_config: 0.2.4-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_nav2_demos` to `0.2.0-1`:
```
* Increased inflation radius
* Added W200 configs
```
=> clearpath_nav2_demos: 0.2.0-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `valence_bms` to `1.0.1-1`:
- release repository: https://gitlab.clearpathrobotics.com/gbp/valence_bms-gbp.git
- No changes
```
* [valence_bms_msgs] Fixed package.xml and CMakeLists.txt.
```
=> valence_bms: 1.0.1-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `valence_bms` to `1.0.2-1`:
- release repository: https://gitlab.clearpathrobotics.com/gbp/valence_bms-gbp.git
- No changes
```
* [valence_bms_msgs] Removed lint test.
```
=> valence_bms: 1.0.2-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `axis_camera` to `0.5.4-1`:
- previous version for package: `0.5.3-1`
```
* Change default PS4 controller inputs (#84 <https://github.com/ros-drivers/axis_camera/issues/84>)
* Refactor the teleop controls to make enable buttons optional, change the defaults to use the right thumb stick for pan/tilt and right/left analog triggers for zoom in/out
* Fix comments in the PS4 controller configuration file, add an additional file with the alternative axis ordering (which is necessary for some controllers)
* Expose the teleop config file …
```
=> axis_camera: 0.5.4-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `clearpath_msgs` to `0.9.7-1`:
- previous version for package: `0.9.6-1`
```
* Merge pull request #30 <https://github.com/clearpathrobotics/clearpath_msgs/issues/30> from clearpathrobotics/ONAV-166
updated autonomy config msg
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
=> clearpath_msgs: 0.9.7-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `jackal` to `0.8.9-1`:
- previous version for package: `0.8.8-1`
- No changes
```
* Fixed origin pose values.
```
- No changes
- No changes
- No changes
=> jackal: 0.8.9-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `0.2.5-1`:
```
* Add republishers to camera
* Added battery launch arguments to support launching the valence bms node
* Fix ros_parameters
```
=> clearpath_config: 0.2.5-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `wireless` to `1.0.1-3`:
- previous version for package: `1.0.1-2`
- No changes
```
* [wireless_watcher] Switched to underscores to get rid of usage of dash-separated warning.
```
=> wireless: 1.0.1-3 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `0.2.5-1`:
- No changes
```
* Add valence dependency
* Launch Valence BMS when relevant
* Rename node based on input
* Added rectify and resize
* Float hz parameter
* Contributors: Hilary Luo, Luis Camero, Roni Kreinin
```
- No changes
```
* Added image_transport_plugins to package.xml
* Added binning parameters
* Recitfy node matches resize
* Added compressed encode and decode launch files
* Fixed theora encoding node
* Add theora encode and decode …
```
=> clearpath_robot: 0.2.5-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky_observer` to `0.0.17-1`:
- previous version for package: `0.0.16-1`
- No changes
```
* Remove config extras file from environment script. Closes ONAV-2205
* Contributors: Michael Hosmar
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
=> husky_observer: 0.0.17-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `clearpath_msgs` to `0.9.8-1`:
- previous version for package: `0.9.7-1`
- No changes
- No changes
```
* Add additional messages for Network of Paths
* Contributors: Chris Iverach-Brereton <mailto:civerachb@clearpathrobotics.com>, Stephen Phillips <mailto:stphillips@clearpathrobotics.com>
```
```
* Add additional messages for Network of Paths
* Contributors: Chris Iverach-Brereton <mailto:civerachb@clearpathrobotics.com>, Stephen Phillips <mailto:stphillips@clearpathrobotics.com>
```
```
* Add additional messages for …
```
=> clearpath_msgs: 0.9.8-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `clearpath_msgs` to `0.9.9-1`:
- previous version for package: `0.9.8-1`
- No changes
- No changes
```
* Message updates for onav-0.12 (#34 <https://github.com/clearpathrobotics/clearpath_msgs/issues/34>)
* Add the size_exceeded field to NetworkMapState
* Mod: Update dock messages for new 0.12 docking APIs
* Mod: Add new autonomy API types to AutonomyStatus.msg
* Mod: Use float64 version of Vector2D for returning path recording lat-lons
* Mod: Add header field to RunNetworkGoToPlanner.action feedback
--------- …
```
=> clearpath_msgs: 0.9.9-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `jackal_robot` to `0.7.10-1`:
- previous version for package: `0.7.9-1`
- No changes
```
* Removed typo
* Moved remap out of the include tag
```
- No changes
=> jackal_robot: 0.7.10-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky` to `0.6.10-1`:
- previous version for package: `0.6.8-1`
```
* Mod: Set 'publish_cmd' param to true in husky_control/config
- With this change the diff drive controller will output the final cmd_vel to /husky_velocity_controller/cmd_vel_out after any filters are applied (e.g., speed/acceleration limits).
```
```
* Add simplified collision geometry to the URDF
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
=> husky: 0.6.10-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_dingo` to `0.4.1-1`:
```
* Swap the priorities of /cmd_vel and /manual/cmd_vel to enable teleop assist via the GUI
```
=> cpr_indoornav_dingo: 0.4.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_husky` to `0.4.1-1`:
```
* Swap the priorities of /cmd_vel and /manual/cmd_vel to enable teleop assist via the GUI
* Remove Config_extras export for outdoornav
* Contributors: Chris Iverach-Brereton, Michael Hosmar, José Mastrangelo
```
=> cpr_indoornav_husky: 0.4.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_jackal` to `0.4.1-1`:
```
* Swap the priorities of /cmd_vel and /manual/cmd_vel to enable teleop assist via the GUI
* Remove Control_extras export for outdoornav
* Contributors: Chris Iverach-Brereton, Michael Hosmar, José Mastrangelo
```
=> cpr_indoornav_jackal: 0.4.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_ridgeback` to `0.4.1-1`:
```
* Swap the priorities of /cmd_vel and /manual/cmd_vel to enable teleop assist via the GUI
```
=> cpr_indoornav_ridgeback: 0.4.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_onav_description` to `0.1.11-1`:
```
* Added teleop urdf functionality
* Add the top-down SVGs for Husky Observer
```
=> cpr_onav_description: 0.1.11-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky_observer` to `0.0.18-1`:
- previous version for package: `0.0.17-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Subscribe to cmd_vel_out instead of cmd_vel. Update subscriber function to use TwistStamped instead of Twist
```
- No changes
- No changes
- No changes
=> husky_observer: 0.0.18-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky_observer` to `0.0.19-1`:
- previous version for package: `0.0.18-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Added new topics for assisted_teleop
```
- No changes
- No changes
=> husky_observer: 0.0.19-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `0.2.7-1`:
- No changes
- No changes
```
* Removed author tag
* Fixed mismatched tag
* Updated package.xml to match
* Extra namespace to device launch
* Fixed URDF issues
* Fixed package and executable name
* Added customization package
* Removed author tag
* Fixed mismatched tag
* Updated package.xml to match
* Extra namespace to device launch
* Fixed URDF issues
* Fixed package and executable name
* Added customization …
```
=> clearpath_common: 0.2.7-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `0.2.6-1`:
- No changes
```
* Add extra launch file to sensor service
```
```
* Removed the argument to source
* Added platform and sensor service to robot service wants
* Added discovery server service
```
- No changes
=> clearpath_robot: 0.2.6-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `0.2.7-1`:
- No changes
```
* Check the correct launch file
```
- No changes
- No changes
=> clearpath_robot: 0.2.7-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky_observer` to `0.0.20-1`:
- previous version for package: `0.0.19-1`
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Use onav-cli to start/stop the docker services instead of manually using docker compose commands. Remove the docker_dir parameter
```
- No changes
- No changes
- No changes
- No changes
=> husky_observer: 0.0.20-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `wireless` to `1.1.0-1`:
- previous version for package: `1.0.1-3`
- No changes
```
* License
* Reimplemented in C++
* Use time.sleep instead of rate.sleep to properly exit loop on external shutdown
Default 'dev' parameter to empty string rather than None
```
=> wireless: 1.1.0-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky_observer` to `0.0.21-1`:
- previous version for package: `0.0.20-1`
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Fix a bug where docker services were not being started/stopped correctly when enabling/disabling low-power mode
```
- No changes
- No changes
- No changes
- No changes
=> husky_observer: 0.0.21-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `ridgeback_robot` to `0.4.3-2`:
- previous version for package: `0.4.3-1`
- No changes
```
* Add microstrain_inertial_driver to support current Microstrain IMU models (#37 <https://github.com/ridgeback/ridgeback_robot/issues/37>)
* Add microstrain_inertial_driver for supporting current Microstrain IMU models.
* Remove accidental copy
* Clearer comments for RIDGEBACK_IMU_MICROSTRAIN.
```
- No changes
=> ridgeback_robot: 0.4.3-2 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_simulator` to `0.2.4-1`:
- No changes
```
* Commented out models that are currently broken in the fuel server
```
- No changes
=> clearpath_simulator: 0.2.4-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `warthog` to `0.1.9-1`:
```
* Mod: Set 'publish_cmd' param to true in warthog_control/config
- With this change the diff drive controller will output the final cmd_vel to /warthog_velocity_controller/cmd_vel_out after any filters are applied (e.g., speed/acceleration limits)
```
```
* Updated meshes to add antennas and E-stop buttons
* Remove robotNamespace in .gazebo file
* Contributors: Antonio Manuel Burgueño Romero, Luis Camero
```
- No changes
=> warthog: 0.1.9-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `0.2.8-1`:
- previous version for package: `0.2.7-1`
- No changes
- No changes
- No changes
- No changes
```
* Fix: Remove IP address from discovery server launch so it listens on all NICs
```
- No changes
- No changes
- No changes
- No changes
=> clearpath_common: 0.2.8-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `0.2.8-1`:
- previous version for package: `0.2.7-1`
```
* Even more lint errors
* More linting changes
* Fixed linting errors
```
```
* Lint error in test
* Workspace install paths
* Ignore error from deleting clearpath temp folder
* More linting changes
* Fixed linting errors
* Added pytest to check config
* Fixed linter errors
```
```
* Ensure that the network interfaces are active before clearpath_robot service starts - required for …
```
=> clearpath_robot: 0.2.8-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `0.2.9-1`:
- previous version for package: `0.2.8-1`
- No changes
```
* Fix tf_static for realsense and microstrain
```
- No changes
```
* Fix tf_static for realsense and microstrain
```
=> clearpath_robot: 0.2.9-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `camera_info_manager_py` to `1.0.0-1`:
- upstream repository: https://github.com/clearpathrobotics/camera_info_manager_py.git
- release repository: https://github.com/clearpath-gbp/camera_info_manager_py-release.git
```
* Ros2 (#2 <https://github.com/clearpathrobotics/camera_info_manager_py/issues/2>)
* Run magic converter
* Ament_python package
* Fix some imports
* Remove references to cpp camera info manager.
Disable tests
* Linting
* Fully Remove old tests
* Add lint tests
* Final tests
* Remove pep257 from depends
* Contributors: Michael Hosmar
```
=> camera_info_manager_py: 1.0.0-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `0.2.10-1`:
- previous version for package: `0.2.9-1`
- No changes
- No changes
```
* Block microstrain in J100 MCU udev rule
```
- No changes
=> clearpath_robot: 0.2.10-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `nmea_navsat_driver` to `2.0.2-1`:
- upstream repository: https://github.com/clearpathrobotics/nmea_navsat_driver.git
- release repository: https://github.com/clearpath-gbp/nmea_navsat_driver-release.git
```
* Changed tf_transformations to python3-transforms3d.
* Sentence field must be of type str (#173 <https://github.com/clearpathrobotics/nmea_navsat_driver/issues/173>)
In nmea_topic_serial_reader, sentence field is a bytes object and should be a str object.
Fixes: https://github.com/ros-drivers/nmea_navsat_driver/issues/172
Co-authored-by: Fletcher Thompson <mailto:fletho@dtu.dk>
* Contributors: FletcherFT, Tony Baltovski
```
=> nmea_navsat_driver: 2.0.2-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `ptz_action_server` to `2.0.1-1`:
- No changes
=> ptz_action_server: 2.0.1-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `axis_camera` to `2.0.0-1`:
```
* Initial release for ROS 2
* Contributors: Chris Iverach-Brereton, Mike Hosmar
```
```
* Initial release for ROS 2
* Contributors: Chris Iverach-Brereton, Mike Hosmar
```
```
* Initial release for ROS 2
* Contributors: Chris Iverach-Brereton, Mike Hosmar
```
=> axis_camera: 2.0.0-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `axis_camera` to `2.0.1-1`:
```
* Remove the unused Axis.msg (all relevant information is now published in independent topics). Fix action imports in axis_ptz
```
- No changes
```
* Remove the unused Axis.msg (all relevant information is now published in independent topics). Fix action imports in axis_ptz
```
=> axis_camera: 2.0.1-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `jackal` to `0.8.10-1`:
- previous version for package: `0.8.9-1`
```
* Removed Z position
* Mod: Set 'publish_cmd' param to true in jackal_control/config
- With this change the diff drive controller will output the final cmd_vel to /jackal_velocity_controller/cmd_vel_out after any filters are applied (e.g., speed/acceleration limits)
* Contributors: Luis Camero, Stephen Phillips
```
- No changes
- No changes
- No changes
- No changes
=> jackal: 0.8.10-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_onav_description` to `0.1.12-1`:
- previous version for package: `0.1.11-1`
```
* Fix the Axis camera prefixes so we can more-easily identify the sensor frames
* Changed prefix for ptz cameras
* Added antenna links to urdf
* Change axis_ptz_num to axis_q62_num for Q62 specific entries
* Use the axis_description package for the camera URDFs, add axis dome camera meshes
* Add ptz camera links to urdf
* Added color of xvn unit
* Fix axis of xvn stl file
* Added xvn stl to model
* Revert fender fix. use …
```
=> cpr_onav_description: 0.1.12-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_tests` to `0.3.3-1`:
```
* Improve support for different IMUs
```
=> cpr_indoornav_tests: 0.3.3-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_ridgeback` to `0.4.2-1`:
```
```
=> cpr_indoornav_ridgeback: 0.4.2-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_jackal` to `0.4.2-1`:
```
```
=> cpr_indoornav_jackal: 0.4.2-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_husky` to `0.4.2-1`:
```
* Modify the husky power monitor node to subscribe to multiple inputs to more gracefully handle lithium battery upgrades
```
=> cpr_indoornav_husky: 0.4.2-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_dingo` to `0.4.2-1`:
```
```
=> cpr_indoornav_dingo: 0.4.2-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_base` to `0.4.1-1`:
```
* Typo
* Use Galactic by default; foxy doesn't seem to play nicely with IndoorNav 2.26
```
=> cpr_indoornav_base: 0.4.1-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `video_recorder` to `0.1.0-1`:
- previous version for package: `0.0.10-1`
```
* Add a header to the result objects for all actions (#6 <https://github.com/clearpathrobotics/video_recorder/issues/6>)
```
```
* Add a header to the result objects for all actions (#6 <https://github.com/clearpathrobotics/video_recorder/issues/6>)
```
```
* Add a header to the result objects for all actions (#6 …
```
=> video_recorder: 0.1.0-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `ridgeback_robot` to `0.4.4-1`:
- previous version for package: `0.4.3-2`
- No changes
```
* Updated Microstrain Configuration
```
- No changes
=> ridgeback_robot: 0.4.4-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky_robot` to `0.6.11-1`:
- previous version for package: `0.6.10-2`
- No changes
```
* Updated Microstrain Configuration
```
- No changes
=> husky_robot: 0.6.11-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `dingo_robot` to `0.3.2-1`:
- No changes
```
* Updated Microstrain config
* Updated realsense tf_prefix in nodelet launch to match urdf
```
- No changes
=> dingo_robot: 0.3.2-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `0.2.9-1`:
- previous version for package: `0.2.8-1`
```
* Added Zed to configuration
* Added Zed as type of camera
```
=> clearpath_config: 0.2.9-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `0.2.9-1`:
- previous version for package: `0.2.8-1`
- No changes
- No changes
```
* Customization linting errors
```
- No changes
```
* Modified common parameter generation to always flatten
* Added Zed to description generator
* Add sysctl config file that changes ipfrag settings to support receiving large messages
* Linting
* Generator linting erros
* Added tests
```
- No changes
- No changes
- No changes
```
* Added Zed …
```
=> clearpath_common: 0.2.9-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_simulator` to `0.2.5-1`:
```
* Added Zed to simulator
```
- No changes
- No changes
=> clearpath_simulator: 0.2.5-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `0.2.11-1`:
- previous version for package: `0.2.10-1`
- No changes
- No changes
- No changes
```
* Added Zed launch and configuration files
```
=> clearpath_robot: 0.2.11-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `video_recorder` to `0.1.1-1`:
```
* Fix the timestamp assignment in the audio recorder
```
- No changes
- No changes
- No changes
=> video_recorder: 0.1.1-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `axis_camera` to `2.0.1-2`:
```
* Remove the unused Axis.msg (all relevant information is now published in independent topics). Fix action imports in axis_ptz
```
- No changes
```
* Remove the unused Axis.msg (all relevant information is now published in independent topics). Fix action imports in axis_ptz
```
=> axis_camera: 2.0.1-2 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `axis_camera` to `2.0.2-2`:
- previous version for package: `2.0.1-2`
- No changes
- No changes
- No changes
=> axis_camera: 2.0.2-2 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_jackal` to `0.4.3-1`:
```
* Use the new ROS 2 API packages
```
=> cpr_indoornav_jackal: 0.4.3-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_ridgeback` to `0.4.3-1`:
```
* Use the new ROS 2 API packages
```
=> cpr_indoornav_ridgeback: 0.4.3-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_husky` to `0.4.3-1`:
```
* Use the new ROS 2 API packages
```
=> cpr_indoornav_husky: 0.4.3-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_dingo` to `0.4.3-1`:
```
* Use the new ROS 2 API packages
```
=> cpr_indoornav_dingo: 0.4.3-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_base` to `0.4.2-1`:
```
* Remove dependency on the old clearpath_api package, install the new api packages
```
=> cpr_indoornav_base: 0.4.2-1 in 'noetic/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `clearpath_msgs` to `0.10.0-1`:
- previous version for package: `0.9.9-1`
```
* Changes
* Merge pull request #46 <https://github.com/clearpathrobotics/clearpath_msgs/issues/46> from clearpathrobotics/0.13/features
0.13/features
* fix endline
* Merge remote-tracking branch 'refs/remotes/origin/poi' into 0.13/features
* added zoom to inspect poi action
* create new camera msg package with InspectPOI action
* Contributors: Chris Iverach-Brereton, José Mastrangelo, Stephen Phillips, jmastrangelo-cpr
* Initial release of …
```
=> clearpath_msgs: 0.10.0-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `0.2.10-1`:
- previous version for package: `0.2.9-1`
```
* Updated Microstrain link parameter
* Updated Realsense parameters
```
=> clearpath_config: 0.2.10-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `ridgeback` to `0.3.5-1`:
```
* Reduce turbo gains
Reduce gains to be the same as non-turbo levels. This way holding either button will allow the robot to drive, but without the safety concerns about a fully-loaded payload moving at full speed.
* Add teleop turbo support
We define a turbo button, but don't actually set the gains; this means pressing B5 uses the default 0.0 multiplier, causing the robot to stop.
This MR adds 1.1x multipliers to the linear speed (maximum advertised speed is …
```
=> ridgeback: 0.3.5-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `0.2.10-1`:
- previous version for package: `0.2.9-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Topics of simulated onboard sensors
* Missing important remapping to mirror hardware topics
* Contributors: Luis Camero, Steve Macenski
```
```
* Realsense adds optical links when in simulator
* Updated topic names to match gazebo message types
* Added topic to gazebo plugins
```
=> clearpath_common: 0.2.10-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_simulator` to `0.2.6-1`:
```
* Add gz image transport for cameras
* IMU data raw remap
* Generate gazebo bridge config parameters
* Removed bridging using remappings and arguments
```
- No changes
- No changes
=> clearpath_simulator: 0.2.6-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `puma_motor_driver` to `1.0.0-1`:
```
* Deleted the CHANGELOG
* Version match to puma_motor_driver
* Renamed socketcan_interface to clearpath_socket_interface
```
```
* Removed info logging
* Restored commandSpeed
* Spacing fixes
* Updated topics to match API
* Renamed socketcan_interface to clearpath_socket_interface
* Topic in node namespace
* Renamed robot to multi_puma_node
* Fixed include
* Add launch files and configuration files
* Add new …
```
=> puma_motor_driver: 1.0.0-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `0.2.13-1`:
- previous version for package: `0.2.12-1`
- No changes
- No changes
- No changes
```
* Fixed bug in microstrain param
* Fixed remapping to allow for compressed vizualization
```
=> clearpath_robot: 0.2.13-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `0.2.11-1`:
- previous version for package: `0.2.10-1`
```
* Adds GQ7 as possible sensor
* Contributors: robbiefish
```
=> clearpath_config: 0.2.11-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `0.2.11-1`:
- previous version for package: `0.2.10-1`
- No changes
```
* Set spawner as super client
```
- No changes
- No changes
```
* Fixes styling issues
* Modifies platform param to add GQ7 IMU data to ekf_localization and adds GQ7 URDF
* Contributors: robbiefish
```
- No changes
- No changes
- No changes
```
* Modifies platform param to add GQ7 IMU data to ekf_localization and adds GQ7 URDF
* Contributors: robbiefish
```
=> clearpath_common: 0.2.11-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `0.2.15-1`:
- previous version for package: `0.2.14-1`
- No changes
- No changes
- No changes
```
* Removed unused import
* Add blackfly to composable container
* Use intraprocess comms
```
=> clearpath_robot: 0.2.15-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_mecanum_drive_controller` to `0.1.0-1`:
- upstream repository: https://github.com/clearpathrobotics/clearpath_mecanum_drive_controller.git
- release repository: https://github.com/clearpath-gbp/clearpath_mecanum_drive_controller-release.git
```
* Add dependency on hardware interface testing
* Fixed tests
* Renamed to clearpath_mecanum_drive_controller
```
=> clearpath_mecanum_drive_controller: 0.1.0-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `nmea_navsat_driver` to `2.0.1-1`:
- upstream repository: https://github.com/ros-drivers/nmea_navsat_driver.git
- release repository: https://github.com/clearpath-gbp/nmea_navsat_driver-release.git
- previous version for package: `2.0.2-1`
```
* Fix parsing of true_course field in VTG message (#165 <https://github.com/evenator/nmea_navsat_driver/issues/165>)
Co-authored-by: Stefan Gisler <mailto:stefan.gisler@hillbot.ch>
* Fix missing return in driver.add_sentence to avoid returning None.
* Update logger definition to match ROS2 logging API.
* Add Support for TCP GNSS Sensor (#152 <https://github.com/evenator/nmea_navsat_driver/issues/152>)
Add a new nmea_tcpclient_driver for …
```
=> nmea_navsat_driver: 2.0.1-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_indoornav_navigation` to `0.0.1-2`:
- upstream repository: https://github.com/clearpathrobotics/cpr-indoornav-navigation.git
- release repository: https://github.com/clearpath-gbp/cpr_indoornav_navigation-release.git
```
```
```
```
=> cpr_indoornav_navigation: 0.0.1-2 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `wireless` to `1.1.1-1`:
- previous version for package: `1.1.0-1`
- No changes
```
* Set NaN when empty BitRate/Frequency
* Add try-catch to BitRate and Frequency field
```
=> wireless: 1.1.1-1 in 'humble/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `simple_term_menu_vendor` to `1.5.7-1`:
- upstream repository: https://github.com/clearpathrobotics/simple-term-menu.git
- release repository: https://github.com/clearpath-gbp/simple_term_menu_vendor-release.git
```
* 1.5.7
* Tag fix
* 1.5.6
* Changelogs.
* Removed unused files
Added testing dependencies
```
=> simple_term_menu_vendor: 1.5.7-1 in 'jazzy/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `nmea_navsat_driver` to `2.0.3-1`:
- upstream repository: https://github.com/clearpathrobotics/nmea_navsat_driver.git
- release repository: https://github.com/clearpath-gbp/nmea_navsat_driver-release.git
```
* Merge pull request #1 <https://github.com/clearpathrobotics/nmea_navsat_driver/issues/1> from clearpathrobotics/lcamero/tf_depend
Add exec_depend for tf_transformations
* Add exec_depend for tf_transformations
```
=> nmea_navsat_driver: 2.0.3-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_msgs` to `0.3.0-2`:
- No changes
```
* Added needs_reset
```
=> clearpath_msgs: 0.3.0-2 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_simulator` to `0.3.0-1`:
```
* Removed prefix_launch_arg no longer used
* Add ridgeback
* Fixed change log order
* Added manipulators to generator and spawn
```
```
* Added manipulators to generator and spawn
```
```
* Fixed changelogs
```
=> clearpath_simulator: 0.3.0-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `0.3.1-1`:
```
* Fix battery in r100 sample
```
=> clearpath_config: 0.3.1-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `0.3.2-1`:
```
* Alphabetically order packages
* Add manipulators to setup
```
=> clearpath_config: 0.3.2-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `0.3.1-1`:
- No changes
- No changes
- No changes
```
* Line too long
```
=> clearpath_robot: 0.3.1-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `0.3.1-1`:
- No changes
- No changes
- No changes
```
* Add manipulator dependencies
```
```
* Add manipulator dependencies
* Fixed linting issues for manipulator generation
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
=> clearpath_common: 0.3.1-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `0.3.3-1`:
```
* Allow all parameters to be modified
```
=> clearpath_config: 0.3.3-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `0.3.2-1`:
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Fix outstanding merge conflict
```
- No changes
=> clearpath_common: 0.3.2-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `0.3.4-1`:
```
* Add OAKD
* Add phidgets spatial to config
```
=> clearpath_config: 0.3.4-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `0.3.3-1`:
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Add OAKD
* Added phidget spatial URDF
```
=> clearpath_common: 0.3.3-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `0.3.2-1`:
- No changes
- No changes
```
* [clearpath_robot] Added script to grab diagnostic logs for troubleshooting.
```
```
* Add OAKD camera
* Add phidget spatial config and launch files
```
=> clearpath_robot: 0.3.2-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `0.3.4-1`:
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Fixed OakD URDF.
```
=> clearpath_common: 0.3.4-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `puma_motor_driver` to `1.0.1-1`:
```
* Add 1ms wait
* Added LICENSE per package.
* Fix linting issues
```
```
* Added LICENSE per package.
```
```
* Added LICENSE per package.
```
=> puma_motor_driver: 1.0.1-1 in 'humble/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `husky_observer` to `0.0.22-1`:
- previous version for package: `0.0.21-1`
- No changes
- No changes
```
* Merge branch 'fix/video_record_speed' into 'devel'
changed topic that is used for axis cameras for video recorder. previous one...
See merge request research/husky_observer!15
* changed topic that is used for axis cameras for video recorder. previous one...
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- …
=> husky_observer: 0.0.22-1 in 'noetic/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_msgs` to `1.0.0-1`:
- previous version for package: `0.3.0-2`
- No changes
- No changes
=> clearpath_msgs: 1.0.0-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `ptz_action_server` to `2.0.3-1`:
- previous version for package: `2.0.2-2`
```
* Added new general Ptz message (#6 <https://github.com/clearpathrobotics/ptz_action_server/issues/6>)
```
=> ptz_action_server: 2.0.3-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `axis_camera` to `2.0.3-1`:
- previous version for package: `2.0.2-2`
```
* Add/cmd vel topic (#90 <https://github.com/ros-drivers/axis_camera/issues/90>)
* added cmd/velocity topic for continuous velocity control
```
- No changes
- No changes
=> axis_camera: 2.0.3-1 in 'humble/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_msgs` to `1.0.0-1`:
- No changes
- No changes
=> clearpath_msgs: 1.0.0-1 in 'jazzy/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_ros2_socketcan_interface` to `1.0.0-1`:
```
* Change CI to Humble.
* Added README.
* Disabled copyright tests.
* Fixed linting.
* Added CI
* Added issue templates.
* Added codeowners.
* Updated package.xml
* Merge pull request #2 <https://github.com/clearpathrobotics/clearpath_ros2_socketcan_interface/issues/2> from clearpathrobotics/rkreinin/callback
Constructor with callback
* Tx queue and wall timer
* Constructor with callback …
```
=> clearpath_ros2_socketcan_interface: 1.0.0-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_msgs` to `1.0.1-1`:
```
* [clearpath_motor_msgs] Updated package version.
* Initial clearpath_motor_msgs
```
```
* Added clearpath_motor_msgs dependency in clearpath_msgs
```
- No changes
=> clearpath_msgs: 1.0.1-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `1.0.0-1`:
```
* Add default vcan ROS interfaces based on platform
* Add support for Axis cameras (#90 <https://github.com/clearpathrobotics/clearpath_config/issues/90>)
* Add the initial AxisCamera class with all ROS parameters defined in axis_camera's launch files & nodes
* Add the AxisCamera class to the sensors generator
* Add the serial to the axis camera's template
* Add serial to the template keys too
* Add serial getter/setter. Use empty …
```
=> clearpath_config: 1.0.0-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `1.0.0-1`:
```
* Remove all references to clearpath_platform
* Move platform.launch.py to clearpath_common metapackage
```
```
* Fix controller names and kinematics (#109 <https://github.com/clearpathrobotics/clearpath_common/issues/109>)
```
- No changes
```
```
```
* Remove …
```
=> clearpath_common: 1.0.0-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_simulator` to `1.0.0-1`:
```
```
```
* Play sim automatically (#52 <https://github.com/clearpathrobotics/clearpath_simulator/issues/52>)
* Play sim automatically
* Accept auto_start as a launch configuration to support previous behavior although default is true
* Contributors: Hilary Luo, Tony Baltovski
```
```
```
=> clearpath_simulator: 1.0.0-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_nav2_demos` to `1.0.0-1`:
```
* Add config files for dingo, ridgeback. Waiting for confirmation that the acceleration limits & max angular velocities are correct
* Copy velocity & acceleration limits from clearpath_control
* Contributors: Tony Baltovski, Chris Iverach-Brereton
```
=> clearpath_nav2_demos: 1.0.0-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_desktop` to `1.0.0-1`:
```
```
```
```
```
```
=> clearpath_desktop: 1.0.0-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `1.0.1-1`:
- previous version for package: `1.0.0-2`
- No changes
- No changes
- No changes
```
* Added missing dependencies (#108 <https://github.com/clearpathrobotics/clearpath_robot/issues/108>)
```
- No changes
- No changes
=> clearpath_robot: 1.0.1-1 in 'humble/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_msgs` to `1.0.1-1`:
```
* [clearpath_motor_msgs] Updated package version.
* Initial clearpath_motor_msgs
```
```
* Added clearpath_motor_msgs dependency in clearpath_msgs
```
- No changes
=> clearpath_msgs: 1.0.1-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `serial` to `2.0.0-1`:
- upstream repository: https://github.com/clearpathrobotics/serial-ros2.git
```
* Revert "Merge branch 'ament_cmake'"
This reverts commit 8e0effcd36b855701d9327aecff949d7f2b20e31.
* Revert "Remove test that breaks the build"
This reverts commit 7fe3be8d5f24db9837fff7e5b2fc45dcb464eef0.
* Remove test that breaks the build
* Convert package to ament_cmake
* Fix the build and cleanup CMakeLists
* Add setupapi to ament_export_libraries
This prevents dependent libraries from failing with something like: serial.lib(list_ports_win.obj) : error …
```
=> serial: 2.0.0-1 in 'jazzy/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_ros2_socketcan_interface` to `1.0.1-1`:
```
* Add our own launch files that allow us to change namespaces
```
=> clearpath_ros2_socketcan_interface: 1.0.1-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `serial` to `2.0.1-1`:
- upstream repository: https://github.com/clearpathrobotics/serial-ros2.git
```
* Add cmake flags and use target include
```
=> serial: 2.0.1-1 in 'humble/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `serial` to `2.0.1-1`:
- upstream repository: https://github.com/clearpathrobotics/serial-ros2.git
```
* Add cmake flags and use target include
```
=> serial: 2.0.1-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `2.0.0-1`:
```
* Add HE2410 & HE2411 battery support (#110 <https://github.com/clearpathrobotics/clearpath_config/issues/110>) (#111 <https://github.com/clearpathrobotics/clearpath_config/issues/111>)
* Add support for the HE2410 and HE2411 batteries to J100 and A200
* Fixed tests.
* Add additional controllers (#105 <https://github.com/clearpathrobotics/clearpath_config/issues/105>)
* Add Xbox controller support
* Add PS5 controller support
* Add …
```
=> clearpath_config: 2.0.0-1 in 'jazzy/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `ewellix_lift` to `0.1.0-1`:
- upstream repository: https://github.com/clearpathrobotics/ewellix_lift.git
- release repository: https://github.com/clearpath-gbp/ewellix_lift-release.git
```
* Add launch parameter to modify lift description
* Add friction and initialize lift extended
* Add all meshes and description configs
* Updated URDF and MoveIt for mimic joint
* Add gazebo tag
* Add gazebo tag
* Use mimic joint
* Pass origin instead of block
* Reset package versions to 0.0.0
* remove empty dependency
* Add sample URDF
* Increase tolerance
* Fix position of mounting link
* Add 2.25cm offset to upper tower
* Initial add of Ewellix …
```
=> ewellix_lift: 0.1.0-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `1.1.0-1`:
```
* Add enable_ekf launch parameter to platform -> localization launch files. Disable the EKF node if enable_ekf is false. (#133 <https://github.com/clearpathrobotics/clearpath_common/issues/133>) (#134 <https://github.com/clearpathrobotics/clearpath_common/issues/134>)
```
```
* Add enable_ekf launch parameter to platform -> localization launch files. Disable the EKF node if enable_ekf is false. …
```
=> clearpath_common: 1.1.0-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `1.1.0-2`:
- previous version for package: `1.1.0-1`
```
* Add enable_ekf launch parameter to platform -> localization launch files. Disable the EKF node if enable_ekf is false. (#133 <https://github.com/clearpathrobotics/clearpath_common/issues/133>) (#134 <https://github.com/clearpathrobotics/clearpath_common/issues/134>)
```
```
* Add enable_ekf launch parameter to platform -> localization launch files. Disable the EKF node if enable_ekf is false. …
```
=> clearpath_common: 1.1.0-2 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `1.1.0-1`:
```
* Added Ewellix Lift (#109 <https://github.com/clearpathrobotics/clearpath_config/issues/109>)
* Initial add of lifts to config
* Added ewellix parameters
* Add HE2411 battery support (#110 <https://github.com/clearpathrobotics/clearpath_config/issues/110>)
* Add support for the HE2411 battery to J100 and A200
* Add the even-older HE2410 too
* Cherry-pick enable_ekf support from Jazzy (#108 …
```
=> clearpath_config: 1.1.0-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `1.1.0-1`:
- No changes
- No changes
```
* Add HE2411 battery support (#119 <https://github.com/clearpathrobotics/clearpath_robot/issues/119>)
* Add support for the HE2410 and HE2411 batteries
```
```
* Add dependency for ewellix_driver (#125 <https://github.com/clearpathrobotics/clearpath_robot/issues/125>)
* Add dependency for ewellix_driver
* Alphabetical dependencies
```
- No changes …
=> clearpath_robot: 1.1.0-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `1.1.1-1`:
- previous version for package: `1.1.0-2`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* [clearpath_platform_description] Fixed R100 rear cover colour. (#145 <https://github.com/clearpathrobotics/clearpath_common/issues/145>)
```
- No changes
=> clearpath_common: 1.1.1-1 in 'humble/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `2.0.1-1`:
```
* Add Zenoh support (#113 <https://github.com/clearpathrobotics/clearpath_config/issues/113>)
* Add Zenoh to the list of supported RMW implementations
* Add zenoh_router_config_uri parameter to middleware config
* Add a sanity check to make sure we aren't trying to use Zenoh on a MicroROS-using platform
* Allow Zenoh on generic platforms
```
=> clearpath_config: 2.0.1-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `2.0.0-1`:
```
* Improve joy telep support (#131 <https://github.com/clearpathrobotics/clearpath_common/issues/131>)
* Update description, add bluez dependency
* Add the quality_cutoff parameter to all of the PS4 configuration files
* Update the launch file to start the new cutoff node and additional twist_mux
* Add udev rules for various controllers
* Add dependency on the new bt cutoff package
* Add xbox controller parameters for all platforms
* Fix the …
```
=> clearpath_common: 2.0.0-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `micro_ros_agent` to `5.0.3-1`:
- upstream repository: https://github.com/clearpathrobotics/micro-ROS-Agent.git
- release repository: https://github.com/clearpath-gbp/micro-ROS-Agent-release.git
```
* Added spdlog as dep.
* Fix superbuild install permission errors
* Contributors: Błażej Sowa, Tony Baltovski
```
=> micro_ros_agent: 5.0.3-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `wireless` to `1.1.2-1`:
- No changes
```
* Define static type in template (#21 <https://github.com/clearpathrobotics/wireless/issues/21>)
```
=> wireless: 1.1.2-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `umx_driver` to `1.0.1-1`:
- upstream repository: https://github.com/ros-drivers/um7
- release repository: https://github.com/ros-drivers-gbp/um7-release.git
```
* Added boost as a build_depend.
```
=> umx_driver: 1.0.1-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `2.0.0-1`:
```
* Fix hard-coded humble packages (#117 <https://github.com/clearpathrobotics/clearpath_robot/issues/117>)
* Contributors: Chris Iverach-Brereton, Luis Camero, Tony Baltovski
```
```
* Add the package initializations that used to be in clearpath_common_generator into the robot generators (#110 <https://github.com/clearpathrobotics/clearpath_robot/issues/110>)
* A300 VCAN (#111 <https://github.com/clearpathrobotics/clearpath_robot/issues/111>)
* …
```
=> clearpath_robot: 2.0.0-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `2.0.1-1`:
- No changes
- No changes
- No changes
- No changes
- No changes
```
* [clearpath_motor_drivers/lynx_motor_driver] Fixed required version of clearpath_motor_msgs.
```
- No changes
=> clearpath_robot: 2.0.1-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_ros2_socketcan_interface` to `2.0.1-1`:
```
* Lint launch files (#4 <https://github.com/clearpathrobotics/clearpath_ros2_socketcan_interface/issues/4>)
* Prefix node names with can interface
* Add our own launch files that allow us to change namespaces
* Change CI to Humble.
* Contributors: Luis Camero, Roni Kreinin, Tony Baltovski, luis-camero
```
=> clearpath_ros2_socketcan_interface: 2.0.1-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `2.0.1-1`:
```
* Explicitly use the default qos profile for the quality & cutoff pubs. Reduce the publish rate from 10Hz to 5Hz (on A300-000006 the 10Hz rate was missing deadlines, resulting in a deadlocked controller)
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
=> clearpath_common: 2.0.1-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `2.0.2-1`:
```
* Add additional logging, replace rate.sleep() with time.sleep(); on boot as part of a systemd job rate.sleep() is never exiting (#148 <https://github.com/clearpathrobotics/clearpath_common/issues/148>)
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
=> clearpath_common: 2.0.2-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `2.0.3-1`:
- previous version for package: `2.0.2-1`
```
* Bypass bluetooth link quality check (#151 <https://github.com/clearpathrobotics/clearpath_common/issues/151>)
* Comment-out the bluetooth cutoff node, the mux, and the remap from the joy_teleop to bypass the link quality check
* Add missing newlines to joy teleop config files
* Change the link quality check to be exclusive instead of inclusive
```
- No changes
```
* Bypass bluetooth link quality …
```
=> clearpath_common: 2.0.3-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `2.0.4-1`:
- previous version for package: `2.0.3-1`
- No changes
```
* Add config and launch for inventus
```
- No changes
- No changes
```
* Add config and launch for inventus
```
```
* Multiply feedback velocity by wheel direction (#132 <https://github.com/clearpathrobotics/clearpath_robot/issues/132>)
```
- No changes
=> clearpath_robot: 2.0.4-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_desktop` to `2.0.0-1`:
```
* Apply linting fixes
```
```
* Add offboard sensors package (#17 <https://github.com/clearpathrobotics/clearpath_desktop/issues/17>)
* Add the clearpath_offboard_sensors package, add launch file for offboard velodyne processing
* Add the image format conversion launch files previously in clearpath_sensors. Update dependencies
```
```
* Add offboard sensors …
```
=> clearpath_desktop: 2.0.0-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_nav2_demos` to `2.0.0-1`:
```
* Enable stamped cmd_vel messages for Nav2
* Add Nav2 config files for A300. Not yet tested on the physical robot (#18 <https://github.com/clearpathrobotics/clearpath_nav2_demos/issues/18>)
* Remove repos file from CI; it doesn't exist in this repo
* Add source CI
* Update CI for Jazzy
* Fix import ordering, allow shadowing of builtin
```
=> clearpath_nav2_demos: 2.0.0-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_msgs` to `2.1.0-1`:
```
* Added new error flags (#66 <https://github.com/clearpathrobotics/clearpath_msgs/issues/66>)
```
- No changes
- No changes
=> clearpath_msgs: 2.1.0-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `2.1.0-1`:
```
* Jazzy Phidgets IMU Filter (#119 <https://github.com/clearpathrobotics/clearpath_config/issues/119>)
* Add filter to IMU entry
* Enable mag only for Phidgets
* Add DATA topic to Phidget
* Add the phidget to default sample (#120 <https://github.com/clearpathrobotics/clearpath_config/issues/120>)
* Change default user to robot (#121 <https://github.com/clearpathrobotics/clearpath_config/issues/121>)
* Feature/diagnostics (#117 …
```
=> clearpath_config: 2.1.0-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_ros2_socketcan_interface` to `2.1.0-1`:
```
* Wait for interface to be up before launching node (#7 <https://github.com/clearpathrobotics/clearpath_ros2_socketcan_interface/issues/7>)
* Wait for interface to be UP before starting node
* Updated CI to Jazzy. (#5 <https://github.com/clearpathrobotics/clearpath_ros2_socketcan_interface/issues/5>)
```
=> clearpath_ros2_socketcan_interface: 2.1.0-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `2.1.1-1`:
- previous version for package: `2.1.0-1`
- No changes
- No changes
```
* [clearpath_hardware_interfaces] Fixed BMS topic for fan control. (#145 <https://github.com/clearpathrobotics/clearpath_robot/issues/145>)
```
```
* VCAN fix for Lynx remote request issue (#146 <https://github.com/clearpathrobotics/clearpath_robot/issues/146>)
```
- No changes
- No changes
- No changes
=> clearpath_robot: 2.1.1-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `inventus_bms` to `3.0.0-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/research/inventus_bmu.git
- release repository: https://gitlab.clearpathrobotics.com/gbp/inventus_bmu-gbp.git
```
* Updates for releasing.
* Set supply status to Full when battery indicates it
* Added script to make bin file of script and driver reads in bin now.
* Charging status
* Check that CAN bus is up before attempting to connect
* Power supply health
* Sensor Data QoS
* Initial ROS 2 update.
```
=> inventus_bms: 3.0.0-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `inventus_bms` to `3.0.1-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/research/inventus_bmu.git
- release repository: https://gitlab.clearpathrobotics.com/gbp/inventus_bmu-gbp.git
- previous version for package: `3.0.0-1`
```
* Removed rclpy from CMakeLists.
```
=> inventus_bms: 3.0.1-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `2.1.2-1`:
- previous version for package: `2.1.1-1`
- No changes
- No changes
- No changes
```
* Turn off clearing of SHM on log out (#152 <https://github.com/clearpathrobotics/clearpath_robot/issues/152>)
Previously the SHM links were being cleared out when all user sessions ended which was causing ROS communication to fail and the robot to stop working.
```
- No changes
- No changes
- No changes
=> clearpath_robot: 2.1.2-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `wireless` to `1.1.3-1`:
- previous version for package: `1.1.2-1`
- No changes
```
* demark private variables with underscore
* Run loop using a timer callback
* Add Wi-Fi diagnostics
```
=> wireless: 1.1.3-1 in 'jazzy/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `wireless` to `1.1.3-1`:
- previous version for package: `1.1.1-1`
- No changes
```
* demark private variables with underscore
* Run loop using a timer callback
* Add Wi-Fi diagnostics
```
=> wireless: 1.1.3-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `1.1.1-1`:
- previous version for package: `1.1.0-1`
- No changes
```
* IMU Filter (#134 <https://github.com/clearpathrobotics/clearpath_robot/issues/134>)
* Add imu_filter launch file and added madgwick entry to filter
* Add imu filter to generator
* Rename imu_filter_node to imu_filter_madgwick
```
- No changes
```
* Turn off clearing of SHM on log out (#152 <https://github.com/clearpathrobotics/clearpath_robot/issues/152>) (#156 …
```
=> clearpath_robot: 1.1.1-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `1.1.1-1`:
- previous version for package: `1.1.0-1`
```
* Fixed docs link for Robot YAML. (#125 <https://github.com/clearpathrobotics/clearpath_config/issues/125>)
* Add filter to IMU entry (#116 <https://github.com/clearpathrobotics/clearpath_config/issues/116>)
* Add filter to IMU entry
* Enable mag only for Phidgets
* Add DATA topic to Phidget
* Contributors: Tony Baltovski, luis-camero
```
=> clearpath_config: 1.1.1-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `1.1.2-1`:
- previous version for package: `1.1.1-1`
- No changes
```
* Fix: Change path to imu_filter to platform config
* Change path to imu_filter to platform config
```
- No changes
- No changes
- No changes
```
* Fix: Robust puma initialization
* Contributors: Stephen Phillips, Tony Baltovski
```
=> clearpath_robot: 1.1.2-1 in 'humble/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_tests` to `0.2.2-1`:
```
* Add missing message dependencies
```
=> clearpath_tests: 0.2.2-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_msgs` to `2.2.0-1`:
- previous version for package: `2.1.0-1`
```
* Lynx Warning flags (#68 <https://github.com/clearpathrobotics/clearpath_msgs/issues/68>)
* Added warning flags
```
- No changes
```
* Added temperature indices for all platforms (#69 <https://github.com/clearpathrobotics/clearpath_msgs/issues/69>)
```
=> clearpath_msgs: 2.2.0-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `2.2.0-1`:
- previous version for package: `2.1.1-1`
```
* Feature Jazzy Ouster (#132 <https://github.com/clearpathrobotics/clearpath_config/issues/132>)
* Add OusterOS1
* Add ouster sample
* Alphabetical entries to Lidar3D models
* Add D455, D456 to supported devices (#136 <https://github.com/clearpathrobotics/clearpath_config/issues/136>)
* Add support for OAK-D Pro W PoE (#135 <https://github.com/clearpathrobotics/clearpath_config/issues/135>)
* Add OAK-D Pro W PoE to sensor types. Add IP …
```
=> clearpath_config: 2.2.0-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `2.2.0-1`:
- previous version for package: `2.1.0-1`
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Feature Jazzy Ouster (#170 <https://github.com/clearpathrobotics/clearpath_common/issues/170>)
* Add OusteOS1 description
* Custom OusterOS1 generator
* Ouster use custom description generator
* Use appropriate generator for Ouster
* Add D455, D456 support (#176 <https://github.com/clearpathrobotics/clearpath_common/issues/176>)
* Add URDFs for all supported RealSense …
```
=> clearpath_common: 2.2.0-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_simulator` to `2.2.0-1`:
- No changes
```
* Forward port: Add argument to disable generation  (#75 <https://github.com/clearpathrobotics/clearpath_simulator/issues/75>)
* Add argument to disable generation (#74 <https://github.com/clearpathrobotics/clearpath_simulator/issues/74>)
```
- No changes
=> clearpath_simulator: 2.2.0-1 in 'jazzy/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `1.2.0-1`:
- previous version for package: `1.1.1-1`
```
* Feature Franka (#133 <https://github.com/clearpathrobotics/clearpath_config/issues/133>)
* Feature Humble Ouster (#123 <https://github.com/clearpathrobotics/clearpath_config/issues/123>)
* Feature: MoveIt Parameters and Enable (#128 <https://github.com/clearpathrobotics/clearpath_config/issues/128>)
* Feature: Manipulator Samples and Poses (#127 <https://github.com/clearpathrobotics/clearpath_config/issues/127>)
* Feature: Link …
```
=> clearpath_config: 1.2.0-1 in 'humble/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_tests` to `0.2.3-1`:
```
* Invert the angle of the lateral test
* Add a mutex to prevent issues with reading & writing the current & previous orientations asynchronously; this sometimes causes false positives or false negatives during the test
* Don't fail if we get controller_manager rate errors
* Add newline between average motor currents in report
* Increase the allowed margin of error on the IMU test to 20% (from 10%)
* Add an extra confirmation that the lights …
```
=> clearpath_tests: 0.2.3-1 in 'jazzy/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `1.2.0-1`:
- previous version for package: `1.1.2-1`
- No changes
- No changes
- No changes
- No changes
```
* Feature Humble Ouster (#143 <https://github.com/clearpathrobotics/clearpath_robot/issues/143>)
* Add Ouster launch and configuration file
```
- No changes
=> clearpath_robot: 1.2.0-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_desktop` to `1.2.0-1`:
- No changes
- No changes
```
* Feature: MoveIt Kinematics (#20 <https://github.com/clearpathrobotics/clearpath_desktop/issues/20>)
* Use kinematics file to generate parameters for markers
* Fix: handle empty namespace (#19 <https://github.com/clearpathrobotics/clearpath_desktop/issues/19>)
```
=> clearpath_desktop: 1.2.0-1 in 'humble/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `2.2.2-1`:
- previous version for package: `2.2.1-1`
- No changes
```
* Fix/diag remap (#168 <https://github.com/clearpathrobotics/clearpath_robot/issues/168>)
* Remap diagnostics topic in fan control node
* Remap diagnostics topic in wireless watcher node
```
- No changes
- No changes
- No changes
```
* [clearpath_motor_drivers/lynx_motor_driver] Change action log to debug. (#171 <https://github.com/clearpathrobotics/clearpath_robot/issues/171>)
* Contributors: Tony …
```
=> clearpath_robot: 2.2.2-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `2.2.1-1`:
- previous version for package: `2.2.0-1`
```
* Added battery to A300 samples.
```
=> clearpath_config: 2.2.1-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_tests` to `0.2.4-1`:
```
* Reduce the minimum duration for a rotation. Log possible false-positives during the rotation test. Print the calculated duration error for the rotation & drive tests
* Log the version of clearpath_tests in the report
* Increase the length of expected lynx messages to 5, cast the length to an integer before comparing it
```
=> clearpath_tests: 0.2.4-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_msgs` to `2.2.1-1`:
- previous version for package: `2.2.0-1`
- No changes
- No changes
```
* Remove temperature fields from status message (#72 <https://github.com/clearpathrobotics/clearpath_msgs/issues/72>)
```
=> clearpath_msgs: 2.2.1-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_tests` to `0.2.5-1`:
```
* Simplify linear driving test, reduce mobility test logging (#1 <https://github.com/clearpathrobotics/clearpath_tests/issues/1>)
```
=> clearpath_tests: 0.2.5-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_tests` to `0.2.7-1`:
```
* Move the confirmation about the lights being in the normal state before we call start()
* Log the hardware ID and firmware version reported by the MCU status topic
* Move the TF listener implementation to its own file
* Add tests, refactor & reformat to address errors they caught
```
=> clearpath_tests: 0.2.7-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_tests` to `0.2.8-1`:
- previous version for package: `0.2.7-1`
```
* Use the last 7 bits for the CAN ID, sort the IDs in the final report
* Note that the IDs are CANopen, and could be incorrect for other devices.
```
=> clearpath_tests: 0.2.8-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_tests` to `0.2.9-1`:
- previous version for package: `0.2.8-1`
```
* Rewrite rotation test (#2 <https://github.com/clearpathrobotics/clearpath_tests/issues/2>)
* Overhaul the logic of the rotation to use an accumulator instead of relying on the latest odom data. Factor in the rate of the EKF + the odometry twist instead of just looking at positional data. On 00005 we're still overshooting slightly, but it's now within the margin of error
* Append the can interface to the node name to suppress duplicate …
```
=> clearpath_tests: 0.2.9-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `inventus_bmu` to `3.0.2-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/research/inventus_bmu.git
- release repository: https://gitlab.clearpathrobotics.com/gbp/inventus_bmu-gbp.git
- previous version for package: `3.0.1-1`
```
* feature/diagnostics
```
=> inventus_bmu: 3.0.2-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `2.2.3-1`:
- previous version for package: `2.2.2-1`
```
* [clearpath_diagnostics] Updated for changes to MCU status message.
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
=> clearpath_robot: 2.2.3-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_msgs` to `2.2.2-1`:
- previous version for package: `2.2.1-1`
- No changes
- No changes
```
* Merge pull request #74 <https://github.com/clearpathrobotics/clearpath_msgs/issues/74> from clearpathrobotics/feature/display_status
Feature/display status
```
=> clearpath_msgs: 2.2.2-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `2.2.2-1`:
- previous version for package: `2.2.1-1`
```
* Updated the parent link of the base IMU on the A300.
```
=> clearpath_config: 2.2.2-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_tests` to `2.3.0-1`:
- previous version for package: `0.2.9-1`
```
* Allow symlinks to the device handle
* Fix serial MCU tests
* Ensure the firmware is 2.3 or higher to allow fan control; otherwise just skip the fan test
* Add support for lateral driving test for omni platforms (#5 <https://github.com/clearpathrobotics/clearpath_tests/issues/5>)
* Re-enable the fan tests (#4 <https://github.com/clearpathrobotics/clearpath_tests/issues/4>)
* Remove rotation test (#3 …
```
=> clearpath_tests: 2.3.0-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `2.2.1-1`:
- previous version for package: `2.2.0-1`
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Fix: Handle empty namespace (#187 <https://github.com/clearpathrobotics/clearpath_common/issues/187>)
* Handle empty namespace
* Resolve formatting issues
```
```
* Fix: Rename ompl to _ompl and update to match Jazzy (#186 <https://github.com/clearpathrobotics/clearpath_common/issues/186>)
```
- No changes
- No …
=> clearpath_common: 2.2.1-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `2.2.4-1`:
- previous version for package: `2.2.3-1`
- No changes
```
* [clearpath_generator_robot] Added python3-apt as exec dep. (#182 <https://github.com/clearpathrobotics/clearpath_robot/issues/182>)
```
- No changes
- No changes
- No changes
- No changes
- No changes
=> clearpath_robot: 2.2.4-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_ros2_socketcan_interface` to `2.1.1-2`:
- previous version for package: `2.1.0-1`
```
* Increased timeout to 1 second (#8 <https://github.com/clearpathrobotics/clearpath_ros2_socketcan_interface/issues/8>)
```
=> clearpath_ros2_socketcan_interface: 2.1.1-2 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `2.2.2-1`:
- previous version for package: `2.2.1-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Fast Forward Fix: Isolate UR Client Library in URDF (#195 <https://github.com/clearpathrobotics/clearpath_common/issues/195>)
* Fix: Isolate Universal Robots driver and client library dependencies (#164 <https://github.com/clearpathrobotics/clearpath_common/issues/164>)
* Update fake to mock
```
- No changes
- No …
=> clearpath_common: 2.2.2-1 in 'jazzy/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_mecanum_drive_controller` to `0.1.1-1`:
- upstream repository: https://github.com/clearpathrobotics/clearpath_mecanum_drive_controller.git
- release repository: https://github.com/clearpath-gbp/clearpath_mecanum_drive_controller-release.git
```
* Fix base_frame_offset uninitialized
* Contributors: Arend-Jan van Hilten
```
=> clearpath_mecanum_drive_controller: 0.1.1-1 in 'humble/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_tests` to `2.3.1-1`:
```
* Fix a bug where the e-stop test could cause the test node to crash
* Add a 2s delay between clearing the e-stop and moving the wheels to allow CAN reconnections as needed
* Remove CAN device ID count for platforms that don't use CANopen
* Lower the time threshold for linear drive test to 0.75 (from 0.8)
* Change the default serial device for Jackal
```
=> clearpath_tests: 2.3.1-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `2.3.0-1`:
- previous version for package: `2.2.4-1`
```
* Lint: Diagnostic move log to new line (#191 <https://github.com/clearpathrobotics/clearpath_robot/issues/191>)
* Fix/estop diagnostics (#184 <https://github.com/clearpathrobotics/clearpath_robot/issues/184>)
* Feature/clear stale diagnostics (#183 <https://github.com/clearpathrobotics/clearpath_robot/issues/183>)
* Feature/diagnostic categories (#175 <https://github.com/clearpathrobotics/clearpath_robot/issues/175>)
* Feature/inventus …
```
=> clearpath_robot: 2.3.0-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_simulator` to `2.3.0-1`:
- previous version for package: `2.2.0-1`
```
* Add exception handlers to the generators for Unsupported* exceptions (#78 <https://github.com/clearpathrobotics/clearpath_simulator/issues/78>)
```
- No changes
- No changes
=> clearpath_simulator: 2.3.0-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `2.3.1-1`:
```
* Remove duplicate and incorrect current / voltage labels (#197 <https://github.com/clearpathrobotics/clearpath_robot/issues/197>)
The terms "measured voltage" or "measured current" are prepended to these labels where they are used.
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
=> clearpath_robot: 2.3.1-1 in 'jazzy/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `1.3.0-1`:
- previous version for package: `1.2.0-1`
```
* Feature: Add delay to manipulator controller (#141 <https://github.com/clearpathrobotics/clearpath_config/issues/141>)
* Feature: Manipulator URDF Parameters (#140 <https://github.com/clearpathrobotics/clearpath_config/issues/140>)
```
=> clearpath_config: 1.3.0-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_simulator` to `1.3.0-1`:
```
* Add Ouster (#68 <https://github.com/clearpathrobotics/clearpath_simulator/issues/68>)
* Feature: MoveIt Parameters and Enable (#70 <https://github.com/clearpathrobotics/clearpath_simulator/issues/70>)
```
```
* Fix: Generation disable (#76 <https://github.com/clearpathrobotics/clearpath_simulator/issues/76>)
* Add argument to disable generation (#74 …
```
=> clearpath_simulator: 1.3.0-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `1.3.2-1`:
- previous version for package: `1.3.1-1`
- No changes
- No changes
- No changes
- No changes
```
* Skip failed tests
```
- No changes
- No changes
- No changes
- No changes
- No changes
=> clearpath_common: 1.3.2-1 in 'humble/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `2.3.1-1`:
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* [clearpath_platform_description] Updated Ridgeback R100 raiser height to 0.07m from 0.055m. (#201 <https://github.com/clearpathrobotics/clearpath_common/issues/201>)
```
- No changes
=> clearpath_common: 2.3.1-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `2.3.2-1`:
- previous version for package: `2.3.1-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Fixed depend version.
```
=> clearpath_robot: 2.3.2-1 in 'jazzy/distribution.yaml' [bloom]

noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_onav_description` to `0.1.13-1`:
- previous version for package: `0.1.12-1`
```
* Merge pull request #22 <https://github.com/cpr-application/cpr_onav_description/issues/22> from cpr-application/ONAV-2740
* use matching end tag
* fix sensor type
* use updated ouster driver and description repos
* added ouster lidar link/joint to urdf
* fix arg declaration
* added microstrain gnss links
* added hesai lidar link to urdf
```
=> cpr_onav_description: 0.1.13-1 in 'noetic/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `2.3.3-1`:
- previous version for package: `2.3.2-1`
- No changes
- No changes
- No changes
```
* Use sed to fix the start/stop scripts
* Run the ros2 command as a de-escalated user
```
- No changes
- No changes
- No changes
=> clearpath_robot: 2.3.3-1 in 'jazzy/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `wireless` to `1.1.4-1`:
- previous version for package: `1.1.3-1`
- No changes
```
* Add IP address info in diagnostic (#23 <https://github.com/clearpathrobotics/wireless/issues/23>)
```
=> wireless: 1.1.4-1 in 'humble/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `wireless` to `1.1.4-1`:
- previous version for package: `1.1.3-1`
- No changes
```
* Add IP address info in diagnostic (#23 <https://github.com/clearpathrobotics/wireless/issues/23>)
```
=> wireless: 1.1.4-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `video_recorder` to `2.0.1-1`:
```
* Add missing dependencies
```
```
* Remove old ROS1 depends
```
```
* Remove old ROS1 depends
```
```
* Remove old ROS1 depends
```
=> video_recorder: 2.0.1-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `2.3.1-1`:
```
* Fixed the Husky A300 serial sample to match the real serial.
```
=> clearpath_config: 2.3.1-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `video_recorder` to `2.0.2-1`:
- No changes
- No changes
```
* Remove boost from build file; it's not actually used (#8 <https://github.com/clearpathrobotics/video_recorder/issues/8>)
```
- No changes
=> video_recorder: 2.0.2-1 in 'jazzy/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `wireless` to `1.1.5-1`:
- previous version for package: `1.1.4-1`
```
* Added Github codeowners, issue template, CI.  Also, fixed linting. (#24 <https://github.com/clearpathrobotics/wireless/issues/24>)
```
```
* Added Github codeowners, issue template, CI.  Also, fixed linting. (#24 <https://github.com/clearpathrobotics/wireless/issues/24>)
```
=> wireless: 1.1.5-1 in 'humble/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_msgs` to `2.4.0-1`:
- No changes
- No changes
```
* Pinout messages (#75 <https://github.com/clearpathrobotics/clearpath_msgs/issues/75>)
```
=> clearpath_msgs: 2.4.0-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `wireless` to `1.1.5-1`:
- previous version for package: `1.1.4-1`
```
* Added Github codeowners, issue template, CI.  Also, fixed linting. (#24 <https://github.com/clearpathrobotics/wireless/issues/24>)
```
```
* Added Github codeowners, issue template, CI.  Also, fixed linting. (#24 <https://github.com/clearpathrobotics/wireless/issues/24>)
```
=> wireless: 1.1.5-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `2.4.0-1`:
- previous version for package: `2.3.3-1`
- No changes
```
* Added a software based low voltage cut-off for the A300. (#185 <https://github.com/clearpathrobotics/clearpath_robot/issues/185>)
* Pinout control node (#198 <https://github.com/clearpathrobotics/clearpath_robot/issues/198>)
```
```
* Added a software based low voltage cut-off for the A300. (#185 <https://github.com/clearpathrobotics/clearpath_robot/issues/185>)
* Pinout control …
```
=> clearpath_robot: 2.4.0-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_nav2_demos` to `2.4.0-1`:
```
* Update nav2 configuration files for Jazzy (#21 <https://github.com/clearpathrobotics/clearpath_nav2_demos/issues/21>)
* use_sim_time should not be in the yaml in Jazzy (#19 <https://github.com/clearpathrobotics/clearpath_nav2_demos/issues/19>)
* Contributors: Chris Iverach-Brereton, Hilary Luo
```
=> clearpath_nav2_demos: 2.4.0-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_simulator` to `2.3.1-1`:
- No changes
```
* Convert generate to a boolean in if-statement (#84 <https://github.com/clearpathrobotics/clearpath_simulator/issues/84>)
```
- No changes
=> clearpath_simulator: 2.3.1-1 in 'jazzy/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_simulator` to `1.3.1-1`:
- previous version for package: `1.3.0-1`
- No changes
```
* Convert generate to a boolean in if-statement (#84 <https://github.com/clearpathrobotics/clearpath_simulator/issues/84>) (#85 <https://github.com/clearpathrobotics/clearpath_simulator/issues/85>)
```
- No changes
=> clearpath_simulator: 1.3.1-1 in 'humble/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `2.3.2-1`:
- previous version for package: `2.3.1-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Add srdf plugins to package xml (#204 <https://github.com/clearpathrobotics/clearpath_common/issues/204>)
```
- No changes
- No changes
- No changes
- No changes
=> clearpath_common: 2.3.2-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `2.4.1-1`:
- previous version for package: `2.4.0-1`
- No changes
- No changes
```
* Muted fan control logs being spammed (#205 <https://github.com/clearpathrobotics/clearpath_robot/issues/205>)
```
```
* Fix: Increase queue length (#206 <https://github.com/clearpathrobotics/clearpath_robot/issues/206>)
```
- No changes
- No changes
- No changes
- No changes
=> clearpath_robot: 2.4.1-1 in 'jazzy/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `1.3.1-1`:
- previous version for package: `1.3.0-1`
- No changes
- No changes
- No changes
- No changes
```
* Fix: Stereolabs Zed launch file (#208 <https://github.com/clearpathrobotics/clearpath_robot/issues/208>)
* Update node parameters
* Switch to composable node
```
- No changes
=> clearpath_robot: 1.3.1-1 in 'humble/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `wiferion_charger` to `2.3.2-1`:
- upstream repository: https://github.com/clearpathrobotics/wiferion_charger.git
- release repository: https://github.com/clearpath-gbp/wiferion_charger-release.git
- previous version for package: `2.3.1-1`
- No changes
```
* Add ament_cmake to package.xml
```
=> wiferion_charger: 2.3.2-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_ros2_socketcan_interface` to `2.1.3-1`:
- previous version for package: `2.1.2-1`
```
* Fix: Spin Timeout (#13 <https://github.com/clearpathrobotics/clearpath_ros2_socketcan_interface/issues/13>)
* Add timeout to spin to prevent script from waiting when node has failed
* Update log to match appropriate action
```
=> clearpath_ros2_socketcan_interface: 2.1.3-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `canopen_inventus` to `0.1.0-1`:
```
* Update maintainer, description, and license
* Update headers
* Only publish when data is available
* Remove inputs
* Remove inventus_bmu
* Remove dependency from CMakeLists
* Remove dependency on inventus_bmu
* Update dependencies
* Add license headers
* Hide ProxyDriver topics
* Do not check reserved fault bits
* Remove logging in boot
* Add conversion methods
* Switch to using indices and maps to store data
* Separate read and publish …
```
=> canopen_inventus: 0.1.0-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `canopen_inventus_bringup` to `0.1.0-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/research/canopen_inventus_bringup.git
- release repository: https://gitlab.clearpathrobotics.com/gbp/canopen_inventus_bringup-gbp.git
```
* Update maintaner, description, and license
* Prune dependencies
* Add license header to launch file
* Add license header to source files
* Add header to include
* Add license file
* Increase publish loop 100 hz, will not publish if data is not available
* Add descriptions to launch arguments
* Update dependencies
* Remove debug print
* Change default battery count to 1
* Add arguments to change battery …
```
=> canopen_inventus_bringup: 0.1.0-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `canopen_inventus` to `0.1.1-1`:
```
* Fixed missing dependency.
```
```
* Fixed missing dependency.
```
=> canopen_inventus: 0.1.1-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `ros2_canopen` to `0.3.1-1`:
- upstream repository: https://github.com/clearpathrobotics/ros2_canopen.git
- release repository: https://github.com/clearpathrobotics/ros2_canopen-release.git
```
* update documentation
* Contributors: ipa-vsp
```
```
* Run pre-commit process
* Whitespace fixes.
* Don't overwrite value, print on read
* Attempt to make homing timeout a parameter in seconds
This should be changed later to support a more robust duration instead
of int seconds
* Add services to disable/enable motor so that brake is usable.
* Add services to disable/enable motor so that brake is usable.
* Contributors: Gerry Salinas, gerry, …
```
=> ros2_canopen: 0.3.1-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `canopen_inventus` to `0.1.2-1`:
```
* Updated package.xml to be BSD-3-Clause licence.
```
```
* Updated package.xml to be BSD-3-Clause licence.
```
=> canopen_inventus: 0.1.2-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `canopen_inventus` to `0.1.3-1`:
```
* Debug logging
```
- No changes
=> canopen_inventus: 0.1.3-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `2.5.0-1`:
- previous version for package: `2.4.1-1`
```
* Feature: ros2_canopen Inventus driver switch  (#216 <https://github.com/clearpathrobotics/clearpath_robot/issues/216>)
* Add canopen_inventus launch to generator
* Add canopen_inventus_bringup dependency
* Add canopen_inventus_bringup to CI rosdep key ignore
* Remove inventus_bmu config and launch
* Remove unused import
* Add foxglove bridge launch to platform service launch (#217 …
```
=> clearpath_robot: 2.5.0-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_nav2_demos` to `2.5.0-1`:
- previous version for package: `2.4.0-1`
```
* Fix typos in issue templates (#27 <https://github.com/clearpathrobotics/clearpath_nav2_demos/issues/27>)
* Add parameter files for Dingo (all variants), Ridgeback (#25 <https://github.com/clearpathrobotics/clearpath_nav2_demos/issues/25>)
* Add parameter files for Dingo (all variants), Ridgeback
* Add trailing newlines to config files, add missing remap to launch file
* Fix the slam launch file to use the new lifecycle node …
```
=> clearpath_nav2_demos: 2.5.0-1 in 'jazzy/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `valence_bms` to `1.1.0-1`:
- release repository: https://gitlab.clearpathrobotics.com/gbp/valence_bms-gbp.git
- previous version for package: `1.0.2-1`
```
* Fix indentation
* Remove testing log
* Do not use bms_functionality to set supply status
* Add leading backspace
* Retrieve system status variables
* Remap battery state
* Fix socketcan receiver launch
* Update launch file
* Get battery status and health
* Also move current and voltage
* Retrieve data before it is wiped
* Initial add of BatteryState message
```
- No changes
=> valence_bms: 1.1.0-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `1.3.2-1`:
- previous version for package: `1.3.1-1`
- No changes
```
* Fix/Feature: Valence Battery Update/Fix (#227 <https://github.com/clearpathrobotics/clearpath_robot/issues/227>)
* Only add battery estimator when no battery driver
* Update valence arguments
* Fix valence launch filename
* Remove duplicate definition
* Add robot namespace argument
```
```
* Populate A200 MCU status messages (#223 <https://github.com/clearpathrobotics/clearpath_robot/issues/223>) …
```
=> clearpath_robot: 1.3.2-1 in 'humble/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_ros2_socketcan_interface` to `2.1.4-2`:
- previous version for package: `2.1.4-1`
```
* Fixed using a global namespace.
* Match package name
* Fix typos in issue templates
* Contributors: Hilary, Tony Baltovski
```
=> clearpath_ros2_socketcan_interface: 2.1.4-2 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `2.5.1-1`:
- previous version for package: `2.5.0-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Fix permissions on the generate_zenoh_router executable (#221 <https://github.com/clearpathrobotics/clearpath_common/issues/221>)
```
- No changes
- No changes
- No changes
- No changes
- No changes
=> clearpath_common: 2.5.1-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `canopen_inventus_bringup` to `0.1.2-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/research/canopen_inventus_bringup.git
- release repository: https://gitlab.clearpathrobotics.com/gbp/canopen_inventus_bringup-gbp.git
```
* Update timeout parameters
```
=> canopen_inventus_bringup: 0.1.2-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `canopen_inventus` to `0.1.4-1`:
- previous version for package: `0.1.3-2`
```
* Handle exceptions of async_sdo_read_typed
```
- No changes
=> canopen_inventus: 0.1.4-1 in 'jazzy/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `1.3.3-1`:
- previous version for package: `1.3.2-1`
- No changes
```
* Add missing linear.y teleop parameters, adjust logitech gains to match equivalents from ps4 configuration (#220 <https://github.com/clearpathrobotics/clearpath_common/issues/220>)
```
- No changes
- No changes
```
* Feature: Manipulator Extra ROS Parameters (#229 <https://github.com/clearpathrobotics/clearpath_common/issues/229>)
* Pass manipulator ros parameters to generated …
```
=> clearpath_common: 1.3.3-1 in 'humble/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `1.3.3-1`:
- previous version for package: `1.3.2-1`
- No changes
- No changes
- No changes
```
* [clearpath_robot] Updated grab-diagnostics to latest. (#232 <https://github.com/clearpathrobotics/clearpath_robot/issues/232>)
```
```
* [clearpath_sensors] Fixed missing dependency lms1xx. (#234 <https://github.com/clearpathrobotics/clearpath_robot/issues/234>)
```
- No changes
=> clearpath_robot: 1.3.3-1 in 'humble/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_msgs` to `2.6.0-1`:
- previous version for package: `2.4.0-1`
```
* Added travel field to lynx feedback (#79 <https://github.com/clearpathrobotics/clearpath_msgs/issues/79>)
```
- No changes
```
* [clearpath_platform_msgs] Update Power.msg CC01 enums. (#78 <https://github.com/clearpathrobotics/clearpath_msgs/issues/78>)
```
=> clearpath_msgs: 2.6.0-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `2.6.0-1`:
- previous version for package: `2.5.1-1`
```
* Enable dependency on sevcon and valence bms
```
```
* Lynx 1.0.0 (#235 <https://github.com/clearpathrobotics/clearpath_robot/issues/235>)
* Multiple boot request attempts
* Added travel field to feedback
Use travel for odometry
* Apply direction to travel
* Added odometry reset to lynx_motor_driver
* Record last travel data
* Last travel in header
* Renamed service to reset_travel
* Limit wheel velocity based …
```
=> clearpath_robot: 2.6.0-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `2.6.1-1`:
- previous version for package: `2.6.0-1`
- No changes
- No changes
- No changes
- No changes
- No changes
```
* [clearpath_motor_drivers] Added missing deps of lynx_motor_driver.
```
- No changes
=> clearpath_robot: 2.6.1-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `2.6.1-1`:
- previous version for package: `2.6.0-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Forward Fix: Universal Robots Rate (#233 <https://github.com/clearpathrobotics/clearpath_common/issues/233>)
* Fix/Feature: UR Arm Controller Update Rate (#225 <https://github.com/clearpathrobotics/clearpath_common/issues/225>)
* Change controller update rate for universal robots to 500
* Use UniversalRobots update_rate parameters if available
* Remove Franka …
```
=> clearpath_common: 2.6.1-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `2.6.2-1`:
- previous version for package: `2.6.1-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Only add sensors to the description if their urdf_enabled flag is true (#235 <https://github.com/clearpathrobotics/clearpath_common/issues/235>)
```
- No changes
- No changes
- No changes
- No changes
- No changes
=> clearpath_common: 2.6.2-1 in 'jazzy/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_simulator` to `1.3.2-1`:
- previous version for package: `1.3.1-1`
- No changes
```
* Fixed generate flag for robot_spawn (#89 <https://github.com/clearpathrobotics/clearpath_simulator/issues/89>)
* Update simulation.launch.py to have generate setting
* properlly define the generate flag usage
* added missing import
* Contributors: Marius Juston
```
- No changes
=> clearpath_simulator: 1.3.2-1 in 'humble/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `2.6.3-1`:
- previous version for package: `2.6.2-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Fix: Ewellix Gazebo Migration (#236 <https://github.com/clearpathrobotics/clearpath_common/issues/236>)
```
- No changes
```
* Fix: Disable Platform Controllers in Manipulator Controllers (#239 <https://github.com/clearpathrobotics/clearpath_common/issues/239>)
Add flag to disable platform controllers for …
```
=> clearpath_common: 2.6.3-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `socketcan_adapter` to `0.2.0-1`:
- upstream repository: https://github.com/clearpathrobotics/socketcan_adapter.git
- release repository: https://github.com/clearpath-gbp/socketcan_adapter-release.git
```
* Merge branch '1-port-socketcan-adapter-to-publishable-repository' into 'main'
Resolve "Port Socketcan Adapter to Publishable Repository"
Closes #1 <https://github.com/clearpathrobotics/socketcan_adapter/issues/1>
See merge request polymathrobotics/socketcan_adapter!1
* Resolve "Port Socketcan Adapter to Publishable Repository"
* Contributors: Amazing Betty-Anne, Zeerek Ahmad
```
=> socketcan_adapter: 0.2.0-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `socketcan_adapter` to `0.2.1-1`:
- upstream repository: https://github.com/clearpathrobotics/socketcan_adapter.git
- release repository: https://github.com/clearpath-gbp/socketcan_adapter-release.git
```
* Added catch2 as test dependency.
```
=> socketcan_adapter: 0.2.1-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `socketcan_adapter` to `0.2.2-1`:
- upstream repository: https://github.com/clearpathrobotics/socketcan_adapter.git
- release repository: https://github.com/clearpath-gbp/socketcan_adapter-release.git
```
* Disabled tests for now.
```
=> socketcan_adapter: 0.2.2-1 in 'jazzy/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_ros2_socketcan_interface` to `1.0.3-1`:
- previous version for package: `1.0.2-1`
```
* Backports (#16 <https://github.com/clearpathrobotics/clearpath_ros2_socketcan_interface/issues/16>)
* Prefix node names with can interface
* Wait for interface to be up before launching node (#7 <https://github.com/clearpathrobotics/clearpath_ros2_socketcan_interface/issues/7>)
* Wait for interface to be UP before starting node
* Fix: Multiple IncludeLaunchDescription (#9 …
```
=> clearpath_ros2_socketcan_interface: 1.0.3-1 in 'humble/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `2.6.4-1`:
- previous version for package: `2.6.3-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Fix: Update diagnostics rate for Inventus  (#243 <https://github.com/clearpathrobotics/clearpath_common/issues/243>)
```
- No changes
- No changes
- No changes
- No changes
- No changes
=> clearpath_common: 2.6.4-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `ewellix_lift_common` to `0.2.0-1`:
- upstream repository: https://github.com/clearpathrobotics/ewellix_lift_common.git
- release repository: https://github.com/clearpath-gbp/ewellix_lift_common-release.git
```
* Add argument to disable mount and base plates
* Update license entry in package.xml
* Merge branch 'feature/ur620' into jazzy
* Add mount plate mesh
* Use  as parameter
* Migrate gazebo away from ignition
* Add UR620 meshes and config
```
- No changes
```
* Bump version
* Update documentation with Gazebo instructions
* Initial update  to ewellix_lift_common docs
* Add metapackage for common packages
* …
```
=> ewellix_lift_common: 0.2.0-1 in 'jazzy/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `ewellix_lift` to `0.1.1-1`:
- upstream repository: https://github.com/clearpathrobotics/ewellix_lift.git
- release repository: https://github.com/clearpath-gbp/ewellix_lift-release.git
```
* Update license in package.xml
* Merge pull request #7 <https://github.com/clearpathrobotics/ewellix_lift/issues/7> from Ayush1285/feat/last-position
Update the initial state of the lift.
* Merge pull request #4 <https://github.com/clearpathrobotics/ewellix_lift/issues/4> from Ayush1285/humble
Encoder limits as configurable parameters
* Fetch prev position
* Added encoder limit struct
* Added upper and lower limits as member variables
* Added …
```
=> ewellix_lift: 0.1.1-1 in 'humble/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_msgs` to `2.7.0-1`:
- previous version for package: `2.6.0-1`
```
* Drivetrains (#82 <https://github.com/clearpathrobotics/clearpath_msgs/issues/82>)
```
- No changes
- No changes
=> clearpath_msgs: 2.7.0-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `2.7.0-1`:
- previous version for package: `2.6.3-1`
```
* Fix: OAK-D Parameters (#260 <https://github.com/clearpathrobotics/clearpath_robot/issues/260>)
```
```
* Drivetrains (#250 <https://github.com/clearpathrobotics/clearpath_robot/issues/250>)
* Allow for only 2 motors in fan control node
* Fixed logic
* Added 2 joint support for lynx hardware
* Switch to using motor protection message
```
```
* Add ewellix_driver to pacakge.xml (#264 …
```
=> clearpath_robot: 2.7.0-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_desktop` to `2.7.0-1`:
- No changes
- No changes
```
* Update republish arguments as parameters for Jazzy (#23 <https://github.com/clearpathrobotics/clearpath_desktop/issues/23>)
```
- No changes
=> clearpath_desktop: 2.7.0-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_simulator` to `2.7.0-1`:
- previous version for package: `2.3.1-1`
- No changes
```
* Add explicit gravity & realtime update rate to warehouse world (#90 <https://github.com/clearpathrobotics/clearpath_simulator/issues/90>)
All other worlds include these parameters, so to keep things consistent add them to the Warehouse too.
```
- No changes
=> clearpath_simulator: 2.7.0-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_nav2_demos` to `2.7.1-1`:
- previous version for package: `2.7.0-1`
```
* Fix SLAM parameter rewrites for Jazzy (#31 <https://github.com/clearpathrobotics/clearpath_nav2_demos/issues/31>)
* Set the scan_topic parameter to the fully qualified topic, set the map_name parameter
* Add a note about the scan_topic and map_name parameters getting rewritten by the launch file
```
=> clearpath_nav2_demos: 2.7.1-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `2.7.3-1`:
- previous version for package: `2.7.2-1`
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Include hidden with foxglove bridge for onav (#261 <https://github.com/clearpathrobotics/clearpath_common/issues/261>)
```
```
* Skip xacro load for zed camera since wrapper must be manually installed (#263 <https://github.com/clearpathrobotics/clearpath_common/issues/263>)
* Forward Port Feature: Manipulator Extra ROS Parameters (#229 …
```
=> clearpath_common: 2.7.3-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `2.7.1-1`:
- previous version for package: `2.7.0-1`
```
* Feature: Franka in Jazzy (#266 <https://github.com/clearpathrobotics/clearpath_robot/issues/266>)
* Feature: Franka Hand (#252 <https://github.com/clearpathrobotics/clearpath_robot/issues/252>)
* Add frank gripper launch
* Add manipulators to namespace
* Add remapping of joint states
* Fix joint names
* Define arm_id in joint names to franka_gripper_node
* Rename franka_gripper node
```
- No changes
- No …
=> clearpath_robot: 2.7.1-1 in 'jazzy/distribution.yaml' [bloom]

humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `1.3.3-1`:
- previous version for package: `1.3.2-1`
```
* Backport Fix: Ouster URDF Parameters (#195 <https://github.com/clearpathrobotics/clearpath_config/issues/195>)
* Base and Cap parameter to Ouster
* Add 'cap_type' and 'base_type' in Ouster sample
* Fix: Lift URDF Parameters (#194 <https://github.com/clearpathrobotics/clearpath_config/issues/194>)
```
=> clearpath_config: 1.3.3-1 in 'humble/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `2.7.3-1`:
- previous version for package: `2.7.2-1`
```
* Feature: Kinova Jazzy Support (#193 <https://github.com/clearpathrobotics/clearpath_config/issues/193>)
* Remove unsupported exception on Kinova
* Lint and remove unused imports
* Add arm reference from within arm's gripper
```
=> clearpath_config: 2.7.3-1 in 'jazzy/distribution.yaml' [bloom]

jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `2.7.4-1`:
- previous version for package: `2.7.3-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Feature: Kinova Jazzy Support (#265 <https://github.com/clearpathrobotics/clearpath_common/issues/265>)
* Remove prefix from Kinova gripper joint
* Switch mesh paths from file to package
* Add custom description generator for Robotiq gripper on Kinova
* Replace 'PI' property with 'math.pi'
* Add ComposableNodeContainer to launch generator
* Remove output from …
```
=> clearpath_common: 2.7.4-1 in 'jazzy/distribution.yaml' [bloom]
