indigo/distribution.yaml

Increasing version of package(s) in repository `jackal_robot` to `0.2.0-0`:
```
* read mag msg in radian.
* added magnetometer calibration computation scripts.
* Contributors: Shokoofeh Pourmehr
```
```
* Add install script.
```
```
* Add jackal_bringup to robot metapackage.
```

jackal_robot: 0.2.0-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `jackal_robot` to `0.2.1-0`:
```
* Resolve catkin_lint.
```
```
* Resolve catkin_lint.
```
- No changes

jackal_robot: 0.2.1-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `jackal_robot` to `0.2.2-0`:
- previous version for package: `0.2.1-0`
```
* Simplify mag computation.
* Don't output stderr from env hook.
* A new approach to fallback configuration.
* Add more missing dependencies to jackal_base.
* Add default compass configuration and install it.
* Remove sixpair, use system one instead.
```
```
* Add default compass configuration and install it.
```
- No changes

jackal_robot: 0.2.2-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.4.2-0`:
- previous version for package: `0.4.0-0`
```
* Shorten timeout for the controller spawner's shutdown.
```
- No changes
- No changes
- No changes

jackal: 0.4.2-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `jackal_robot` to `0.3.0-0`:
- previous version for package: `0.2.2-0`
- No changes
```
* Support changing topic name for accessory laser.
* Support turning on the LMS1xx accessory via optenv.
```
- No changes

jackal_robot: 0.3.0-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.5.0-0`:
- previous version for package: `0.4.2-0`
```
* Support disabling the joystick for simulation when only the interactive markers are desired for teleop.
```
```
* Add hook for custom URDF insertion to jackal.urdf.xacro.
* Add xacro wrapper script to provide some pre-cooked "configs", especially for simulated Jackal.
* Switch to parameterizing URDF with optenv.
* Add laser bracket STL.
```
- No changes
- No changes

jackal: 0.5.0-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `robot_upstart` to `0.1.1-0`:
- upstream repository: https://github.com/clearpathrobotics/robot_upstart.git
- release repository: https://github.com/clearpath-gbp/robot_upstart-release.git
```
* Python Rewrite
* The startup event is too early for ROS to start, use local-filesystems instead.
* Remove bash versions of the install and uninstall utilities.
* Add support for supplying the --wait flag to roslaunch.
* Add Sphinx documentation.
To get the argparse docs required moving most of the install
script to a module, which probably should have been done anyway.
* Add a new-implementation install script, refactor Provider to be a class …
```

robot_upstart: 0.1.1-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `lms1xx` to `0.1.1-0`:
- upstream repository: https://github.com/clearpathrobotics/LMS1xx.git
- release repository: https://github.com/clearpath-gbp/LMS1xx-release.git
```
* Changed the pkg and name so that the launch file is able to find the package.
* Fix assignment in if() to comparison.
* Contributors: Jeff Schmidt, Mike Purvis
```

lms1xx: 0.1.1-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `lms1xx` to `0.1.2-0`:
- upstream repository: https://github.com/clearpathrobotics/LMS1xx.git
- release repository: https://github.com/clearpath-gbp/LMS1xx-release.git
```
* More robust startup for LMS1xs, retries instead of just dying.
* Switch to console_bridge logouts, separate lib.
* Remove buffer flush at conclusion.
* Use LMS1xx reported configuration instead of capabilities for angle_min, max, etc...
* Use output range query for min & max angles, num_values, and time_increment.
Previously, the code would query the LMS1xx for its capabilities, which
might exceed its current configuration (in terms of angle range).  Now, we
query …
```

lms1xx: 0.1.2-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.5.1-0`:
- previous version for package: `0.5.0-0`
- No changes
```
* Modified the accessories.urdf.xacro to include both the GPS and mount plate, including standoffs.
* Eliminate rosrun from the xacro wrapper.
* Contributors: BryceVoort, Mike Purvis
```
- No changes
- No changes

jackal: 0.5.1-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `jackal_robot` to `0.3.1-0`:
- No changes
```
* Add multicast lib, add navsat rtk relay.
* Add launch functionality of the Novatel GPS to accessories.launch
* Contributors: BryceVoort, Mike Purvis
```
- No changes

jackal_robot: 0.3.1-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `jackal_robot` to `0.3.1-1`:
- No changes
```
* Add multicast lib, add navsat rtk relay.
* Add launch functionality of the Novatel GPS to accessories.launch
* Contributors: BryceVoort, Mike Purvis
```
- No changes

jackal_robot: 0.3.1-1 in 'indigo/distribution.yaml' [bloom]

---

hydro/distribution.yaml

Increasing version of package(s) in repository `kingfisher_firmware` to `0.1.1-0`:
- upstream repository: https://bitbucket.org/clearpathrobotics/kingfisher_firmware
- release repository: git@bitbucket.org:clearpathrobotics/kingfisher_firmware-gbp.git
- distro file: `hydro/distribution.yaml`
```
* Add rosserial_arduino as a run depend, per catkin warning.
```
- No changes

kingfisher_firmware: 0.1.1-0 in 'hydro/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `jackal_firmware` to `0.3.0-0`:
- previous version for package: `0.2.1-0`
```
* For released builds, use the package.xml version as the hardware ID.
* Add wifi LED support, zeroing of non-implemented temperature values.
* Dramatically reduce startup delay, now that controller issue is resolved.
* New approach to capturing NMEA sentences, GPS now enabled.
* Extend power-off deadline to 10 seconds.
When equipped with a lot of USB payloads, there's a longer
gap on startup between the USB ports coming alive, which
caused …
```

jackal_firmware: 0.3.0-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `jackal_robot` to `0.3.2-0`:
```
* Add simple connection detect to enable Jackal's wifi status LED.
* Get elapsed time from monotonic time source
* Contributors: Mike Purvis, Paul Bovbel
```
```
* Retry on startup when network device does not exist.
* Set args types to int.
```
- No changes

jackal_robot: 0.3.2-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `jackal_robot` to `0.3.3-0`:
- previous version for package: `0.3.2-0`
```
* Remove duration cast, was using incorrect method to get time out of clock
* Return from function early when getifaddrs fails to avoid double free.
* Contributors: Mike Purvis, Paul Bovbel
```
- No changes
- No changes

jackal_robot: 0.3.3-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `jackal_firmware` to `0.3.1-0`:
```
* Populate drivers fields.
```

jackal_firmware: 0.3.1-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `jackal_firmware` to `0.3.2-0`:
```
* Update to stm32plus 4.0.0.
```

jackal_firmware: 0.3.2-0 in 'indigo/distribution.yaml' [bloom]

---

hydro/distribution.yaml

Increasing version of package(s) in repository `kingfisher_robot` to `0.0.5-0`:
- upstream repository: https://github.com/kf/kingfisher_robot
- release repository: git@bitbucket.org:clearpathrobotics/kingfisher_robot-gbp.git
- distro file: `hydro/distribution.yaml`
- bloom version: `0.5.19`
- previous version for package: `0.0.4-0`
```
* Add echosounder nmea topic
* Changed sensor to sonar to be more descriptive.
* set ublox back as default. Minor syntax changes.
* Setup sonar, gps, rtcm
* changes to nmea gps and serial bringup and added rtcm netserial stream
* Contributors: Andrew Blakey, Graeme Yeates, Mike Purvis, andrew_blakey
```
```
* Instantiate Helm and Course classes as well as Drive.
* Fix topic name for Hydro, will change back on Indigo.
* Remove screen output tags from launch …
```

kingfisher_robot: 0.0.5-0 in 'hydro/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `jackal_firmware` to `0.3.3-0`:
- previous version for package: `0.3.2-0`
```
* Basic accelerometer bias removal.
* Added motor button and enabled interrupt for power button.
* Fixed minor bug in the gyroscope bias logging.
```

jackal_firmware: 0.3.3-0 in 'indigo/distribution.yaml' [bloom]

---

index.yaml

Use rosdistro cache to speed up buildbot reconfig

---

indigo/distribution.yaml

Increasing version of package(s) in repository `jackal_firmware` to `0.3.4-0`:
- previous version for package: `0.3.3-0`
```
* Fixed temperature sensing.
* Fixed external e-stop support.
* Migrated logging and SM logic to common components lib.
```

jackal_firmware: 0.3.4-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `firmware_components` to `0.1.1-0`:
- upstream repository: git@bitbucket.org:clearpathrobotics/firmware_components
- release repository: git@bitbucket.org:clearpathrobotics/firmware_components-gbp.git
```
* Added IMU bias removal.
* Capitalized constants.
* Made constants public.
* Added IMU bias removal.
* Added LUT for temperature sensors.
* Add roslint dependency.
```

firmware_components: 0.1.1-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `jackal_firmware` to `0.3.5-0`:
- previous version for package: `0.3.4-0`
```
* Small firmware_components fix for test build.
```

jackal_firmware: 0.3.5-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `roboteq` to `0.2.0-0`:
- upstream repository: https://github.com/g/roboteq.git
- release repository: https://github.com/clearpath-gbp/roboteq-release.git
- No changes
```
* Explicit stop commands at 10Hz when uncommanded.
* Add option to command position control, specifying separate sets of constants in MBS.
* Fixed channel.cpp line 85 to properly pass variable relevent to channel
* Contributors: Mike Purvis, Thomas Watters
```
```
* Add mode for stop, clear control constants; this is an MD5 breakage for Indigo.
```

roboteq: 0.2.0-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `grizzly_robot` to `0.2.1-0`:
```
* Launchfiles from RS232 comms option.
* Modify MotorFanout to take advantage of active brake.
```
- No changes
- No changes

grizzly_robot: 0.2.1-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `grizzly` to `0.3.2-0`:
- upstream repository: https://github.com/g/grizzly.git
- release repository: https://github.com/clearpath-gbp/grizzly-release.git
- No changes
```
* Added a precharge check before transitioning into MOVING state. Without this,
precharges that take longer than 2.0 seconds will cause stuttering issues if
there is already a cmd_vel being sent.
* Added estop check in watchdog callback for the Moving state. Without this, the
state machine will get stuck in the Moving state if the vehicle is estopped while
there is still a stream of motion commands being sent.
* Contributors: Mike Purvis, Peiyi Chen
```
```
* Add …
```

grizzly: 0.3.2-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback` to `0.1.0-0`:
```
* Initial ridgeback release.
```
```
* Initial ridgeback description release.
```
```
* Initial ridgeback messages release.
```
```
* Initial ridgeback release.
```

ridgeback: 0.1.0-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `puma_motor_driver` to `0.1.0-0`:
```
* First release of CAN/serial ROS driver for Puma.
```
```
* Add standalone package for a puma messages.
```

puma_motor_driver: 0.1.0-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `firmware_components` to `0.2.0-0`:
- upstream repository: git@bitbucket.org:clearpathrobotics/firmware_components
- release repository: git@bitbucket.org:clearpathrobotics/firmware_components-gbp.git
```
* Improve logic which shortens logger file output.
* Retry MPU read on failure.
* PCA9685 LED controller driver.
* Split MPU hardware interface into a timed and interrupt.
* Added support for MPU-9250, renamed to MPU9X50.
```

firmware_components: 0.2.0-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback_firmware` to `0.1.0-0`:
```
* Initial release of Ridgeback firmware.
```

ridgeback_firmware: 0.1.0-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `puma_motor_driver` to `0.1.1-0`:
```
* Package format 2, dependency fix.
```
```
* Package format 2.
```

puma_motor_driver: 0.1.1-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback_robot` to `0.1.1-0`:
```
* Added lighting.
```
- No changes
- No changes

ridgeback_robot: 0.1.1-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback_robot` to `0.1.2-0`:
```
* Fixed dependency.
```
- No changes
- No changes

ridgeback_robot: 0.1.2-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback_robot` to `0.1.3-0`:
```
* Install the ridgeback_node target.
```
- No changes
- No changes

ridgeback_robot: 0.1.3-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback_robot` to `0.1.4-0`:
- No changes
```
* Added manufacturer to laser environment variables.
* Installed robot_upstart install script with connman and can-udp-bridge.conf.
```
- No changes

ridgeback_robot: 0.1.4-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback` to `0.1.1-0`:
- No changes
```
* Added manufacturer to laser environment variables.
```
- No changes
- No changes

ridgeback: 0.1.1-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `firmware_components` to `0.3.0-0`:
- upstream repository: git@bitbucket.org:clearpathrobotics/firmware_components
- release repository: git@bitbucket.org:clearpathrobotics/firmware_components-gbp.git
```
* Add canopen libs, plus find module.
* Add FreeRTOS 7.6.0, plus C++ wrapper and find module.
* Add firmware version function.
```

firmware_components: 0.3.0-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback` to `0.1.2-0`:
```
* Added wheel separation override.
```
- No changes
- No changes
- No changes

ridgeback: 0.1.2-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback_firmware` to `0.1.1-0`:
```
* Improvements to power control.
```

ridgeback_firmware: 0.1.1-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback_desktop` to `0.1.0-0`:
- upstream repository: https://github.com/ridgeback/ridgeback_desktop
- release repository: https://github.com/clearpath-gbp/ridgeback_desktop-release.git
```
* Initial Ridgeback commit.
```
```
* Initial Ridgeback commit.
```

ridgeback_desktop: 0.1.0-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback_firmware` to `0.1.1-1`:
```
* Improvements to power control.
```

ridgeback_firmware: 0.1.1-1 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback_firmware` to `0.1.1-2`:
```
* Improvements to power control.
```

ridgeback_firmware: 0.1.1-2 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `jackal_firmware` to `0.3.6-0`:
- previous version for package: `0.3.5-0`
```
* Added I2C Recovery Behaviour.
```

jackal_firmware: 0.3.6-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `jackal_robot` to `0.3.4-0`:
- previous version for package: `0.3.3-0`
- No changes
```
* Added bumblebee2 to accessories.
```
- No changes

jackal_robot: 0.3.4-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.5.2-0`:
- previous version for package: `0.5.1-0`
```
* Removed reference to FootprintLayer.
* Increased inflation radius to account for uneven wall in Jackal_world.
* Added pointgrey camera and accessories.
* Improve robot_localiztion params
* Added Sick LMS1XX URDF.
* Fixed example calibration output.
* Added tutorials.
* Contributors: Mike Purvis, Martin Cote, Tony Baltovski, James Servos
```
- No changes

jackal: 0.5.2-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `jackal_robot` to `0.3.5-0`:
- previous version for package: `0.3.4-0`
- No changes
```
* Fixed scan topic name and optenv for lms1xx bringup.
```
- No changes

jackal_robot: 0.3.5-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback_robot` to `0.1.5-0`:
- previous version for package: `0.1.4-0`
```
* Fixed state order for lighting.
* Separated passive joint into header.
```
```
* Removed br0 interface from upstart job to default to hostname.
```
- No changes

ridgeback_robot: 0.1.5-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback` to `0.1.3-0`:
```
* Updated URDF for physical changes.
* Updated control limits.
* Removed yaw estimate from robot_localization.
```
```
* Updated URDF for physical changes.
* Simulation using gazebo_ros_force_based_move.
```
- No changes
```
* Removed CATKIN_IGNORE from ridgeback_navigation.
* ridgeback_navigation: remove deprecated footprint layer
* Simulation using gazebo_ros_force_based_move.
* …
```

ridgeback: 0.1.3-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `multimaster_fkie` to `0.5.0-0`:
- upstream repository: http://github.com/fkie/multimaster_fkie.git
- release repository: https://github.com/fkie-release/multimaster_fkie-release.git
- previous version for package: `0.4.4-0`
```
* default_cfg_fkie: added 'load_params_at_start' parameter.
On start of default_cfg_fkie all parameters are loaded into ROS
parameter server. If this parameter is set to False the parameter are
loaded on first run of an included node.
* mulitmaster_fkie: fixed the missing leading SEP by groups
* Contributors: Alexander Tiderko
```
```
* master_discovery: fixed avg. network load calculation, added checks for some parameters
* multimaster_fkie: Set …
```

Increasing version of package(s) in repository multimaster_fkie to 0.5.0-0

---

indigo/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.5.2-1`:
- previous version for package: `0.5.2-0`
```
* Removed reference to FootprintLayer.
* Increased inflation radius to account for uneven wall in Jackal_world.
* Added pointgrey camera and accessories.
* Improve robot_localiztion params
* Added Sick LMS1XX URDF.
* Fixed example calibration output.
* Added tutorials.
* Contributors: Mike Purvis, Martin Cote, Tony Baltovski, James Servos
```
- No changes

jackal: 0.5.2-1 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback` to `0.1.4-0`:
- No changes
```
* Added lms1xx as run dependency.
```
- No changes
- No changes

ridgeback: 0.1.4-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback_robot` to `0.1.6-0`:
- previous version for package: `0.1.5-0`
```
* Combined hostname and version for hardware ID.
* Fixed initialization of constant doubles.
* Added hardware ID based hostname.
```
```
* Specified max/min angles for Hokuyo UST-10LX.
* Added support for Hokuyo URG-10LX.
```
- No changes

ridgeback_robot: 0.1.6-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback` to `0.1.5-0`:
- previous version for package: `0.1.4-0`
- No changes
```
* Added support for Hokuyo URG-10LX.
```
- No changes
- No changes

ridgeback: 0.1.5-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback` to `0.1.6-0`:
- previous version for package: `0.1.5-0`
```
* Added support for PS4 controller.
```
```
* Added params for hector_gazebo_plugins/gazebo_ros_force_based_move.
* Using ros_force_based_move from ridgeback_simulator.
* Fixed xacro xmlns declaration and added Hokuyo minimun intensity.
```
- No changes
```
* Updated laser scan topic and robot footprint.  Also, enabled holonomic motion.
```

ridgeback: 0.1.6-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback_desktop` to `0.1.1-0`:
- upstream repository: https://github.com/ridgeback/ridgeback_desktop
- release repository: https://github.com/clearpath-gbp/ridgeback_desktop-release.git
- No changes
```
* Updated laser scan topic.
```

ridgeback_desktop: 0.1.1-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.5.3-0`:
- previous version for package: `0.5.2-1`
```
* Added support for PS4 controller.
```
- No changes
- No changes

jackal: 0.5.3-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `robot_pose_ekf_gpsfix` to `1.0.1-0`:
- upstream repository: https://bitbucket.org/clearpathrobotics/robot_pose_ekf_gpsfix.git
- release repository: git@bitbucket.org:clearpathrobotics/robot_pose_ekf_gpsfix-gbp.git

robot_pose_ekf_gpsfix: 1.0.1-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `heron` to `0.2.0-0`:
```
* Updated the UM6 orientation.
* Added SICK lms1xx laser and Axis ptz camera to accessories.
* Added Power message.
* Added optional Novatel Smart6 GPS, updated Gazebo GPS plugin and made default environment variables more specific.
* Fixed IMU angle substitution.
* Updated URDF.
```
```
* Changed Power message to Status.
* Added Power message.
* Updated URDF.
```

heron: 0.2.0-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `heron_controller` to `0.1.0-0`:
- upstream repository: git@bitbucket.org:clearpathrobotics/heron_controller.git
- release repository: git@bitbucket.org:clearpathrobotics/heron_controller-gbp.git
```
* Switched from updatePid to computeCommand as it is deprecated control_toolbox.
```

heron_controller: 0.1.0-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `heron_firmware` to `0.3.0-0`:
- upstream repository: git@bitbucket.org:clearpathrobotics/heron_firmware.git
- release repository: git@bitbucket.org:clearpathrobotics/heron_firmware-gbp.git
```
* Added user current sensing and created an estimate for power usage. Additionally, fulled out the rest of the fields of the new status message.
```
```
```

heron_firmware: 0.3.0-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `heron_robot` to `0.1.0-1`:
```
* Added Axis ptz to accessories.
* Updated nmea_topic_driver remap.
* Added env-hooks for mag and controller config.  Renamed folder kingfisher to heron.
* Added heron_base which currently only contains the base launch file and removed the many launch files in heron_bringup. Also, added accessories.launch for optional accessories.
```
```
* Added Axis ptz to accessories.
* Updated nmea_topic_driver remap.
* Added lms1xx accessory and …
```

heron_robot: 0.1.0-1 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `heron_robot` to `0.1.0-2`:
```
* Added Axis ptz to accessories.
* Updated nmea_topic_driver remap.
* Added env-hooks for mag and controller config.  Renamed folder kingfisher to heron.
* Added heron_base which currently only contains the base launch file and removed the many launch files in heron_bringup. Also, added accessories.launch for optional accessories.
```
```
* Added Axis ptz to accessories.
* Updated nmea_topic_driver remap.
* Added lms1xx accessory …
```

heron_robot: 0.1.0-2 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `declination` to `0.0.2-0`:
- upstream repository: https://github.com/clearpathrobotics/declination
- release repository: https://github.com/clearpath-gbp/declination-release.git
```
* Fix executable name.
```

declination: 0.0.2-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `enu` to `1.2.2-0`:
- upstream repository: https://github.com/clearpathrobotics/enu.git
- release repository: https://github.com/clearpath-gbp/enu-release.git
```
* Define _xerbla logging function to fix regression from swiftnav.
```

enu: 1.2.2-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `heron_robot` to `0.1.0-3`:
- previous version for package: `0.1.0-2`
```
* Added Axis ptz to accessories.
* Updated nmea_topic_driver remap.
* Added env-hooks for mag and controller config.  Renamed folder kingfisher to heron.
* Added heron_base which currently only contains the base launch file and removed the many launch files in heron_bringup. Also, added accessories.launch for optional accessories.
```
```
* Added Axis ptz to accessories.
* Updated nmea_topic_driver remap.
* Added lms1xx accessory …
```

heron_robot: 0.1.0-3 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `heron_firmware` to `0.3.1-0`:
- upstream repository: git@bitbucket.org:clearpathrobotics/heron_firmware.git
- release repository: git@bitbucket.org:clearpathrobotics/heron_firmware-gbp.git
```
* Added rosbash as build dependency and fixed units on power usage.
* Added missing publisher and minor improvements.
```
- No changes

heron_firmware: 0.3.1-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `heron` to `0.2.1-0`:
```
* Updated meshes and added rear plate.
```
- No changes

heron: 0.2.1-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `heron_robot` to `0.1.1-0`:
- previous version for package: `0.1.0-3`
- No changes
```
* Fixed axis ptz comment.
* Updated Axis PTZ default width and height.
```
- No changes
- No changes

heron_robot: 0.1.1-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback` to `0.1.7-0`:
- previous version for package: `0.1.6-0`
```
* Fixed teleop angular axis for PS4.
```
```
* Removed unused mesh.
* Uncommented RIDGEBACK_URDF_EXTRAS include.
```
- No changes
- No changes

ridgeback: 0.1.7-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `heron_robot` to `0.1.2-0`:
```
* Added tf and heron_controller as run dependency for heron_base.
* Added controller and ekf to base.launch.
```
```
* Added controller and ekf to base.launch.
* Added heron_base as run dependency to heron_bringup.
```
```
* Set queue_size to python publishers.
* Added navsat_sentence_relay.
```
- No changes

heron_robot: 0.1.2-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `heron_robot` to `0.1.3-0`:
```
* Moved ekf and imu_compass config to heron_base which fixes the circular dependency issues.  Removed camera launch and configuration files.
```
```
* Moved ekf and imu_compass config to heron_base which fixes the circular dependency issues.  Removed camera launch and configuration files.
```
- No changes
- No changes

heron_robot: 0.1.3-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `heron_robot` to `0.1.4-0`:
```
* Removed heron_bringup as run dependency from heron_base.
```
- No changes
- No changes
- No changes

heron_robot: 0.1.4-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `heron_robot` to `0.1.5-1`:
- previous version for package: `0.1.4-0`
```
* Add missing install rule for heron_base configs.
* Add missing install rule for heron_base configs.
```
```
* Added calibrate_compass and netserial scripts in heron_bringup to be installed.
* Added calibrate_compass and netserial scripts in heron_bringup to be installed.
```
```
* Updated the remap for the nmea_if socket node.
* …
```

heron_robot: 0.1.5-1 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `heron` to `0.2.2-0`:
- previous version for package: `0.2.1-0`
```
* Updated the UM6 orientation.
* Added lms1xx as run dependency.
```
- No changes

heron: 0.2.2-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback` to `0.1.8-0`:
- previous version for package: `0.1.7-0`
- No changes
```
* Added environment variable to set the robot configuration and empty configuration.
* Added cmd_vel timeout for force based move plugin.
```
- No changes
- No changes

ridgeback: 0.1.8-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `jackal_robot` to `0.3.6-0`:
- previous version for package: `0.3.5-0`
```
* Minor linter fixes to jackal_diagnostic_updater.
```
```
* Added parameter for flea3 camera frame rate.
* Added flea3 to accessories.
```
- No changes

jackal_robot: 0.3.6-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback_robot` to `0.1.7-0`:
- previous version for package: `0.1.6-0`
```
* Removed GPS dependencies.
* Contributors: Johannes Meyer, Tony Baltovski
```
- No changes
- No changes

ridgeback_robot: 0.1.7-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `husky_robot` to `0.2.6-0`:
- previous version for package: `0.2.4-0`
```
* Adding support for the UM7 IMU.
```
```
* Adding support for the UM7 IMU.
* Added new ur_modern_driver
* Added param for laser frame_id.
* Contributors: TheDash, Tony Baltovski
```
```
* Adding support for the UM7 IMU.
```

husky_robot: 0.2.6-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `warthog` to `0.0.1-0`:
```
```
```
```
```
```

warthog: 0.0.1-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `warthog_desktop` to `0.0.1-0`:
- upstream repository: https://github.com/warthog-cpr/warthog_desktop.git
- release repository: https://github.com/clearpath-gbp/warthog_desktop-release.git
```
```
```
```

warthog_desktop: 0.0.1-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `jackal_firmware` to `0.3.7-0`:
- previous version for package: `0.3.6-0`
```
* Switched to FreeRTOS from firmware components.
* Added support for the MPU-9250 IMU.
* Add defines for mutex changes in FreeRTOSConfig.
```

jackal_firmware: 0.3.7-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback_firmware` to `0.1.2-0`:
- bloom version: `0.5.23`
- previous version for package: `0.1.1-2`
```
* Updated hardware for minor MCU changes.
* Updated I2C devices for changes in firmware_components.
* Added ARP parameters for networking.
* Removed debug logging for IMU.
* Added missing files to roslint test and fixed issues.
```

ridgeback_firmware: 0.1.2-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback_firmware` to `0.1.2-1`:
- bloom version: `0.5.23`
```
* Updated hardware for minor MCU changes.
* Updated I2C devices for changes in firmware_components.
* Added ARP parameters for networking.
* Removed debug logging for IMU.
* Added missing files to roslint test and fixed issues.
```

ridgeback_firmware: 0.1.2-1 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback_firmware` to `0.1.2-2`:
- bloom version: `0.5.23`
```
* Updated hardware for minor MCU changes.
* Updated I2C devices for changes in firmware_components.
* Added ARP parameters for networking.
* Removed debug logging for IMU.
* Added missing files to roslint test and fixed issues.
```

ridgeback_firmware: 0.1.2-2 in 'indigo/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `puma_motor_driver` to `0.1.1-2`:
- bloom version: `0.5.23`
```
* Package format 2, dependency fix.
```
```
* Package format 2.
```

puma_motor_driver: 0.1.1-2 in 'kinetic/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback` to `0.1.9-0`:
- bloom version: `0.5.26`
- previous version for package: `0.1.8-0`
```
```
```
* Fixed malformed stl meshes.
* Reduced gyroscopes noise.
* Reverted dimensions of chassis collision mesh to allow laser rays out.
* Added Sick S300 laser and Microstrain IMU upgrade accessories.
* Updated material properties for Ridgeback.
* Fixed IMU offset.
```
```
```
```
* Changed amcl odom model …
```

ridgeback: 0.1.9-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback` to `0.1.10-0`:
- bloom version: `0.5.26`
- previous version for package: `0.1.9-0`
- No changes
```
* Updated the visual meshes to make them lighter and prettier.  More accurate collision mesh made for tight areas
* Used sick-s300 xacro for simulation.
```
- No changes
- No changes

ridgeback: 0.1.10-0 in 'indigo/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.3.0-0`:
```
* Fix default tyre radius
* changed the tire radius in base.launch to reflect a 13 inch Husky outdoor tire
* Remove defunct email address
* Updated maintainers.
* Update bringup for multirobot
* Update URDF for multirobot
* Move packages into monorepo for kinetic; strip out ur packages
* Contributors: Martin Cote, Paul Bovbel, Tony Baltovski, Wolfgang Merkt
```
```
* Remove defunct email address
* Re-added microstrain_3dmgx2_imu as run  dependency.
* Re-added imu_transformer and um7 …
```

husky: 0.3.0-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.6.0-0`:
```
* [jackal_control] Made the PS4 controller default.
* Made minor changes to syntax for kinetic warnings
```
- No changes
- No changes

jackal: 0.6.0-0 in 'kinetic/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.5.4-0`:
- previous version for package: `0.5.3-0`

jackal: 0.5.4-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `heron` to `0.2.3-0`:
- previous version for package: `0.2.2-0`

heron: 0.2.3-0 in 'indigo/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `heron` to `0.3.0-0`:
```
* Updated gps and imu default locations for next version of heron
* Updated stls and xacro definitions for kinetic syntax changes
```
- No changes

heron: 0.3.0-0 in 'kinetic/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `husky_simulator` to `0.2.7-0`:
- upstream repository: https://github.com/husky/husky_simulator.git
- release repository: https://github.com/clearpath-gbp/husky_simulator-release.git
- previous version for package: `0.2.4-0`
```
* Added empty.urdf to fix vanilla husky gazebo crash
* Respect env var setup similar to husky_description
* URDF Parameters for Husky Gazebo dnt respect envvr
Changed so the launch files follow the same convention as husky_description
* Contributors: Dave Niewinski, Devon Ash
```
- No changes

husky_simulator: 0.2.7-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `husky_robot` to `0.2.7-0`:
- previous version for package: `0.2.6-0`
```
* Follow-up to #9 <https://github.com/husky/husky_robot/issues/9>, missing default value for wheel_diameter
* changed Husky tire to 13 inches (0.3302m)
* Contributors: Martin Cote, Wolfgang Merkt
```
```
* Fixes for single-ur5 husky platform so that it works in production
* Contributors: Devon Ash
```
- No changes

husky_robot: 0.2.7-0 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `firmware_components` to `2.9.2-0`:
- upstream repository: git@gitlab.clearpathrobotics.com:firmware/firmware_components.git
- previous version for package: `0.6.2-0`
```
* Separating LWIP function tracing from other function tracing
* Contributors: Jeffrey Gorchynski
```

firmware_components: 2.9.2-0 in 'indigo/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `firmware_components` to `2.9.2-0`:
- upstream repository: git@gitlab.clearpathrobotics.com:firmware/firmware_components.git
```
* Separating LWIP function tracing from other function tracing
* Contributors: Jeffrey Gorchynski
```

firmware_components: 2.9.2-0 in 'kinetic/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `firmware_components` to `2.9.2-1`:
- upstream repository: git@gitlab.clearpathrobotics.com:firmware/firmware_components.git
- previous version for package: `2.9.2-0`
```
* Separating LWIP function tracing from other function tracing
* Contributors: Jeffrey Gorchynski
```

firmware_components: 2.9.2-1 in 'indigo/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `jackal_firmware` to `0.3.8-0`:
- previous version for package: `0.3.7-0`
```
* Consolidated udev.
* Implemented feature to report battery status on the Jackal based on total power consumed since start up.
* Contributors: Aditya Bhattacharjee, Tony Baltovski
```

jackal_firmware: 0.3.8-0 in 'indigo/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `jackal_firmware` to `0.3.8-0`:
```
* Consolidated udev.
* Implemented feature to report battery status on the Jackal based on total power consumed since start up.
* Contributors: Aditya Bhattacharjee, Tony Baltovski
```

jackal_firmware: 0.3.8-0 in 'kinetic/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `canfestival_ros` to `0.8.2-0`:
- upstream repository: git@gitlab.clearpathrobotics.com:software/canfestival_ros.git
- release repository: git@gitlab.clearpathrobotics.com:gbp/canfestival_ros-gbp.git
```
* CORE-7257 set socket to 0 after closing
* Contributors: Alex Bencz
```

canfestival_ros: 0.8.2-0 in 'indigo/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `canfestival_ros` to `0.8.4-0`:
- upstream repository: http://gitlab.clearpathrobotics.com/software/canfestival_ros.git
- release repository: http://gitlab.clearpathrobotics.com/gbp/canfestival_ros-gbp.git

canfestival_ros: 0.8.4-0 in 'kinetic/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `sevcon_ros` to `0.1.0-0`:
```
* Renaming packages in cmakelists and package.xml
* Rename meta-package.
* Contributors: Mike O'Driscoll
```
```
* Changed logging level.
* Changes for Warthog.
* Throttle switched.
* Move maximum torque to 100%
* Send syncs automatically at 20hz
* Launchfile update.
* Rename topics from /left/ to /left_drive/
* Renaming packages in cmakelists and package.xml
* Contributors: Mike O'Driscoll, Tony Baltovski
```

sevcon_ros: 0.1.0-0 in 'indigo/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `sevcon_ros` to `0.1.0-0`:
```
* Renaming packages in cmakelists and package.xml
* Rename meta-package.
* Contributors: Mike O'Driscoll
```
```
* Changed logging level.
* Changes for Warthog.
* Throttle switched.
* Move maximum torque to 100%
* Send syncs automatically at 20hz
* Launchfile update.
* Rename topics from /left/ to /left_drive/
* Renaming packages in cmakelists and package.xml
* Contributors: Mike O'Driscoll, Tony Baltovski
```

sevcon_ros: 0.1.0-0 in 'kinetic/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `warthog_firmware` to `0.0.1-0`:
```
* Updates for changes to hardware
* Updated to match PCA9685 in firmware_components.
* Enabled C++11.
* Added SBUS.
* Updated the power hardware and logic.  Changed the ADCs for the new board.  Modified the lighting to work with 4 lights.
```

warthog_firmware: 0.0.1-0 in 'indigo/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `warthog_firmware` to `0.0.1-0`:
```
* Updates for changes to hardware
* Updated to match PCA9685 in firmware_components.
* Enabled C++11.
* Added SBUS.
* Updated the power hardware and logic.  Changed the ADCs for the new board.  Modified the lighting to work with 4 lights.
```

warthog_firmware: 0.0.1-0 in 'kinetic/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `warthog_robot` to `0.0.1-0`:
```
* Removed timeout feature.
* [warthog_base] Fixed dupilcate parameter name.
* [warthog_base] Fixed comment.
* [warthog_base] Updated parameter names and added timeout for not getting data from the offboard stop source.
* [warthog_base] Added optional subscriber to stop Warthog.
* [warthog_base] Updated joint names.
* Minor linter fixes.
* Diagnostics changes
* [warthog_base] Changes for updated warthog_msgs.
* …
```

warthog_robot: 0.0.1-0 in 'indigo/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `warthog_desktop` to `0.0.1-1`:
- upstream repository: https://github.com/warthog-cpr/warthog_desktop.git
- release repository: https://github.com/clearpath-gbp/warthog_desktop-release.git
```
```
```
```

warthog_desktop: 0.0.1-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `warthog_robot` to `0.1.0-0`:
```
* Updated bringup for systemd
```
```
* Install all necessary files
* Removed scripts dir from install
* Updated bringup for systemd
```
- No changes

warthog_robot: 0.1.0-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `ridgeback_firmware` to `0.1.2-0`:
```
* Updated hardware for minor MCU changes.
* Updated I2C devices for changes in firmware_components.
* Added ARP parameters for networking.
* Removed debug logging for IMU.
* Added missing files to roslint test and fixed issues.
```

ridgeback_firmware: 0.1.2-0 in 'kinetic/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback_robot` to `0.1.8-0`:
- previous version for package: `0.1.7-0`
```
* [ridgeback_base] Added absolute value checking for fans.
* [ridgeback_base] Fixed a typo.
* Fixed temperature warning for PCB and MCU temperature.
```
```
* Added Sick S300 laser and Microstrain IMU upgrade accessories.
```
```
```

ridgeback_robot: 0.1.8-0 in 'indigo/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `ridgeback_robot` to `0.2.0-0`:
```
* [ridgeback_base] Added absolute value checking for fans.
* Updated to package format 2.
* [ridgeback_base] Switched to rosserial_server_udp.
* Updated bringup for kinetic
* [ridgeback_base] Fixed a typo.
* Fixed temperature warning for PCB and MCU temperature.
```
```
* Updated to package format 2.
* [ridgeback_base] Switched to rosserial_server_udp.
* Updated bringup for kinetic …
```

ridgeback_robot: 0.2.0-0 in 'kinetic/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback_firmware` to `0.1.3-0`:
- previous version for package: `0.1.2-2`
```
* Consolidated udev.
```

ridgeback_firmware: 0.1.3-0 in 'indigo/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `warthog_robot` to `0.1.1-0`:
```
* [warthog_base] Switched to rosserial_server_udp.
```
```
* [warthog_base] Switched to rosserial_server_udp.
```
- No changes

warthog_robot: 0.1.1-0 in 'kinetic/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `warthog_firmware` to `0.0.2-0`:
```
* Consolidated udev.
```

warthog_firmware: 0.0.2-0 in 'indigo/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `warthog_robot` to `0.1.2-0`:
```
* [warthog_base] Linter fixes.
* Updated to package format 2 and other minor CMake cleanup.
```
```
* Updated to package format 2 and other minor CMake cleanup.
* Removed un-needed install files.
```
```
* Updated to package format 2 and other minor CMake cleanup.
```

warthog_robot: 0.1.2-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `grizzly_firmware` to `0.3.0-0`:
- upstream repository: http://gitlab.clearpathrobotics.com/research/grizzly_firmware.git
- release repository: http://gitlab.clearpathrobotics.com/gbp/grizzly_firmware-gbp.git
```
* Added README.md.
* Switched to polling based ADC and moved communication timeouts to network task.
* Fixed linter and applied fixes.  Consolidated udev rules and removed un-needed tests.
* Enable the brake when the MCU is asserting an estop.
* Added motor temperature monitoring to the TCU.  Also, added helper function to fill CAN RX message and removed un-used function.
* Enable the brake when the MCU is asserting an estop.
* …
```

grizzly_firmware: 0.3.0-0 in 'kinetic/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `warthog_robot` to `0.0.2-0`:
- No changes
```
* Add can udev
```
- No changes

warthog_robot: 0.0.2-0 in 'indigo/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `warthog_robot` to `0.1.3-0`:
- No changes
```
* Add can udev
* Contributors: Michael Hosmar, Tony Baltovski
```
- No changes

warthog_robot: 0.1.3-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `grizzly_firmware` to `0.3.1-0`:
- upstream repository: http://gitlab.clearpathrobotics.com/research/grizzly_firmware.git
- release repository: http://gitlab.clearpathrobotics.com/gbp/grizzly_firmware-gbp.git
```
* Added initial delay to enabling the PSUs.
```

grizzly_firmware: 0.3.1-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `grizzly_motor_driver` to `0.0.2-0`:
- upstream repository: https://github.com/g/grizzly_motor_driver.git
- release repository: https://github.com/clearpath-gbp/grizzly_motor_driver-release.git
```
* [grizzly_motor_driver] Installed library and node.
```
- No changes

grizzly_motor_driver: 0.0.2-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `grizzly_motor_driver` to `0.0.2-1`:
- upstream repository: https://github.com/g/grizzly_motor_driver.git
- release repository: https://github.com/clearpath-gbp/grizzly_motor_driver-release.git
```
* [grizzly_motor_driver] Installed library and node.
```
- No changes

grizzly_motor_driver: 0.0.2-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `grizzly_robot` to `0.3.1-0`:
- No changes
```
* [grizzly_bringup] Removed install for non-existent file.
```
- No changes

grizzly_robot: 0.3.1-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `grizzly_robot` to `0.3.2-0`:
- No changes
```
* Sensor addition (#11 <https://github.com/g/grizzly_robot/issues/11>)
* Updated most of the payload launches
* Changed default ptu port for udev
* Contributors: dniewinski
```
- No changes

grizzly_robot: 0.3.2-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `grizzly` to `0.4.1-0`:
- upstream repository: https://github.com/g/grizzly.git
- release repository: https://github.com/clearpath-gbp/grizzly-release.git
- previous version for package: `0.4.0-0`
- No changes
```
* Updated urdf (#21 <https://github.com/g/grizzly/issues/21>)
* Updated urdf to have both sensor arches, all standard sensors, and some non-standard sensors
* URDF formatting
* Contributors: dniewinski
```
- No changes
- No changes

grizzly: 0.4.1-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `grizzly` to `0.4.2-0`:
- upstream repository: https://github.com/g/grizzly.git
- release repository: https://github.com/clearpath-gbp/grizzly-release.git
- previous version for package: `0.4.1-0`
- No changes
```
* [grizzly_description] Installed env_run script.
```
- No changes
- No changes

grizzly: 0.4.2-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `grizzly_robot` to `0.3.3-0`:
- previous version for package: `0.3.2-0`
- No changes
```
* Removed scripts in file locations as scripts are installed to root share
```
- No changes

grizzly_robot: 0.3.3-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `grizzly_robot` to `0.3.4-0`:
- previous version for package: `0.3.3-0`
- No changes
```
* [grizzly_bringup] Installed CAN systemhd job and make roslaunch a test dep.
```
- No changes

grizzly_robot: 0.3.4-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `grizzly_robot` to `0.3.5-0`:
- previous version for package: `0.3.4-0`
```
* [grizzly_base] Updated GPS indicator topic.
```
- No changes
- No changes

grizzly_robot: 0.3.5-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `grizzly_robot` to `0.3.5-1`:
- previous version for package: `0.3.5-0`
```
* [grizzly_base] Updated GPS indicator topic.
```
- No changes
- No changes

grizzly_robot: 0.3.5-1 in 'kinetic/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `warthog_firmware` to `0.0.3-0`:
```
* Enabled the MCU CAN2.
```

warthog_firmware: 0.0.3-0 in 'indigo/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `warthog_firmware` to `0.0.3-0`:
```
* Enabled the MCU CAN2.
```

warthog_firmware: 0.0.3-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.3.1-0`:
- No changes
```
* Renamed udev so it is installed
```
```
* Updated default controller to be PS4.  Can be set back to logitech (legacy) by setting HUSKY_LOGITECH environment variable
```
```
* Removed unnecessary dae objects and duplicate vertices
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Updated dependencies for …
```

husky: 0.3.1-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `jackal_robot` to `0.3.7-0`:
- previous version for package: `0.3.6-0`
```
* Updated the wireless interface for kinetic
```
```
* Updated default IPs for Kinetic
* Added stereo cameras accessory.
```
- No changes

jackal_robot: 0.3.7-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.6.1-0`:
- previous version for package: `0.6.0-0`
```
* Added missing twist_mux.yaml.  Fixed malformed meshes
* Added twist_mux and minor kinetic syntax changes
```
- No changes
- No changes

jackal: 0.6.1-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `ridgeback_robot` to `0.2.2-0`:

ridgeback_robot: 0.2.2-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `boxer` to `0.0.1-0`:
```
```
```
```
```
```
```
```
```
```

boxer: 0.0.1-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `visual_indication` to `0.0.1-0`:
- upstream repository: git@gitlab.clearpathrobotics.com:Boxer/visual_indication.git
- release repository: http://gitlab.clearpathrobotics.com/boxer_gbp/visual_indication.git
```
```

visual_indication: 0.0.1-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `robot_state_aggregator` to `0.0.1-0`:
- upstream repository: git@gitlab.clearpathrobotics.com:Boxer/robot_state_aggregator.git
- release repository: http://gitlab.clearpathrobotics.com/boxer_gbp/robot_state_aggregator.git
```
```
```
```
```
```

robot_state_aggregator: 0.0.1-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `cpr_common_msgs` to `0.0.1-0`:
- upstream repository: git@gitlab.clearpathrobotics.com:Boxer/cpr_common_msgs.git
- release repository: http://gitlab.clearpathrobotics.com/boxer_gbp/cpr_common_msgs.git
```
```
```
```
```
```
```
```

cpr_common_msgs: 0.0.1-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `boxer_firmware` to `0.0.1-0`:
- upstream repository: git@gitlab.clearpathrobotics.com:Boxer/boxer_firmware.git
- release repository: http://gitlab.clearpathrobotics.com/boxer_gbp/boxer_firmware.git
```
```

boxer_firmware: 0.0.1-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `boxer_simulator` to `0.0.1-0`:
```
```
```
```
```
```
```
```
```
```

boxer_simulator: 0.0.1-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `boxer_robot` to `0.0.1-0`:
```
```
```
```
```
```

boxer_robot: 0.0.1-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `boxer_desktop` to `0.0.1-0`:
- upstream repository: git@gitlab.clearpathrobotics.com:Boxer/boxer_desktop.git
- release repository: http://gitlab.clearpathrobotics.com/boxer_gbp/boxer_desktop.git
```
```
```
```

boxer_desktop: 0.0.1-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `linux_gpio_driver` to `0.0.1-0`:
- upstream repository: git@gitlab.clearpathrobotics.com:Boxer/linux_gpio_driver.git
- release repository: http://gitlab.clearpathrobotics.com/boxer_gbp/linux_gpio_driver.git
```
```

linux_gpio_driver: 0.0.1-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `boxer` to `0.0.2-0`:
```
* Fixed dependencies
```
- No changes
- No changes
```
* Fixed dependencies
```
- No changes

boxer: 0.0.2-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `boxer` to `0.0.2-1`:
```
* Fixed dependencies
```
- No changes
- No changes
```
* Fixed dependencies
```
- No changes

boxer: 0.0.2-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `boxer_simulator` to `0.0.3-0`:
- No changes
- No changes
- No changes
- No changes
```
```

boxer_simulator: 0.0.3-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `boxer_robot` to `0.0.2-0`:
```
* Dependencies
```
```
* Dependencies
```
- No changes

boxer_robot: 0.0.2-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `boxer_simulator` to `0.0.4-0`:
- previous version for package: `0.0.3-0`
```
* Fixed install
```
- No changes
- No changes
- No changes
- No changes

boxer_simulator: 0.0.4-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `boxer` to `0.0.3-0`:
```
* Fixed install
```
- No changes
- No changes
```
* Fixed install
```
- No changes

boxer: 0.0.3-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `boxer_simulator` to `0.0.5-0`:
- previous version for package: `0.0.4-0`
```
* Removed sonar visualization
```
- No changes
- No changes
- No changes
- No changes

boxer_simulator: 0.0.5-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `boxer_robot` to `0.0.4-0`:
- previous version for package: `0.0.3-0`
```
* Updated dependencies
```
- No changes
```
* Updated dependencies
```

boxer_robot: 0.0.4-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `jackal_robot` to `0.3.8-0`:
- previous version for package: `0.3.7-0`
```
* [jackal_base] Added environment variable for changing the wireless interface which controlls the light on the HMI.
* [jackal_base] Fixed linting.
```
- No changes
- No changes

jackal_robot: 0.3.8-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `boxer_robot` to `0.0.5-0`:
- previous version for package: `0.0.4-0`
```
* Added IMU filter
```
- No changes
- No changes

boxer_robot: 0.0.5-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `boxer_simulator` to `0.0.6-0`:
- previous version for package: `0.0.5-0`
```
* Cleaned up launches, model colours, and camera location
```
- No changes
- No changes
- No changes
- No changes

boxer_simulator: 0.0.6-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `boxer_robot` to `0.0.6-0`:
- previous version for package: `0.0.5-0`
```
* Updated camera config for spinnaker driver and synchronized triggering
* Added message_info_service
```
- No changes
- No changes

boxer_robot: 0.0.6-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `boxer` to `0.0.5-0`:
- previous version for package: `0.0.4-0`
```
* Updated acceleration to make the system more responsive
```
```
* Updated meshes and simplified description
```
- No changes
- No changes
- No changes

boxer: 0.0.5-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `jackal_firmware` to `0.3.9-0`:
- previous version for package: `0.3.8-0`
```
* Simple battery status light based on voltage
* Updated the udev rule to an actually tested one
* Updated udev rule for jackal mcu to avoid conflict with microstrain
* Contributors: Dave Niewinski, David Niewinski
```

jackal_firmware: 0.3.9-0 in 'kinetic/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `jackal_firmware` to `0.3.9-0`:
- previous version for package: `0.3.8-0`
```
* Simple battery status light based on voltage
* Updated the udev rule to an actually tested one
* Updated udev rule for jackal mcu to avoid conflict with microstrain
* Contributors: Dave Niewinski, David Niewinski
```

jackal_firmware: 0.3.9-0 in 'indigo/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `valence_bms` to `0.0.1-0`:
- release repository: http://gitlab.clearpathrobotics.com/gbp/valence_bms-gbp.git
```
* [valence_bms_driver] Fixed linter error.
* [valence_bms_driver] Added MultiModule publishing.
* [valence_bms_driver] Added args to example launch file.
* Added roslaunch and roslint tests.
```
```
* [valence_bms_driver] Added MultiModule publishing.
* [valence_bms_msgs] Updated ModuleInfo.
```

valence_bms: 0.0.1-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `valence_bms` to `0.0.2-0`:
- release repository: http://gitlab.clearpathrobotics.com/gbp/valence_bms-gbp.git
```
* Updated license and installed files.
```
```
* Updated license and installed files.
```

valence_bms: 0.0.2-0 in 'kinetic/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `firmware_components` to `2.9.3-0`:
- previous version for package: `2.9.2-1`
```
* [pca9685] Fixed bug with lighting enable reference passing.
```

firmware_components: 2.9.3-0 in 'indigo/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `firmware_components` to `2.9.3-0`:
- previous version for package: `2.9.2-1`
```
* [pca9685] Fixed bug with lighting enable reference passing.
```

firmware_components: 2.9.3-0 in 'kinetic/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `firmware_components` to `2.9.3-1`:
- previous version for package: `2.9.3-0`
```
* [pca9685] Fixed bug with lighting enable reference passing.
```

firmware_components: 2.9.3-1 in 'indigo/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `firmware_components` to `2.9.3-1`:
- previous version for package: `2.9.3-0`
```
* [pca9685] Fixed bug with lighting enable reference passing.
```

firmware_components: 2.9.3-1 in 'kinetic/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback_firmware` to `0.1.4-0`:
```
* Fixed bug in passing lighting_enable by reference.
```

ridgeback_firmware: 0.1.4-0 in 'indigo/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `ridgeback_firmware` to `0.1.4-0`:
```
* Fixed bug in passing lighting_enable by reference.
```

ridgeback_firmware: 0.1.4-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `boxer` to `0.0.6-0`:
- previous version for package: `0.0.5-0`
```
* Pulled well back on teleop until PS4 bug is fixed.
* Added extra config layer to control
```
- No changes
- No changes
- No changes
- No changes

boxer: 0.0.6-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `microhard_snmp` to `0.0.1-0`:
- release repository: git@gitlab.clearpathrobotics.com:gbp/microhard_snmp-gbp.git
```
* Initial Release
* Contributors: Michael Hosmar, Shrey Kavi
```

microhard_snmp: 0.0.1-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Jenkins doesn't work with ssh release urls.

Fix microhard_snmp url

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `heron_desktop` to `0.0.3-0`:
- upstream repository: https://github.com/heron/heron_desktop.git
- release repository: https://github.com/clearpath-gbp/heron_desktop-release.git
- No changes
```
* Merge pull request #1 <https://github.com/heron/heron_desktop/issues/1> from ssubramaniam-cpr/kinetic-devel
Changed interactive marker topic update
* Changed interative marker topic update
* Contributors: Shreya Subramaniam, Tony Baltovski
```

heron_desktop: 0.0.3-0 in 'kinetic/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `ridgeback_robot` to `0.1.9-0`:
- previous version for package: `0.1.8-0`
```
* [ridgeback_base] Updated compute_calibration to use a MagneticField message.
```
- No changes
- No changes

ridgeback_robot: 0.1.9-0 in 'indigo/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `ridgeback_robot` to `0.2.3-0`:
- previous version for package: `0.2.2-0`
```
* [ridgeback_base] Updated compute_calibration to use a MagneticField message.
```
- No changes
- No changes

ridgeback_robot: 0.2.3-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `ridgeback` to `0.2.2-0`:
```
* Changed boost::shared_ptr to urdfdom shared pointers
* ridgeback_control: fixed missing calculation of wheels_k_ (regression from daa4bc9050f786ed092fab911dd217da6febeae0)
* Simplify boolean logic for wheel separation checks
* Allow URDF to be optional
* Contributors: Catherine Wong, Chad Rockey, Johannes Meyer, Tony Baltovski
```
- No changes
- No changes
- No changes

ridgeback: 0.2.2-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `grizzly_robot` to `0.3.6-0`:
- previous version for package: `0.3.5-1`
```
* Fixing diagnostic updater to work with mcu/status message
* Contributors: Guy Stoppi
```
- No changes
- No changes

grizzly_robot: 0.3.6-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.3.2-0`:
- No changes
```
* [husky_bringup] Disabled the use of magnetic field msgs in imu_filter_madgwick.
```
- No changes
```
* Added some additional frames on the top plates and an environment variable for diabling the user rails
* Added env var to allow a 7cm forward bumper extension (#92 <https://github.com/husky/husky/issues/92>)
* Added env var to allow for extendable front bumper
* Fix weird spacing
* Uploaded bumper extension meshes
* Allowed for …
```

husky: 0.3.2-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.6.2-0`:
- previous version for package: `0.6.1-0`
- No changes
- No changes
- No changes

jackal: 0.6.2-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.3.3-0`:
- previous version for package: `0.3.2-0`
- No changes
- No changes
- No changes
```
* Fixed bumper extensions, cleaned up collision meshes
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

husky: 0.3.3-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.1-1`:
- upstream repository: http://gitlab.clearpathrobotics.com/research/cpr_gps_navigation
- release repository: http://gitlab.clearpathrobotics.com/gbp/cpr_gps_navigation-gbp
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

cpr_gps_navigation: 0.1.1-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `boxer_robot` to `0.0.7-1`:
- previous version for package: `0.0.6-0`
```
* Temporarily removed point grey camera driver dep until it is fixed in the buildfarm
* Linting
```
- No changes
- No changes

boxer_robot: 0.0.7-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `jackal_robot` to `0.3.9-1`:
- previous version for package: `0.3.8-0`
```
* [jackal_base] Minor launch file nit.
* Merge pull request #14 <https://github.com/jackal/jackal_robot/issues/14> from hawesie/kinetic-devel
Add parameter to change IMU message type.
* Add paramter to change IMU message type.
* Contributors: Nick Hawes, Tony Baltovski
```
```
* Temporarily removed point grey driver dependency
```
- No changes

jackal_robot: 0.3.9-1 in 'kinetic/distribution.yaml' [bloom]

---

indigo/distribution.yaml

Increasing version of package(s) in repository `jackal_robot` to `0.4.0-0`:
- previous version for package: `0.3.6-0`
```
* [jackal_base] Fixed linting.
```
```
* Temporarily removed point grey driver dependency
* Merge pull request #10 <https://github.com/jackal/jackal_robot/issues/10> from jackal/stereo-cameras
Added stereo cameras accessory.
* Added stereo cameras accessory.
```
- No changes

jackal_robot: 0.4.0-0 in 'indigo/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `jackal_robot` to `0.5.0-0`:
- previous version for package: `0.3.9-1`

jackal_robot: 0.5.0-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_common` to `0.1.1-1`:
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

cpr_gps_common: 0.1.1-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_common` to `0.1.2-0`:
```
* restart and revert changes
```
```
* restart and revert changes
```
```
* restart and revert changes
```
```
* roslint dependency for estop_monitor
* restart and revert changes
```
```
* restart and revert changes
* nav_utils
```
```
* restart and revert changes …
```

cpr_gps_common: 0.1.2-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `gps_mpc_navigation` to `0.1.1-0`:
```
* deps for bloom
* prepare for release and versions
* Merge branch 'dev' into 'master'
* Merge branch 'dependency_fix' into 'dev'
Dependency fix
See merge request research/gps_mpc_navigation!10
* Acado dep and warnings
* change structure of the folder to bloom and remove extra packages
```
```
* prepare for release and versions
* package dependency
* Merge branch 'dev' into …
```

gps_mpc_navigation: 0.1.1-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.1-0`:
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

cpr_gps_navigation: 0.1.1-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.2-0`:
- No changes
- No changes
- No changes
- No changes
```
* safety dependency build
```
- No changes

cpr_gps_navigation: 0.1.2-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `gps_mpc_navigation` to `0.1.2-0`:
```
* removed local planner limits
```
- No changes
- No changes
- No changes
- No changes

gps_mpc_navigation: 0.1.2-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.3.4-1`:
- previous version for package: `0.3.3-0`
- No changes
```
* Properly support GX5.
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

husky: 0.3.4-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `firmware_components` to `2.9.4-1`:
- previous version for package: `2.9.3-1`
```
* Removed error count reset preventing i2c bus reinit
* Contributors: lazzalini
```

firmware_components: 2.9.4-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.3-0`:
```
* Merge branch 'naked_repo' into 'master'
removing params and launch files
See merge request research/cpr_gps_navigation!29
* removing params and launch files
* laser filter
```
- No changes
```
* Merge branch 'naked_repo' into 'master'
removing params and launch files
See merge request research/cpr_gps_navigation!29
* removing params and launch files
* Contributors: Ebrahim, …
```

cpr_gps_navigation: 0.1.3-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `boxer` to `0.0.7-0`:
- previous version for package: `0.0.6-0`
```
* Added a top frame and fixed diagnostics dependency
```
```
* Added top plate mesh
* Added a top frame and fixed diagnostics dependency
```
- No changes
- No changes
- No changes

boxer: 0.0.7-0 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `boxer` to `0.0.8-1`:
- previous version for package: `0.0.7-0`
- No changes
```
* Updated robot name in urdf
```
- No changes
- No changes
- No changes

boxer: 0.0.8-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.4.0-1`:
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Removed frontier_exploration temporarily for Melodic.
```
- No changes
- No changes
- No changes

husky: 0.4.0-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `firmware_components` to `2.9.4-1`:
```
* Removed error count reset preventing i2c bus reinit
* Contributors: lazzalini
```

firmware_components: 2.9.4-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `jackal_firmware` to `0.3.9-1`:
```
* Simple battery status light based on voltage
* Updated the udev rule to an actually tested one
* Updated udev rule for jackal mcu to avoid conflict with microstrain
* Contributors: Dave Niewinski, David Niewinski
```

jackal_firmware: 0.3.9-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `ridgeback_firmware` to `0.1.4-1`:
```
* Fixed bug in passing lighting_enable by reference.
```

ridgeback_firmware: 0.1.4-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `warthog_firmware` to `0.0.3-1`:
```
* Enabled the MCU CAN2.
```

warthog_firmware: 0.0.3-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `jackal_robot` to `0.5.0-1`:

jackal_robot: 0.5.0-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `puma_motor_driver` to `0.1.1-1`:
```
* Package format 2, dependency fix.
```
```
* Package format 2.
```

puma_motor_driver: 0.1.1-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `puma_motor_driver` to `0.1.1-1`:
- previous version for package: `0.1.1-2`
```
* Package format 2, dependency fix.
```
```
* Package format 2.
```

puma_motor_driver: 0.1.1-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `puma_motor_driver` to `0.2.0-1`:
```
* Renamed verifying 16x16 raw bytes and added verfying 8x8 function. Added parentheses to evaluate AND before comparison and added default case to switch statement in non-void function. Also, minor linter fixes.
* Updated fixed-point conversion.
```
- No changes

puma_motor_driver: 0.2.0-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `puma_motor_driver` to `0.2.0-1`:
```
* Renamed verifying 16x16 raw bytes and added verfying 8x8 function. Added parentheses to evaluate AND before comparison and added default case to switch statement in non-void function. Also, minor linter fixes.
* Updated fixed-point conversion.
```
- No changes

puma_motor_driver: 0.2.0-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.5-1`:
- previous version for package: `0.1.4-0`
```
* initialize estimate service
```
- No changes
- No changes
- No changes
- No changes
- No changes

cpr_gps_navigation: 0.1.5-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.5-2`:
```
* initialize estimate service
```
- No changes
- No changes
- No changes
- No changes
- No changes

cpr_gps_navigation: 0.1.5-2 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.6-1`:
- previous version for package: `0.1.5-2`
```
* pose_set_wait_threshold
* use imu/data instead of mag
```
- No changes
- No changes
- No changes
- No changes
- No changes

cpr_gps_navigation: 0.1.6-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.4.1-1`:
- No changes
```
* [husky_bringup] Enabled using MagnenticField message for UM6 and UM7 since imu_filter_madgwick now uses it by default.
* Added Udev rule for Logitech joy. (#116 <https://github.com/husky/husky/issues/116>)
```
```
* Added envar for joy device.
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

husky: 0.4.1-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.7-1`:
```
* Merge branch 'rpy_or_imu_data' into 'master'
```
- No changes
- No changes
- No changes
- No changes
```
* reduce wait time
```

cpr_gps_navigation: 0.1.7-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `warthog_robot` to `0.1.4-1`:
```
* [warthog_base] Removed global namespace.
```
- No changes
- No changes

warthog_robot: 0.1.4-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `jackal_firmware` to `0.3.10-1`:
- previous version for package: `0.3.9-0`
```
* Enabled the fan header once the PCB temperature goes over 35C.
```

jackal_firmware: 0.3.10-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `jackal_firmware` to `0.4.0-1`:
- previous version for package: `0.3.9-1`
```
* Switch to MagneticField message rather than Vector3Stamped.
```

jackal_firmware: 0.4.0-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `firmware_components` to `2.9.5-1`:
- previous version for package: `2.9.4-1`
- No changes

firmware_components: 2.9.5-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `puma_motor_driver` to `0.2.1-1`:
```
* [puma_motor_driver] Disabld checking of message if it was a status cause it was causing issues.
```
- No changes

puma_motor_driver: 0.2.1-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `puma_motor_driver` to `0.2.1-1`:
```
* [puma_motor_driver] Disabld checking of message if it was a status cause it was causing issues.
```
- No changes

puma_motor_driver: 0.2.1-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `ridgeback_robot` to `0.2.4-1`:
- previous version for package: `0.2.3-0`
```
* Merge pull request #26 <https://github.com/ridgeback/ridgeback_robot/issues/26> from ridgeback/RPSW-119
Added the ability to disable using the MCU
* [ridgeback_base] Added param type for use_mcu.
* [ridgeback_base] Added lighting and cooling under use_mcu flag.
* [ridgeback_base] Added envar for using MCU.
```
- No changes
- No changes

ridgeback_robot: 0.2.4-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `ridgeback_robot` to `0.2.4-1`:
```
* Merge pull request #26 <https://github.com/ridgeback/ridgeback_robot/issues/26> from ridgeback/RPSW-119
Added the ability to disable using the MCU
* [ridgeback_base] Added param type for use_mcu.
* [ridgeback_base] Added lighting and cooling under use_mcu flag.
* [ridgeback_base] Added envar for using MCU.
```
- No changes
- No changes

ridgeback_robot: 0.2.4-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `valence_bms` to `0.0.2-1`:
- release repository: http://gitlab.clearpathrobotics.com/gbp/valence_bms-gbp.git
```
* Updated license and installed files.
```
```
* Updated license and installed files.
```

valence_bms: 0.0.2-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `moose` to `0.1.0-1`:
- upstream repository: https://github.com/moose-cpr/moose.git
- release repository: https://github.com/clearpath-gbp/moose-release.git
```
* Updated collisions,
* Made the generator optional
* Moved interactive markers to manned control and removed joy
* Added wheels to URDF.
* Initial commit for Moose.
```
```
* Updated collisions,
* Made the generator optional
* Moved interactive markers to manned control and removed joy
* Added wheels to URDF.
* Initial commit for Moose.
```
```
* Initial commit for Moose.
* …
```

moose: 0.1.0-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.3.5-1`:

husky: 0.3.5-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.4.2-1`:
- No changes
```
* [husky_bringup] Installed udev rule for Logitech controller.
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

husky: 0.4.2-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `moose_desktop` to `0.1.0-3`:
- upstream repository: https://github.com/moose-cpr/moose_desktop.git
- release repository: https://github.com/clearpath-gbp/moose_desktop-release.git
```
```
```
```

moose_desktop: 0.1.0-3 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `moose_firmware` to `0.1.0-1`:
- upstream repository: http://gitlab.clearpathrobotics.com/research/moose_firmware.git
- release repository: http://gitlab.clearpathrobotics.com/gbp/moose_firmware-gbp.git
```
* Updated generator start logic.
```

moose_firmware: 0.1.0-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `moose_motor_driver` to `0.1.0-1`:
- upstream repository: http://gitlab.clearpathrobotics.com/research/moose_motor_driver.git
- release repository: http://gitlab.clearpathrobotics.com/gbp/moose_motor_driver-gbp.git
```
* [moose_motor_driver] minor linting.
* Added fault detection.
```
```
* Added fault detection.
```

moose_motor_driver: 0.1.0-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `moose_robot` to `0.1.0-1`:
```
* Merge branch 'diagnostics_agg' into 'master'
Added diagnostics_agg
See merge request research/moose_robot!1
* Added diagnostics_agg
* [moose_base] Added bms driver to base launch.
* Fixed valence_bms_driver dependency.
* [moose_base] Fixed linter errors.
* Initial work for moose.
* Contributors: Dave Niewinski, David Niewinski, Tony Baltovski
```
```
* Fixed valence_bms_driver dependency.
* Initial work for moose.
* Contributors: Tony …
```

moose_robot: 0.1.0-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `moose-simulator` to `0.1.0-1`:
- upstream repository: https://github.com/moose-cpr/moose_simulator.git
- release repository: https://github.com/clearpath-gbp/moose_simulator-release.git
```
* Merge pull request #1 <https://github.com/moose-cpr/moose_simulator/issues/1> from dniewinski/gazebo_cleanup
Gazebo cleanup
* Added script install
* Made a dummy keyswitch node to still use the same mux setup as the robot
* Using moose_description instead of duplicating description
* Merge branch 'master' into 'master'
Initial Moose simulator
See merge request research/moose_simulator!1
* Initial Moose simulator
* Contributors: Dave Niewinski, Loic …
```

moose-simulator: 0.1.0-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `moose_simulator` to `0.1.0-2`:
- upstream repository: https://github.com/moose-cpr/moose_simulator.git
- release repository: https://github.com/clearpath-gbp/moose_simulator-release.git
```
* Merge pull request #1 <https://github.com/moose-cpr/moose_simulator/issues/1> from dniewinski/gazebo_cleanup
Gazebo cleanup
* Added script install
* Made a dummy keyswitch node to still use the same mux setup as the robot
* Using moose_description instead of duplicating description
* Merge branch 'master' into 'master'
Initial Moose simulator
See merge request research/moose_simulator!1
* Initial Moose simulator
* Contributors: Dave Niewinski, …
```

moose_simulator: 0.1.0-2 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `moose_robot` to `0.1.1-1`:
```
* [moose_base] Updated dependencies.
```
- No changes
- No changes

moose_robot: 0.1.1-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `moose_simulator` to `0.1.1-1`:
- upstream repository: https://github.com/moose-cpr/moose_simulator.git
- release repository: https://github.com/clearpath-gbp/moose_simulator-release.git
- previous version for package: `0.1.0-2`
```
* [moose_gazebo] Updated dependencies.
```
- No changes

moose_simulator: 0.1.1-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `boxer_robot` to `0.0.9-1`:
- previous version for package: `0.0.8-1`
```
* Updated camera framerate
```
- No changes
- No changes

boxer_robot: 0.0.9-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `heron` to `0.3.2-1`:
```
* [heron_control] Fixing missing dep and minor clean-up.
```
```
* Changed mesh declarations to use packages instead of xacro finds (#8 <https://github.com/heron/heron/issues/8>)
```
- No changes

heron: 0.3.2-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `jackal_firmware` to `0.3.11-1`:
- previous version for package: `0.3.10-1`
```
* Merge branch 'rpsw-173' into 'indigo-devel'
Fix NMEA sentence termination bug
See merge request research/jackal_firmware!30
* Fix NMEA sentence termination bug
* Contributors: Chris Iverach-Brereton, David Niewinski
```

jackal_firmware: 0.3.11-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `jackal_firmware` to `0.4.1-1`:
```
* Fix NMEA sentence termination bug
```

jackal_firmware: 0.4.1-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `ridgeback_cartographer_navigation` to `0.0.1-1`:
- upstream repository: https://github.com/ridgeback/ridgeback_cartographer_navigation.git
- release repository: https://github.com/clearpath-gbp/ridgeback_cartographer_navigation-release.git
```
* Added ridgeback_navigation as run dep.
* Removed rviz to use ridgeback_viz.
* Merge pull request #3 <https://github.com/ridgeback/ridgeback_cartographer_navigation/issues/3> from ljazzal/master
Updated dependencies to use cartographer_ros pkg instead of building from source
* minor changes to carto params, install instruction
* changed tracking frame back to imu_link
* …
```

ridgeback_cartographer_navigation: 0.0.1-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `husky_cartographer_navigation` to `0.0.1-1`:
- upstream repository: https://github.com/husky/husky_cartographer_navigation.git
- release repository: https://github.com/clearpath-gbp/husky_cartographer_navigation-release.git
```
* Removed rviz to use husky_viz.
* minor change to install instructions
* removed unused file
* added cartographer_ros as run depend
* updated install instructions
* Added brief Cartographer description and generated image
* Update CMakeLists.txt to install custom RViz config
* Modified install script to clone repos based on ros distro
* Slight tuning
* Fix install script …
```

husky_cartographer_navigation: 0.0.1-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `husky_cartographer_navigation` to `0.0.2-1`:
- upstream repository: https://github.com/husky/husky_cartographer_navigation.git
- release repository: https://github.com/clearpath-gbp/husky_cartographer_navigation-release.git
```
* Updated to package.xml format 2.
* Added husky_navigation as run dep.
```

husky_cartographer_navigation: 0.0.2-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `ridgeback` to `0.2.3-1`:
- previous version for package: `0.2.2-0`
```
* Fix controller odom bug, it works well in multi robots case now
* Contributors: yizheng
```
```
* [ridgeback_description] Removing namespace arg.
* Add namespace to gazebo plugin, it works well in multi robots case now
* Contributors: Tony Baltovski, yizheng
```
- No changes
- No changes

ridgeback: 0.2.3-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `ridgeback` to `0.2.3-1`:
```
* Fix controller odom bug, it works well in multi robots case now
* Contributors: yizheng
```
```
* [ridgeback_description] Removing namespace arg.
* Add namespace to gazebo plugin, it works well in multi robots case now
* Contributors: Tony Baltovski, yizheng
```
- No changes
- No changes

ridgeback: 0.2.3-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.6.4-1`:
```
* Update control.launch
Somehow a ">" has gone missing. This change adds it back in.
* [jackal_control] Added control extras.
* Contributors: Jeff Schmidt, Tony Baltovski
```
```
* Modify the hokuyo accessory so that it works properly in gazebo/rviz.  Add an additional environment var JACKAL_LASER_HOKUYO which overrides the default lms1xx sensor with the ust10.
* use env_run.bat on Windows (#3 <https://github.com/jackal/jackal/issues/3>)
* add setlocal
* Fix jackal_description …
```

jackal: 0.6.4-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `jackal_firmware` to `0.4.2-1`:
- release repository: git@gitlab.clearpathrobotics.com:gbp/jackal_firmware-gbp.git
```
* Apply fixes from Otto for Bionic+Melodic
* Fix misleading indentation
```

jackal_firmware: 0.4.2-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.6.4-3`:
- previous version for package: `0.6.4-1`
```
* Update control.launch
Somehow a ">" has gone missing. This change adds it back in.
* [jackal_control] Added control extras.
* Contributors: Jeff Schmidt, Tony Baltovski
```
```
* Modify the hokuyo accessory so that it works properly in gazebo/rviz.  Add an additional environment var JACKAL_LASER_HOKUYO which overrides the default lms1xx sensor with the ust10.
* use env_run.bat on Windows (#3 <https://github.com/jackal/jackal/issues/3>)
* add setlocal
* Fix jackal_description …
```

jackal: 0.6.4-3 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.3.6-1`:
- previous version for package: `0.3.5-1`

husky: 0.3.6-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.4.3-1`:
- No changes
```
* Add the other product ID for the PS4 controller to the udev rule
* Update the udev rules to map the controllers to appropriate symlinks instead of relying on device enumeration to save us
```
```
* Update the udev rules to map the controllers to appropriate symlinks instead of relying on device enumeration to save us
* Remove the device override for the PS4 controller since we pair with bluez now (which maps the device to /dev/input/js0)
* …
```

husky: 0.4.3-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.6.5-2`:
- previous version for package: `0.6.4-1`

jackal: 0.6.5-2 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.7.0-1`:
- previous version for package: `0.6.4-3`
```
* Mark the PS3 controller launch file as deprecated, update the default joystick device to point to /dev/input/ps4, as per the new udev rules added to the bringup package
```
```
* [jackal_description] Re-added pointgrey_camera_description as run depend.
```
- No changes
- No changes

jackal: 0.7.0-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `jackal_robot` to `0.6.0-1`:
- previous version for package: `0.5.0-1`
```
* [jackal_base] Stopped using Vector3 messages for on-board IMU.
* Folding Wifi into single function
* removed extra code.
* specify jackal serial port as arg in launch file (#7 <https://github.com/jackal/jackal_robot/issues/7>)
* allow configuring jackal's port in env (#6 <https://github.com/jackal/jackal_robot/issues/6>)
* fix calibration script (#5 <https://github.com/jackal/jackal_robot/issues/5>)
* fix batch file
* fix batch script for mix use of forward …
```

jackal_robot: 0.6.0-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `jackal_robot` to `0.5.1-1`:
- previous version for package: `0.5.0-0`
```
* [jackal_base] Stopped using Vector3 messages for on-board IMU.
* Merge pull request #17 <https://github.com/jackal/jackal_robot/issues/17> from ms-iot/init_windows
Support Jackal ROS packages on Windows
* Merge branch 'init_windows' of https://github.com/ms-iot/jackal_robot into init_windows
* Folding Wifi into single function
* removed extra code.
* specify jackal serial port as arg in launch file (#7 <https://github.com/jackal/jackal_robot/issues/7>)
* …
```

jackal_robot: 0.5.1-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `ridgeback_firmware` to `0.2.0-1`:
```
* Apply fixes for Melodic+Bionic from Jackal
```

ridgeback_firmware: 0.2.0-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `ridgeback` to `0.3.0-1`:
```
* Fix the default device for the PS4 controller to match with the updated udev rules for bionic
```
- No changes
- No changes
- No changes

ridgeback: 0.3.0-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.8-2`:
```
* Merge branch 'parallel_planner' into 'master'
Parallel planner
* Contributors: Ebrahim, Ebrahim Shahrivar, Jose Mastrangelo
```
```
* Merge branch 'parallel_planner' into 'master'
Parallel planner
* path smoothing server
```
```
* Merge branch 'parallel_planner' into 'master'
Parallel planner
```
```
* Merge branch 'parallel_planner' …
```

cpr_gps_navigation: 0.1.8-2 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `gps_mpc_navigation` to `0.1.3-1`:
- No changes
```
* Merge branch 'turning_radius' into 'master'
* Contributors: Ebrahim Shahrivar, Jose Mastrangelo, José Mastrangelo
```
```
* Merge branch 'turning_radius' into 'master'
* Contributors: Ebrahim, Ebrahim Shahrivar, Jose Mastrangelo, José Mastrangelo
```
- No changes
- No changes

gps_mpc_navigation: 0.1.3-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_common` to `0.1.3-1`:
- No changes
- No changes
- No changes
- No changes
- No changes
```
```
- No changes
- No changes
```
```
- No changes

cpr_gps_common: 0.1.3-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.9-1`:
- previous version for package: `0.1.8-2`
- No changes
- No changes
- No changes
```
* Merge branch 'devel' into 'master'
* Contributors: Ebrahim, Ebrahim Shahrivar, Jose Mastrangelo
```
```
```
- No changes
- No changes

cpr_gps_navigation: 0.1.9-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.10-1`:
- No changes
- No changes
- No changes
```
* dependency issue on jackal
```
- No changes
- No changes
- No changes

cpr_gps_navigation: 0.1.10-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo` to `0.1.0-1`:
```
* Fix the controller parameters for omni control; behaviour is now the same as ridgeback
* Unified Dingo folders/files as much as possible, updated meshes, bumped CMake version and made roslaunch a test depend.
* Added dingo_control; split dingo_description into separate Dingo-D and Dingo-O flavours; still much work to be done here, but preparing hand-off for Tony
* Contributors: Chris Iverach-Brereton, Jason Higgins, Tony Baltovski
```
```
* Unified Dingo folders/files as much …
```

dingo: 0.1.0-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.11-1`:
```
* Merge branch 'devel' into 'master'
Devel
See merge request gps-navigation/cpr_gps_navigation!53
See merge request gps-navigation/cpr_gps_navigation!52
```
```
```
```
* See merge request gps-navigation/cpr_gps_navigation!52
```
```
* Contributors: Ebrahim, Ebrahim Shahrivar, Jose Mastrangelo, José …
```

cpr_gps_navigation: 0.1.11-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `gps_mpc_navigation` to `0.1.4-2`:
```
* See merge request gps-navigation/gps_mpc_navigation!18
```
```
* See merge request gps-navigation/gps_mpc_navigation!18
```
```
* Contributors: Ebrahim, Ebrahim Shahrivar, Jose Mastrangelo, José Mastrangelo
```
```
* See merge request gps-navigation/gps_mpc_navigation!18
```
```
* See merge request …
```

gps_mpc_navigation: 0.1.4-2 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_common` to `0.1.4-2`:
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Merge branch 'devel' into 'master'
* Contributors: Ebrahim Shahrivar, Jose Mastrangelo, José Mastrangelo
```
- No changes

cpr_gps_common: 0.1.4-2 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo_simulator` to `0.1.0-1`:
- upstream repository: https://github.com/dingo-cpr/dingo_simulator.git
- release repository: https://github.com/clearpath-gbp/dingo_simulator-release.git
```
* Revert to using dirname; i blanked on the conversation where we went over the new standards
* Add the empty world launch file (useful for replaying bags w/o obstacles getting in the way)
* Add spawn_dingo.launch for compatibility with the new simulation environments. Enable teleop by default in the simulations. Use $(find ...) instead of $(dirname) for improved compatibility with external packages
* Unified launch files, added platform specific …
```

dingo_simulator: 0.1.0-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo_desktop` to `0.1.0-1`:
```
* Consolidated launch files.
* Split the single launch file into separate launch files for Dingo-D vs Dingo-O; updated project maintainer to Tony
* Added viz and desktop packages
* Contributors: Dave Niewinski, Jason Higgins, Tony Baltovski
```
```
* Consolidated launch files.
* Split the single launch file into separate launch files for Dingo-D vs Dingo-O; updated project maintainer to Tony
* Added viz and desktop packages
* Contributors: Dave Niewinski, …
```

dingo_desktop: 0.1.0-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.3.7-1`:
- previous version for package: `0.3.6-1`

husky: 0.3.7-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.4.4-1`:
- previous version for package: `0.4.3-1`
```
* Removed Paul Bovbel as maintainer.
```
```
* Set default for optenv HUSKY_MAG_CONFIG
* Removed env-hooks
* Removed Paul Bovbel as maintainer.
* Add support for some environment variables to override realsense defaults
* Sort the dependencies alphabetically
* Finish adding the simulated realsense to the topbar, add support for the physical realsense. Tidy up some parameters that were copied in last night but not yet configured.
* Mark the Kinect for …
```

husky: 0.4.4-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `boxer_robot` to `0.0.10-1`:
- upstream repository: http://gitlab.clearpathrobotics.com/Boxer/boxer_robot.git
- previous version for package: `0.0.9-1`
```
* Updated camera framerates for hardware limitations
* Put parentheses around the print statements
* Contributors: Chris I-B, Dave Niewinski
```
- No changes
- No changes

boxer_robot: 0.0.10-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.6.6-1`:
- previous version for package: `0.6.5-2`
```
* Disable ekf option (#71 <https://github.com/jackal/jackal/issues/71>)
* added env var and if-statement to disable robot ekf
* changed if to unless
* clearer wording
* Contributors: jmastrangelo-cpr
```
- No changes
- No changes
```
* Remove the leading / from the gmapping default scan topic
* Expose the scan_topic and use_map_topic parameters in the demo launch files
```

jackal: 0.6.6-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `moose_motor_driver` to `0.1.0-1`:
- upstream repository: http://gitlab.clearpathrobotics.com/research/moose_motor_driver.git
- release repository: http://gitlab.clearpathrobotics.com/gbp/moose_motor_driver-gbp.git
```
* [moose_motor_driver] minor linting.
* Added fault detection.
```
```
* Added fault detection.
```

moose_motor_driver: 0.1.0-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `moose` to `0.1.0-1`:
- upstream repository: https://github.com/moose-cpr/moose.git
- release repository: https://github.com/clearpath-gbp/moose-release.git
```
* Updated collisions,
* Made the generator optional
* Moved interactive markers to manned control and removed joy
* Added wheels to URDF.
* Initial commit for Moose.
```
```
* Updated collisions,
* Made the generator optional
* Moved interactive markers to manned control and removed joy
* Added wheels to URDF.
* Initial commit for Moose.
```
```
* Initial commit for Moose.
* …
```

moose: 0.1.0-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `moose_firmware` to `0.1.0-1`:
- upstream repository: http://gitlab.clearpathrobotics.com/research/moose_firmware.git
- release repository: http://gitlab.clearpathrobotics.com/gbp/moose_firmware-gbp.git
```
* Updated generator start logic.
```

moose_firmware: 0.1.0-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `moose_robot` to `0.1.1-1`:
```
* [moose_base] Updated dependencies.
```
- No changes
- No changes

moose_robot: 0.1.1-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo` to `0.1.1-1`:
```
* Improve joy device configurability (#4 <https://github.com/dingo-cpr/dingo/issues/4>)
* Remove the joy device from the yaml file, but keep it as the default in the launch file. Add support for a DINGO_JOY_DEV environment variable to override the default joy device.
* Add the ASCII art diagram of the controller from Husky to make it easier to interpret the button mappings, should anyone want to remap them.
* Expose the yaml file as an additional argument to the teleop launch …
```

dingo: 0.1.1-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `warthog` to `0.1.2-1`:
```
* Remove unused arg and set joysticks to use joy topic. (#11 <https://github.com/warthog-cpr/warthog/issues/11>)
* Disable ekf option (#9 <https://github.com/warthog-cpr/warthog/issues/9>)
* added env var and if-statement to disable robot ekf
* changed if to unless
* clearer wording
* chenged default to true
* [warthog_control] Removed rosserial_server as run dependency.
* Contributors: Michael Hosmar, Tony Baltovski, jmastrangelo-cpr
```
```
* Add the legacy namespace …
```

warthog: 0.1.2-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `warthog` to `0.1.2-1`:
```
* Remove unused arg and set joysticks to use joy topic. (#11 <https://github.com/warthog-cpr/warthog/issues/11>)
* Disable ekf option (#9 <https://github.com/warthog-cpr/warthog/issues/9>)
* added env var and if-statement to disable robot ekf
* changed if to unless
* clearer wording
* chenged default to true
* [warthog_control] Removed rosserial_server as run dependency.
* Contributors: Michael Hosmar, Tony Baltovski, jmastrangelo-cpr
```
```
* Add the legacy namespace …
```

warthog: 0.1.2-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `heron` to `0.3.3-1`:
- No changes
```
* Update ROS deps to remove/rename third-party packages that are not available on Melodic
* Related to https://github.com/heron/heron_simulator/pull/6.  Change the topic that the mag data is published to so we can translate it to the new message standard to work-around a bug with the imu filter.
```
- No changes

heron: 0.3.3-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `heron` to `0.3.3-1`:
- No changes
```
* Update ROS deps to remove/rename third-party packages that are not available on Melodic
* Related to https://github.com/heron/heron_simulator/pull/6.  Change the topic that the mag data is published to so we can translate it to the new message standard to work-around a bug with the imu filter.
```
- No changes

heron: 0.3.3-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `heron_simulator` to `0.3.0-1`:
```
* Add the UUV worlds dependency
* Rename "heron_sim" to "spawn_heron" for compatibility with the new simulation environments
* Tidy up the lake world a little, set the camera position so the initial view is a little nicer
* Add a second world, a lake with some islands (also copied from UUV Worlds so we can modify as-necessary for a surface-only vehicle)
* Add a copy of the world to make future modifications easier. Fix the initial camera position so that …
```

heron_simulator: 0.3.0-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo` to `0.1.2-1`:
```
* [dingo_control] Reduced Dingo-O accelerations.
* [dingo_control] Reduced line length.
* [dingo_control] Removed linear accelerations from EKF.
```
- No changes
- No changes
- No changes

dingo: 0.1.2-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo` to `0.1.3-1`:
```
* Remove the 0/1 DINGO_CONTROL_EXTRAS + DINGO_CONTROL_EXTRAS_PATH, simplify to just DINGO_CONFIG_EXTRAS, like Husky & Warthog. (#6 <https://github.com/dingo-cpr/dingo/issues/6>)
* [dingo_control] Reduced linear acceleration limits.
* Contributors: Chris I-B, Tony Baltovski
```
- No changes
- No changes
```
* Make the default scan topic for gmapping + amcl use the env vars (#7 <https://github.com/dingo-cpr/dingo/issues/7>)
Load the DINGO_LASER_TOPIC env var as the default scan …
```

dingo: 0.1.3-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.6.7-1`:
- previous version for package: `0.6.6-1`
```
* Apply similar change as https://github.com/jackal/jackal/pull/73 for Kinetic
```
- No changes
- No changes
- No changes

jackal: 0.6.7-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.7.2-1`:
- previous version for package: `0.7.0-1`

jackal: 0.7.2-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.4.5-1`:
- previous version for package: `0.4.4-1`
- No changes
```
* Fix a bug where the UM7 and UM6 launch files don't work when installed to /etc/ros/*/ros.d; they fail to find the mag config files.
```
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Expose the scan_topic argument in amcl_demo and gmapping_demo, make them use the HUSKY_LASER_TOPIC env var as their default
```
- No changes
- No changes
- No changes

husky: 0.4.5-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.3.8-1`:
- previous version for package: `0.3.7-1`

husky: 0.3.8-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `vanguard_bms` to `0.1.0-1`:
- upstream repository: https://github.com/clearpathrobotics/vanguard_bms.git
- release repository: https://github.com/clearpath-gbp/vanguard_bms-release.git
```
* Added candump of BMS.
* Minor rework getting warnings and errors.
* Initial work.
```

vanguard_bms: 0.1.0-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `moose_robot` to `0.1.2-1`:
```
* Fix the names of the wheels to match with the format from the URDF
```
- No changes
- No changes

moose_robot: 0.1.2-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `moose_robot` to `0.1.2-1`:
```
* Fix the names of the wheels to match with the format from the URDF
```
- No changes
- No changes

moose_robot: 0.1.2-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `ridgeback_robot` to `0.2.5-1`:
```
* Use eval + find to properly load the default mag config file
* Added RIDGEBACK_MAG_CONFIG to madgwick filter and set a default optenv
* Removed env-hooks
* Contributors: Chris Iverach-Brereton, Dave Niewinski
```
- No changes
- No changes

ridgeback_robot: 0.2.5-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `ridgeback_robot` to `0.2.5-1`:
```
* Use eval + find to properly load the default mag config file
* Added RIDGEBACK_MAG_CONFIG to madgwick filter and set a default optenv
* Removed env-hooks
* Contributors: Chris Iverach-Brereton, Dave Niewinski
```
- No changes
- No changes

ridgeback_robot: 0.2.5-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_common` to `0.1.5-1`:
- previous version for package: `0.1.4-2`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
```
- No changes
- No changes
- No changes

cpr_gps_common: 0.1.5-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo` to `0.1.4-1`:
```
* [dingo_control] Fixed angular axis.
```
```
* [dingo_description] Switched description.launch to use single Dingo URDF which then determines which file should be loaded.
* Add a generic dingo.urdf.xacro (#8 <https://github.com/dingo-cpr/dingo/issues/8>)
* Add a generic dingo.urdf.xacro which will include dingo-d or dingo-o as-needed. This simplifies adding support for manipulators to the robot
* Contributors: Chris I-B, Tony Baltovski
```
- No …

dingo: 0.1.4-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo` to `0.1.5-1`:
```
* [dingo_control] Reduced acceleration limit for omnidirectional platform.
```
```
* Fix the mount links for Dingo-D and Dingo-O; -D doesn't technically have a mid_mount (#9 <https://github.com/dingo-cpr/dingo/issues/9>)
```
```
* [dingo_msgs] Removed Power msg.
```
- No changes

dingo: 0.1.5-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `ridgeback_robot` to `0.2.6-1`:
```
* [ridgeback_base] Fixed missing forward slash.
```
```
```
```
```

ridgeback_robot: 0.2.6-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `puma_motor_driver` to `0.3.0-1`:
```
* [puma_motor_driver] Improved logging.
* [puma_motor_driver] Added settings for socketcan interface.
* [puma_motor_driver] Fixes for roslint.
* [puma_motor_driver] Switched to socketcan_interface, updated configuration and added extra field handling.
* [puma_motor_driver] Removed serial gateway.
* [puma_motor_driver] Update for cpp11.
```
- No changes

puma_motor_driver: 0.3.0-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_common` to `0.1.6-1`:
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Merge branch 'master' into 'melodic'
* Contributors: Ebrahim Shahrivar, Michael Hosmar, Mike Hosmar
```
```
* Merge branch 'melodic' into 'master'
* Contributors: Ebrahim, Ebrahim Shahrivar, ebrahim
```
- No changes
```
* Contributors: Ebrahim, Ebrahim Shahrivar, ebrahim
```
- No changes

cpr_gps_common: 0.1.6-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_common` to `0.1.6-1`:
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Merge branch 'master' into 'melodic'
* Contributors: Ebrahim Shahrivar, Michael Hosmar, Mike Hosmar
```
```
* Merge branch 'melodic' into 'master'
* Contributors: Ebrahim, Ebrahim Shahrivar, ebrahim
```
- No changes
```
* Contributors: Ebrahim, Ebrahim Shahrivar, ebrahim
```
- No changes

cpr_gps_common: 0.1.6-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.12-1`:
- previous version for package: `0.1.11-1`
- No changes
- No changes
- No changes
```
* use legacy tasks by default
* Contributors: Ebrahim, Ebrahim Shahrivar, Michael Hosmar, Mike Hosmar
```
- No changes
- No changes
```
* Contributors: Ebrahim, Ebrahim Shahrivar, Mike Hosmar
```

cpr_gps_navigation: 0.1.12-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `ridgeback_robot` to `0.3.0-1`:
```
* [ridgeback_base] Added dependency.
* [ridgeback_base] Updated to use new functions from puma_motor_drivers.
* [ridgeback_base] Used ros::ok() for while condition on thread loops.
* Updates for C++11.
```
```
* [ridgeback_bringup] Increased CAN TX queue size.
```
- No changes

ridgeback_robot: 0.3.0-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `gps_mpc_navigation` to `0.1.6-1`:
- previous version for package: `0.1.4-2`
- No changes
- No changes
```
* remove cpr_nav_core_adapter
```
- No changes

gps_mpc_navigation: 0.1.6-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `gps_mpc_navigation` to `0.1.6-1`:
- No changes
- No changes
```
* remove cpr_nav_core_adapter
```
- No changes

gps_mpc_navigation: 0.1.6-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `earth_rover_piksi` to `1.8.2-1`:
- upstream repository: https://github.com/earthrover/earth_rover_piksi.git
- release repository: https://github.com/clearpath-gbp/earth_rover_piksi-release.git

earth_rover_piksi: 1.8.2-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo_robot` to `0.1.0-1`:
```
* [dingo_base] Reduced log spamming.
* [dingo_base] Fixed not using function for ros::ok().
* [dingo_base] Updated encoder count for mmp-s14 motor config.
* [dingo_base] Added motor parameters as rosparams to be loaded as a YAML which is set by an enviroment variable.
* [dingo_base] Updated I gain.
* Merge branch 'melodic-devel' of gitlab.clearpathrobotics.com:dingo/dingo_robot into melodic-devel
* Merge branch …
```

dingo_robot: 0.1.0-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.13-2`:
- previous version for package: `0.1.12-1`
```
* resolve conflicts with parallel planner branch
```
```
* resolve conflicts with parallel planner branch
```
```
* resolve conflicts with parallel planner branch
```
```
* Merge branch 'parallel_planner_fix' into 'master'
```
```
* resolve conflicts with parallel planner …
```

cpr_gps_navigation: 0.1.13-2 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `launch_delay` to `0.1.0-1`:
- upstream repository: http://gitlab.clearpathrobotics.com/research/launch_delay.git
- release repository: http://gitlab.clearpathrobotics.com/gbp/launch_delay-gbp.git
```
* Fixed README to augment job rather then replace.
* Minor changes to release this.
* README.md edited online with Bitbucket
* README.md edited online with Bitbucket
* README.md edited online with Bitbucket
* Made script executable.
* package.xml created online with Bitbucket
* CMakeLists.txt created online with Bitbucket
* launch_delay.sh created online with Bitbucket
* delayed_launch.launch created online with Bitbucket …
```

launch_delay: 0.1.0-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.14-1`:
- No changes
- No changes
```
* yaml-cpp dependency
```
- No changes
- No changes
- No changes
- No changes

cpr_gps_navigation: 0.1.14-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `launch_delay` to `0.1.0-1`:
- upstream repository: http://gitlab.clearpathrobotics.com/research/launch_delay.git
- release repository: http://gitlab.clearpathrobotics.com/gbp/launch_delay-gbp.git
```
* Fixed README to augment job rather then replace.
* Minor changes to release this.
* README.md edited online with Bitbucket
* README.md edited online with Bitbucket
* README.md edited online with Bitbucket
* Made script executable.
* package.xml created online with Bitbucket
* CMakeLists.txt created online with Bitbucket
* launch_delay.sh created online with Bitbucket
* delayed_launch.launch created online with Bitbucket …
```

launch_delay: 0.1.0-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.14-1`:
- previous version for package: `0.1.13-2`
- No changes
- No changes
```
* yaml-cpp dependency
```
- No changes
- No changes
- No changes
- No changes

cpr_gps_navigation: 0.1.14-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.14-2`:
- previous version for package: `0.1.14-1`
- No changes
- No changes
```
* yaml-cpp dependency
```
- No changes
- No changes
- No changes
- No changes

cpr_gps_navigation: 0.1.14-2 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.15-1`:
- previous version for package: `0.1.14-1`
- No changes
- No changes
- No changes
```
```
- No changes
- No changes
- No changes

cpr_gps_navigation: 0.1.15-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.15-1`:
- previous version for package: `0.1.14-2`
- No changes
- No changes
- No changes
```
```
- No changes
- No changes
- No changes

cpr_gps_navigation: 0.1.15-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo_robot` to `0.1.1-1`:
```
* Added missing test dependencies.
* Roslint fixes
* Diagnostics update (#2 <https://github.com/dingo-cpr/dingo_robot/issues/2>)
* Separate the diagnostics config into 3 separate files (common, omni, diff)
* Tidy up the wheel expectations, add the wi-fi connected topic to general
* Fix the CAN IDs of the four wheels
* Fix c&p error with left/right in the previous commit
* Correctly load the diff/omni files in the right places
* Remove the wi-fi connected …
```

dingo_robot: 0.1.1-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `puma_motor_driver` to `0.3.1-1`:
```
* [puma_motor_driver] Made socketcan_interface a depend rather than build_depend.
```
- No changes

puma_motor_driver: 0.3.1-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.16-2`:
- previous version for package: `0.1.15-1`
- No changes
- No changes
- No changes
```
* disable path shifting close to goal point
```
- No changes
- No changes
- No changes

cpr_gps_navigation: 0.1.16-2 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.16-2`:
- previous version for package: `0.1.15-1`
- No changes
- No changes
- No changes
```
* disable path shifting close to goal point
```
- No changes
- No changes
- No changes

cpr_gps_navigation: 0.1.16-2 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo` to `0.1.6-1`:
```
* [dingo_control] Increased acceleration limit for omnidirectional platform.
```
- No changes
- No changes
- No changes

dingo: 0.1.6-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo_robot` to `0.1.2-1`:
```
* [dingo_base] Fixed battery topic.
```
```
* [dingo_bringup] Made ros service start after can-udp-bridge service.
```
- No changes

dingo_robot: 0.1.2-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo` to `0.1.6-2`:
```
* [dingo_control] Increased acceleration limit for omnidirectional platform.
```
- No changes
- No changes
- No changes

dingo: 0.1.6-2 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_common` to `0.1.7-1`:
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Merge branch 'tolerance_from_action' into 'master'
tolerance from action for isGoalReached
See merge request gps-navigation/cpr_gps_common!8
* tolerance from action for isGoalReached
```
- No changes

cpr_gps_common: 0.1.7-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_common` to `0.1.7-1`:
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Merge branch 'tolerance_from_action' into 'master'
tolerance from action for isGoalReached
See merge request gps-navigation/cpr_gps_common!8
* tolerance from action for isGoalReached
```
- No changes

cpr_gps_common: 0.1.7-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.17-1`:
- previous version for package: `0.1.16-2`
```
* Merge branch 'nextviapoint_fix' into 'master'
* created node to converted data in sensor NED frame to ENU frame
* Contributors: Ebrahim Shahrivar, Jose Mastrangelo
```
- No changes
- No changes
```
* Merge branch 'nextviapoint_fix' into 'master'
Nextviapoint fix
See merge request gps-navigation/cpr_gps_navigation!65
* Update mission_server.cpp
* remove unsued param
* fix racing between parallel planner and makePlan …
```

cpr_gps_navigation: 0.1.17-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.17-1`:
- previous version for package: `0.1.16-2`
```
* Merge branch 'nextviapoint_fix' into 'master'
* created node to converted data in sensor NED frame to ENU frame
* Contributors: Ebrahim Shahrivar, Jose Mastrangelo
```
- No changes
- No changes
```
* Merge branch 'nextviapoint_fix' into 'master'
Nextviapoint fix
See merge request gps-navigation/cpr_gps_navigation!65
* Update mission_server.cpp
* remove unsued param
* fix racing between parallel planner and makePlan …
```

cpr_gps_navigation: 0.1.17-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `gps_mpc_navigation` to `0.1.7-1`:
- No changes
```
* Merge branch 'tolerance_from_action' into 'master'
```
- No changes
- No changes

gps_mpc_navigation: 0.1.7-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `gps_mpc_navigation` to `0.1.7-1`:
- No changes
```
* Merge branch 'tolerance_from_action' into 'master'
```
- No changes
- No changes

gps_mpc_navigation: 0.1.7-1 in 'melodic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `serial` to `1.2.1-1`:
- upstream repository: https://github.com/wjwwood/serial.git
```
* Removed the use of a C++11 feature for compatibility with older browsers.
* Fixed an issue with cross compiling with mingw on Windows.
* Restructured Visual Studio project layout.
* Added include of ``#include <AvailabilityMacros.h>`` on OS X (listing of ports).
* Fixed MXE for the listing of ports on Windows.
* Now closes file device if ``reconfigureDevice`` fails (Windows).
* Added the MARK/SPACE parity bit option, also made it optional.
Adding the enumeration values for …
```

serial: 1.2.1-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `um7` to `0.0.6-1`:
- upstream repository: https://github.com/ros-drivers/um7
- release repository: https://github.com/ros-drivers-gbp/um7-release.git
```
* Fix error of mag topic not publish
* Contributors: Nicolas SIMON
```

um7: 0.0.6-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `um6` to `1.1.3-1`:
- upstream repository: https://github.com/ros-drivers/um6.git
- release repository: https://github.com/ros-drivers-gbp/um6-release.git
```
* Disabled using MagneticField message by default.
* Updated to be able to use MagneticField message.
* Updated TravisCI to use Industrial CI for Kinetic and Melodic.
```

um6: 1.1.3-1 in 'noetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `ros_mscl` to `1.0.1-1`:
```
* Move the libmscl dependency to a normal depend, as it's required for both building & running
* Remove the examples folder, move the ros_mscl contents into the root of the repo. Update the package data to remove the broken dependency (until we can get it fixed). Update authors & maintainer for this fork.
* Fixed bug preventing device report service from working on a GQ7.
* Added support for raw binary file output and RTK status message (see changelog for …
```

ros_mscl: 1.0.1-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `ros_mscl` to `1.0.1-1`:
```
* Move the libmscl dependency to a normal depend, as it's required for both building & running
* Remove the examples folder, move the ros_mscl contents into the root of the repo. Update the package data to remove the broken dependency (until we can get it fixed). Update authors & maintainer for this fork.
* Fixed bug preventing device report service from working on a GQ7.
* Added support for raw binary file output and RTK status message (see changelog for …
```

ros_mscl: 1.0.1-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `ros_mscl` to `1.1.2-1`:
```
* Move the libmscl dependency to a normal depend, as it's required for both building & running
* Remove the examples folder, move the ros_mscl contents into the root of the repo. Update the package data to remove the broken dependency (until we can get it fixed). Update authors & maintainer for this fork.
* Fixed bug preventing device report service from working on a GQ7.
* Added support for raw binary file output and RTK status message (see changelog for …
```

ros_mscl: 1.1.2-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `ros_mscl` to `1.1.2-1`:
```
* Move the libmscl dependency to a normal depend, as it's required for both building & running
* Remove the examples folder, move the ros_mscl contents into the root of the repo. Update the package data to remove the broken dependency (until we can get it fixed). Update authors & maintainer for this fork.
* Fixed bug preventing device report service from working on a GQ7.
* Added support for raw binary file output and RTK status message (see changelog for …
```

ros_mscl: 1.1.2-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `ros_mscl` to `1.1.3-1`:
- previous version for package: `1.1.2-1`
```
* Fix missing dependencies that are breaking the buildfarm
```

ros_mscl: 1.1.3-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `ros_mscl` to `1.1.3-1`:
- previous version for package: `1.1.2-1`
```
* Fix missing dependencies that are breaking the buildfarm
```

ros_mscl: 1.1.3-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `rosserial_leonardo_cmake` to `0.1.4-0`:
- upstream repository: https://github.com/clearpathrobotics/rosserial_leonardo_cmake.git
- release repository: https://github.com/clearpath-gbp/rosserial_leonardo_cmake-release.git
```
* Updated arduino link from google code
```

rosserial_leonardo_cmake: 0.1.4-0 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `rosserial_leonardo_cmake` to `0.1.4-1`:
- upstream repository: https://github.com/clearpathrobotics/rosserial_leonardo_cmake.git
- release repository: https://github.com/clearpath-gbp/rosserial_leonardo_cmake-release.git
```
* Updated arduino link from google code
```

rosserial_leonardo_cmake: 0.1.4-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `heron_firmware` to `0.3.2-1`:
- upstream repository: http://gitlab.clearpathrobotics.com/research/heron_firmware.git
- release repository: http://gitlab.clearpathrobotics.com/gbp/heron_firmware-gbp.git
```
* Put contents back in the upload script, add rosserial_leondardo_cmake to the run_depends
* Merge branch 'power_calc_fix' into 'indigo-devel'
Fixed calculation from watt-seconds to watt-hours
See merge request research/heron_firmware!1
* Fixed calculation from watt-seconds to watt-hours
* Added the ability to disable the lights via topic.
* Contributors: Chris Iverach-Brereton, Guy Stoppi, Tony Baltovski
```
- No changes

heron_firmware: 0.3.2-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `heron_firmware` to `0.3.2-1`:
- upstream repository: http://gitlab.clearpathrobotics.com/research/heron_firmware.git
- release repository: http://gitlab.clearpathrobotics.com/gbp/heron_firmware-gbp.git
```
* Put contents back in the upload script, add rosserial_leondardo_cmake to the run_depends
* Merge branch 'power_calc_fix' into 'indigo-devel'
Fixed calculation from watt-seconds to watt-hours
See merge request research/heron_firmware!1
* Fixed calculation from watt-seconds to watt-hours
* Added the ability to disable the lights via topic.
* Contributors: Chris Iverach-Brereton, Guy Stoppi, Tony Baltovski
```
- No changes

heron_firmware: 0.3.2-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `heron` to `0.3.4-1`:
- No changes
```
* Fix disconnected thruster joints (#12 <https://github.com/heron/heron/issues/12>)
* Use a fixed joint for the thrusters unless we're in simulation; these joints are purely decorative outside gazebo, and the tf is not published except in simulation anyway
* Remove superfluous .py; they were a copy & paste error
* Merge pull request #11 <https://github.com/heron/heron/issues/11> from heron/no-um6
Rename UM6 env vars to be generic IMU
* Rename the UM6 IMU env vars to …
```

heron: 0.3.4-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `heron_simulator` to `0.3.1-1`:
```
* Merge pull request #11 <https://github.com/heron/heron_simulator/issues/11> from heron/thruster-fix
Enable thruster joints in simulation
* Enable the simulation argument so the thrusters are mobile & allow the robot to move
* Merge pull request #10 <https://github.com/heron/heron_simulator/issues/10> from heron/namespace-fix
Fix namespace preventing the EKF node from working
* Use remap instead of rosparams to set the topics for the mag topic …
```

heron_simulator: 0.3.1-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `heron` to `0.3.4-1`:
- No changes
```
* Fix disconnected thruster joints (#12 <https://github.com/heron/heron/issues/12>)
* Use a fixed joint for the thrusters unless we're in simulation; these joints are purely decorative outside gazebo, and the tf is not published except in simulation anyway
* Remove superfluous .py; they were a copy & paste error
* Merge pull request #11 <https://github.com/heron/heron/issues/11> from heron/no-um6
Rename UM6 env vars to be generic IMU
* Rename the UM6 IMU env vars to …
```

heron: 0.3.4-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `heron_simulator` to `0.3.1-1`:
```
* Merge pull request #11 <https://github.com/heron/heron_simulator/issues/11> from heron/thruster-fix
Enable thruster joints in simulation
* Enable the simulation argument so the thrusters are mobile & allow the robot to move
* Merge pull request #10 <https://github.com/heron/heron_simulator/issues/10> from heron/namespace-fix
Fix namespace preventing the EKF node from working
* Use remap instead of rosparams to set the topics for the mag topic …
```

heron_simulator: 0.3.1-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `heron_controller` to `0.1.0-1`:
- upstream repository: http://gitlab.clearpathrobotics.com/research/heron_controller.git
- release repository: http://gitlab.clearpathrobotics.com/gbp/heron_controller-gbp.git
```
* Switched from updatePid to computeCommand as it is deprecated control_toolbox.
```

heron_controller: 0.1.0-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `heron_controller` to `0.1.0-1`:
- upstream repository: http://gitlab.clearpathrobotics.com/research/heron_controller.git
- release repository: http://gitlab.clearpathrobotics.com/gbp/heron_controller-gbp.git
```
* Switched from updatePid to computeCommand as it is deprecated control_toolbox.
```

heron_controller: 0.1.0-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `heron_robot` to `0.1.6-1`:
```
* Replace now-defunct UM6 as default, use CV5-25 instead, as-per RPSW-661 (#10 <https://github.com/heron/heron_robot/issues/10>)
* Remove all references to the now-defunct UM6, as-per RPSW-661
* Add the Microstrain CV5 launch configuration as the new default. We're going to move forward and publish the driver off our own build farm, so depending on it shouldn't cause long-term issues (though it won't work right now)
* Remove the notes to check topics & devices; …
```

heron_robot: 0.1.6-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `heron_robot` to `0.1.6-1`:
```
* Replace now-defunct UM6 as default, use CV5-25 instead, as-per RPSW-661 (#10 <https://github.com/heron/heron_robot/issues/10>)
* Remove all references to the now-defunct UM6, as-per RPSW-661
* Add the Microstrain CV5 launch configuration as the new default. We're going to move forward and publish the driver off our own build farm, so depending on it shouldn't cause long-term issues (though it won't work right now)
* Remove the notes to check topics & devices; …
```

heron_robot: 0.1.6-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo_firmware_components` to `2.9.7-1`:
```
* Change python-tftpy dep.
```

dingo_firmware_components: 2.9.7-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo_firmware` to `0.1.0-1`:
```
* Made roslint a test dep.
* Reset package version.
* Switched to dingo_firmware_components.
* Added user input & outputs and respective publisher & subscriber.  Switched from dingo_msg/Power to std_msgs/Bool.  Added some more consts.
* Averaging system battery level over 30 seconds
* Updated README.md
* Cleanup.
* Synched up all batteries for publishing the battery status message
Batteries can now be hot swapped without blocking the …
```

dingo_firmware: 0.1.0-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `ros_mscl` to `1.1.4-1`:
- previous version for package: `1.1.3-1`
```
* Add postinst and postrm scripts to symlink libmscl.so when this package is built as a .deb
* Add troubleshooting instructions to the README
```

ros_mscl: 1.1.4-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `ros_mscl` to `1.1.4-1`:
- previous version for package: `1.1.3-1`
```
* Add postinst and postrm scripts to symlink libmscl.so when this package is built as a .deb
* Add troubleshooting instructions to the README
```

ros_mscl: 1.1.4-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `heron_simulator` to `0.3.2-1`:
```
* Bumped CMake version to avoid author warning.
* Add the config, launch, and worlds folders to the install target
```
```
* Bumped CMake version to avoid author warning.
```

heron_simulator: 0.3.2-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `heron_simulator` to `0.3.2-1`:
```
* Bumped CMake version to avoid author warning.
* Add the config, launch, and worlds folders to the install target
```
```
* Bumped CMake version to avoid author warning.
```

heron_simulator: 0.3.2-1 in 'melodic/distribution.yaml' [bloom]

---

foxy/distribution.yaml

Increasing version of package(s) in repository `teleop_twist_joy` to `2.4.1-1`:
- upstream repository: https://github.com/ros2/teleop_twist_joy.git
- release repository: https://github.com/ros2-gbp/teleop_twist_joy-release.git
```
* Add parameter to enable/disable requiring the enable button to be held for motion (#21 <https://github.com/ros2/teleop_twist_joy/issues/21>)
* Contributors: Chris Lalancette, kgibsonjca
```

teleop_twist_joy: 2.4.1-1 in 'foxy/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_common_msgs` to `0.0.1-1`:
- upstream repository: git@gitlab.clearpathrobotics.com:Boxer/cpr_common_msgs.git
- release repository: http://gitlab.clearpathrobotics.com/boxer_gbp/cpr_common_msgs.git
```
```
```
```
```
```
```
```

cpr_common_msgs: 0.0.1-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo_firmware_components` to `2.9.8-1`:
- previous version for package: `2.9.7-1`
```
* Renamed folder.
```

dingo_firmware_components: 2.9.8-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `microhard_snmp` to `0.0.1-1`:
```
* Initial Release
* Contributors: Michael Hosmar, Shrey Kavi
```

microhard_snmp: 0.0.1-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo_firmware_components` to `2.9.9-1`:
- previous version for package: `2.9.8-1`
```
* More dingo renaming.
```

dingo_firmware_components: 2.9.9-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo_firmware` to `0.1.1-1`:
```
* Additional renaming to dingo_firmware_components.
```

dingo_firmware: 0.1.1-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo_firmware` to `0.1.2-1`:
```
* Change cmake path.
```

dingo_firmware: 0.1.2-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo_firmware_components` to `2.9.10-1`:
- previous version for package: `2.9.9-1`
```
* Updated cmake for components.
```

dingo_firmware_components: 2.9.10-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo_firmware` to `0.1.3-1`:
```
* More changes for dingo_firmware_components.
```

dingo_firmware: 0.1.3-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo_firmware_components` to `2.9.11-1`:
- previous version for package: `2.9.10-1`
```
* Renamed folder.
```

dingo_firmware_components: 2.9.11-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `heron_desktop` to `0.0.3-1`:
- upstream repository: https://github.com/heron/heron_desktop.git
- release repository: https://github.com/clearpath-gbp/heron_desktop-release.git
- No changes
```
* Merge pull request #1 <https://github.com/heron/heron_desktop/issues/1> from ssubramaniam-cpr/kinetic-devel
Changed interactive marker topic update
* Changed interative marker topic update
* Contributors: Shreya Subramaniam, Tony Baltovski
```

heron_desktop: 0.0.3-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `heron_desktop` to `0.0.3-2`:
- upstream repository: https://github.com/heron/heron_desktop.git
- release repository: https://github.com/clearpath-gbp/heron_desktop-release.git
- No changes
```
* Merge pull request #1 <https://github.com/heron/heron_desktop/issues/1> from ssubramaniam-cpr/kinetic-devel
Changed interactive marker topic update
* Changed interative marker topic update
* Contributors: Shreya Subramaniam, Tony Baltovski
```

heron_desktop: 0.0.3-2 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo` to `0.1.7-1`:
- previous version for package: `0.1.6-2`
- No changes
```
* Add env var support for VLP-16 (#10 <https://github.com/dingo-cpr/dingo/issues/10>)
* Add support for the VLP16 as a standard laser sensor on this platform
* Add vlp16 to the comment block explaining supported laser scanners
* Add the 3D and secondary 2D lidars
```
- No changes
- No changes

dingo: 0.1.7-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo_robot` to `0.1.3-1`:
- No changes
```
* Move the VLP16 to a new DINGO_LASER_3D family of vars, add DINGO_LASER_SECONDARY
* Add vlp16 to the commend block explaining allowed values
* Add support for the VLP16 as a standard laser sensor for Dingo
```
- No changes

dingo_robot: 0.1.3-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.7.3-1`:
- previous version for package: `0.7.2-1`
- No changes
```
* Add VLP16 support, refactor main/secondary laser envar support (#79)
```
- No changes
- No changes

jackal: 0.7.3-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `jackal_robot` to `0.6.1-1`:
- previous version for package: `0.6.0-1`
```
* Use eval to find the mag config. This should fix a bug when jackal is installed to ros.d
* Set default for optenv JACKAL_MAG_CONFIG
* Removed env-hooks
* Contributors: Chris Iverach-Brereton, Dave Niewinski
```
```
* Add VLP16 support, refactor main/secondary laser envar support (#27 <https://github.com/jackal/jackal_robot/issues/27>)
* Add groups for the front/rear fender lasers' nodes
* Revert the front/rear laser frames to "front_laser" and "rear_laser" …
```

jackal_robot: 0.6.1-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `warthog` to `0.1.3-1`:
```
* Bumped CMake version to avoid author warning.
* Change the enable & enable-turbo buttons to 4 and 5 to match with all the other platforms
* Add another optenv to allow setting the Warthog's joy device
* Config extras (#12 <https://github.com/warthog-cpr/warthog/issues/12>)
* Add a WARTHOG_CONFIG_EXTRAS environment variable for the same purpose as the equivalent in Husky.
* Contributors: Chris I-B, Chris Iverach-Brereton, Tony Baltovski
```
```
* Bumped CMake version …
```

warthog: 0.1.3-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.4.6-1`:
- previous version for package: `0.4.5-1`
- No changes
```
* Add VLP16, secondary LMS1xx support (#164 <https://github.com/husky/husky/issues/164>)
* Minimal refactor to add VLP16 + secondary LMS1xx support. Update defaults for the laser_enabled and realsense_enabled args to refer to the underlying envars to improve consistency when launching simulations. Modify the sensor bar to allow it to be positioned in the center by default, but with configurable xyz and rpy offsets
* Add the new run dependencies
* Remove the prefix's …
```

husky: 0.4.6-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `moose` to `0.1.1-1`:
- upstream repository: https://github.com/moose-cpr/moose.git
- release repository: https://github.com/clearpath-gbp/moose-release.git
```
* Expose MOOSE_JOY_DEV and MOOSE_JOY_TELEOP environment variables.  Enable the joy node's messages to be received by twist_mux with the same priority as Warthog.
```
```
* Add the legacy mode NS flag to the gazebo file. This gets rid of a warning when launching gazebo
```
- No changes

moose: 0.1.1-1 in 'kinetic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `heron_simulator` to `0.3.3-1`:
```
* Pass the config arg to the heron_description package correctly
```
- No changes

heron_simulator: 0.3.3-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `heron_simulator` to `0.3.3-1`:
```
* Pass the config arg to the heron_description package correctly
```
- No changes

heron_simulator: 0.3.3-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.19-2`:
- previous version for package: `0.1.17-1`
- No changes
- No changes
```
* fix package name
```
- No changes
- No changes
- No changes
- No changes

cpr_gps_navigation: 0.1.19-2 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.19-6`:
- previous version for package: `0.1.17-1`
- No changes
- No changes
```
* fix package name
```
- No changes
- No changes
- No changes
- No changes

cpr_gps_navigation: 0.1.19-6 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.7.4-1`:
- bloom version: `0.10.2`
- previous version for package: `0.7.3-1`
```
* Bumped CMake version to avoid author warning.
* Add the JACKAL_JOY_DEVICE envar to optionally override the joy device more easily.
```
```
* Bumped CMake version to avoid author warning.
```
```
* Bumped CMake version to avoid author warning.
```
```
* Bumped CMake version to avoid author warning.
```

jackal: 0.7.4-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.4.7-1`:
- bloom version: `0.10.2`
- previous version for package: `0.4.6-1`
- No changes
- No changes
- No changes
```
* Add HUSKY_{FRONT|REAR}_BUMPER envars we can use to completely turn off the front & rear bumpers.  This is requested to make integration of the wireless charging docks easier
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

husky: 0.4.7-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.7.5-1`:
- bloom version: `0.10.2`
- previous version for package: `0.7.4-1`
- No changes
```
* Add the origin block to the fender UST-10 macros; otherwise enabling them crashes
```
- No changes
- No changes

jackal: 0.7.5-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.4.8-1`:
- previous version for package: `0.4.7-1`
- No changes
```
* Add a missing colon to the install script
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

husky: 0.4.8-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `occupancy_grid_utils` to `0.0.11-1`:
- upstream repository: https://github.com/clearpathrobotics/occupancy_grid_utils
- release repository: https://github.com/clearpath-gbp/occupancy_grid_utils-release.git
```
* Drop signals boost component.
```

occupancy_grid_utils: 0.0.11-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `occupancy_grid_utils` to `0.0.11-1`:
- upstream repository: https://github.com/clearpathrobotics/occupancy_grid_utils
- release repository: https://github.com/clearpath-gbp/occupancy_grid_utils-release.git
```
* Drop signals boost component.
```

occupancy_grid_utils: 0.0.11-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `image_undistort` to `0.0.1-1`:
- upstream repository: https://github.com/clearpathrobotics/image_undistort.git
- release repository: https://github.com/clearpath-gbp/image_undistort-release.git
```
* Initial tagged release.
* Contributors: Dominik Schindler, Helen Oleynikova, Raghav Khanna, Tracey Spicer, Vaibhav Kumar Mehta, Zachary Taylor
```

image_undistort: 0.0.1-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `image_undistort` to `0.0.1-2`:
- upstream repository: https://github.com/clearpathrobotics/image_undistort.git
- release repository: https://github.com/clearpath-gbp/image_undistort-release.git
```
* Initial tagged release.
* Contributors: Dominik Schindler, Helen Oleynikova, Raghav Khanna, Tracey Spicer, Vaibhav Kumar Mehta, Zachary Taylor
```

image_undistort: 0.0.1-2 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_docking` to `0.0.4-1`:
- upstream repository: git@gitlab.clearpathrobotics.com:gps-navigation/cpr_docking.git
- release repository: git@gitlab.clearpathrobotics.com:gbp/cpr_docking-gbp.git
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

cpr_docking: 0.0.4-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_docking` to `0.0.4-4`:
- release repository: git@gitlab.clearpathrobotics.com:gbp/cpr_docking-gbp.git
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

cpr_docking: 0.0.4-4 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_docking` to `0.0.5-1`:
- previous version for package: `0.0.4-4`
- No changes
```
* roslint fix
```
```
* roslint fix
```
```
* roslint fix
```
- No changes
```
* roslint fix
```
- No changes
```
* roslint fix
```
```
* roslint fix
```
```
* roslint fix
```
- No …

cpr_docking: 0.0.5-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_docking` to `0.0.6-1`:
- No changes
- No changes
- No changes
```
* dependency fix
```
- No changes
- No changes
- No changes
- No changes
- No changes
```
* dependency fix
```
- No changes
- No changes
- No changes
- No changes
- No changes

cpr_docking: 0.0.6-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `gps_mpc_navigation` to `0.1.8-1`:
- No changes
```
```
- No changes
- No changes

gps_mpc_navigation: 0.1.8-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `gps_mpc_navigation` to `0.1.8-1`:
- No changes
```
```
- No changes
- No changes

gps_mpc_navigation: 0.1.8-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_common_core` to `0.1.0-1`:
- upstream repository: https://github.com/clearpathrobotics/cpr_common_core.git
- release repository: https://github.com/clearpath-gbp/cpr_common_core-release.git
```
* [cpr_common_core_msgs] Added messages.
```

cpr_common_core: 0.1.0-1 in 'melodic/distribution.yaml' [bloom]

---

kinetic/distribution.yaml

Increasing version of package(s) in repository `ros_mscl` to `1.2.3-1`:
- previous version for package: `1.1.4-1`
```
* Merge the recent upstream changes so we're compatible with MSCL 61.1.6.
* Keep the old version numbers, re-add our postinst and postrm scripts, but otherwise keep the structure of the repo the same as upstream; this should make it easier to update our repo down the road.
* Driver modified to support MSCL version 61.1.6
* Fixed missing boolean set for RTK status message publishing
* Merge pull request #34 …
```

ros_mscl: 1.2.3-1 in 'kinetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `ros_mscl` to `1.2.3-1`:
- previous version for package: `1.1.4-1`
```
* Merge the recent upstream changes so we're compatible with MSCL 61.1.6.
* Keep the old version numbers, re-add our postinst and postrm scripts, but otherwise keep the structure of the repo the same as upstream; this should make it easier to update our repo down the road.
* Driver modified to support MSCL version 61.1.6
* Fixed missing boolean set for RTK status message publishing
* Merge pull request #34 …
```

ros_mscl: 1.2.3-1 in 'melodic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `ros_mscl` to `1.2.3-1`:
```
* Merge the recent upstream changes so we're compatible with MSCL 61.1.6.
* Keep the old version numbers, re-add our postinst and postrm scripts, but otherwise keep the structure of the repo the same as upstream; this should make it easier to update our repo down the road.
* Driver modified to support MSCL version 61.1.6
* Fixed missing boolean set for RTK status message publishing
* Merge pull request #34 <https://github.com/clearpathrobotics/ros_mscl/issues/34> …
```

ros_mscl: 1.2.3-1 in 'noetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `ros_mscl` to `1.2.4-1`:
- previous version for package: `1.2.3-1`
- No changes
```
* Add an argument to specify the frame_id, instead of always using "sensor"
```

ros_mscl: 1.2.4-1 in 'melodic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `ros_mscl` to `1.2.4-1`:
- previous version for package: `1.2.3-1`
- No changes
```
* Add an argument to specify the frame_id, instead of always using "sensor"
```

ros_mscl: 1.2.4-1 in 'noetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo_firmware` to `0.1.4-1`:
```
* Installed missing script.
```

dingo_firmware: 0.1.4-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo_firmware` to `0.1.5-1`:
```
* Disabled tests.
```

dingo_firmware: 0.1.5-1 in 'melodic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `ros_mscl` to `1.2.5-1`:
- previous version for package: `1.2.4-1`
- No changes
```
* Merge branch 'master' of github.com:LORD-MicroStrain/ROS-MSCL into upstream-sync
* Merge pull request #49 <https://github.com/clearpathrobotics/ros_mscl/issues/49> from civerachb-cpr/rosdep-fix
Add tf2_geometry_msgs as a dependency
* Add tf2_geometry_msgs as a dependency
* Merge pull request #48 <https://github.com/clearpathrobotics/ros_mscl/issues/48> from civerachb-cpr/master
Make frame IDs configurable
* Contributors: Chris Iverach-Brereton, …
```

ros_mscl: 1.2.5-1 in 'noetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `ros_mscl` to `1.2.5-1`:
- previous version for package: `1.2.4-1`
- No changes
```
* Merge branch 'master' of github.com:LORD-MicroStrain/ROS-MSCL into upstream-sync
* Merge pull request #49 <https://github.com/clearpathrobotics/ros_mscl/issues/49> from civerachb-cpr/rosdep-fix
Add tf2_geometry_msgs as a dependency
* Add tf2_geometry_msgs as a dependency
* Merge pull request #48 <https://github.com/clearpathrobotics/ros_mscl/issues/48> from civerachb-cpr/master
Make frame IDs configurable
* Contributors: Chris Iverach-Brereton, …
```

ros_mscl: 1.2.5-1 in 'melodic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `jackal_firmware` to `0.4.3-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/research/jackal_firmware.git
```
* Used integer for time rather then float.
```

jackal_firmware: 0.4.3-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `ros_mscl` to `1.2.6-1`:
- previous version for package: `1.2.5-1`
- No changes
```
* Expose the use_enu_frame parameter as an arg
```

ros_mscl: 1.2.6-1 in 'noetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `ros_mscl` to `1.2.6-1`:
- previous version for package: `1.2.5-1`
- No changes
```
* Expose the use_enu_frame parameter as an arg
```

ros_mscl: 1.2.6-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `lockmount_description` to `0.0.1-1`:
- upstream repository: https://github.com/clearpathrobotics/lockmount_description.git
- release repository: https://github.com/clearpath-gbp/lockmount_description-release.git
```
```

lockmount_description: 0.0.1-1 in 'melodic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `jackal_desktop` to `0.4.0-1`:
- upstream repository: https://github.com/jackal/jackal_desktop.git
- release repository: https://github.com/clearpath-gbp/jackal_desktop-release.git
- No changes
```
* [jackal_viz] Removed joint_state_publisher since joint_state_publisher_gui is generating the same data.
* Fix a deprecation warning with the joint state publisher gui
```

jackal_desktop: 0.4.0-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `jackal_simulator` to `0.4.0-1`:
- upstream repository: https://github.com/jackal/jackal_simulator
- release repository: https://github.com/clearpath-gbp/jackal_simulator-release.git
```
* Enable the joystick by default. Add yaw to the spawn_jackal launch file
* Add an additional parameter to enable teleop in the simulations
* Fix an accidental deletion of a closing tag
* Move the jackal-spawning into a separate launch file for compatibility with the new sim environments.  Add additional sim worlds: completely empty (useful for replaying bag files w/o risk of obstacle collisions!) and HRTAC since the world was in the repo, but not …
```

jackal_simulator: 0.4.0-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `jackal_robot` to `0.7.0-1`:
```
* Merge development changes from live hardware test into noetic-devel
* Sort the jackal_base changelog version tags
* Fix the scipy dependency so it resolves properly. Minor code cleanup
* Contributors: Chris I-B, Chris Iverach-Brereton
```
```
* Merge development changes from live hardware test into noetic-devel
* Fix the name of the VLP16 launch file that gets included in accessories
* Fix a c&p error where and arg was referenced before it was actually …
```

jackal_robot: 0.7.0-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.8.0-1`:
```
* Merge branch 'noetic-devel-bkup' into noetic-devel
* Fix the link_name parameter for the interactive marker server; the default for the package includes a leading '/', which prevents the markers from working on Noetic.  We can revert this if/when the default for interactive_marker_twist_server is modified.
```
- No changes
- No changes
- No changes
- No changes

jackal: 0.8.0-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `lockmount_description` to `0.0.1-1`:
- upstream repository: https://github.com/clearpathrobotics/lockmount_description.git
- release repository: https://github.com/clearpath-gbp/lockmount_description-release.git
```
```

lockmount_description: 0.0.1-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `lockmount_description` to `0.0.2-1`:
- upstream repository: https://github.com/clearpathrobotics/lockmount_description.git
- release repository: https://github.com/clearpath-gbp/lockmount_description-release.git
```
* Remove a copy & paste error in the cmake file that's breaking the install
```

lockmount_description: 0.0.2-1 in 'noetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `lockmount_description` to `0.0.2-1`:
- upstream repository: https://github.com/clearpathrobotics/lockmount_description.git
- release repository: https://github.com/clearpath-gbp/lockmount_description-release.git
```
* Remove a copy & paste error in the cmake file that's breaking the install
```

lockmount_description: 0.0.2-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `jackal_robot` to `0.6.2-1`:
- previous version for package: `0.6.1-1`
- No changes
```
* Fix the name of the VLP16 launch file that gets included in accessories
* Fix a c&p error where and arg was referenced before it was actually assigned
```
- No changes

jackal_robot: 0.6.2-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `ros_mscl` to `1.2.7-1`:
- previous version for package: `1.2.6-1`
```
* Explicitly name the mscl_msgs package
```
- No changes

ros_mscl: 1.2.7-1 in 'melodic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `ros_mscl` to `1.2.7-1`:
- previous version for package: `1.2.6-1`
```
* Explicitly name the mscl_msgs package
```
- No changes

ros_mscl: 1.2.7-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `ros_mscl` to `1.2.7-2`:
- previous version for package: `1.2.7-1`
```
* Explicitly name the mscl_msgs package
```
- No changes

ros_mscl: 1.2.7-2 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `ros_mscl` to `1.2.7-3`:
- release repository: git@github.com:clearpath-gbp/ros_mscl-release.git
- previous version for package: `1.2.7-2`
```
* Explicitly name the mscl_msgs package
```
- No changes

ros_mscl: 1.2.7-3 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `jackal_desktop` to `0.4.0-2`:
- upstream repository: https://github.com/jackal/jackal_desktop.git
- release repository: https://github.com/clearpath-gbp/jackal_desktop-release.git
- No changes
```
* [jackal_viz] Removed joint_state_publisher since joint_state_publisher_gui is generating the same data.
* Fix a deprecation warning with the joint state publisher gui
```

jackal_desktop: 0.4.0-2 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `jackal_simulator` to `0.4.0-2`:
- upstream repository: https://github.com/jackal/jackal_simulator
- release repository: https://github.com/clearpath-gbp/jackal_simulator-release.git
```
* Enable the joystick by default. Add yaw to the spawn_jackal launch file
* Add an additional parameter to enable teleop in the simulations
* Fix an accidental deletion of a closing tag
* Move the jackal-spawning into a separate launch file for compatibility with the new sim environments.  Add additional sim worlds: completely empty (useful for replaying bag files w/o risk of obstacle collisions!) and HRTAC since the world was in the repo, but not …
```

jackal_simulator: 0.4.0-2 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `jackal_robot` to `0.7.0-2`:
- previous version for package: `0.7.0-1`
```
* Merge development changes from live hardware test into noetic-devel
* Sort the jackal_base changelog version tags
* Fix the scipy dependency so it resolves properly. Minor code cleanup
* Contributors: Chris I-B, Chris Iverach-Brereton
```
```
* Merge development changes from live hardware test into noetic-devel
* Fix the name of the VLP16 launch file that gets included in accessories
* Fix a c&p error where and arg was referenced before it was actually …
```

jackal_robot: 0.7.0-2 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `firmware_components` to `2.9.5-1`:
- upstream repository: http://gitlab.clearpathrobotics.com/research/firmware_components.git
- release repository: git@gitlab.clearpathrobotics.com:gbp/firmware_components-gbp.git
- No changes

firmware_components: 2.9.5-1 in 'noetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo` to `0.1.8-1`:
```
* Update the axes to match the latest DS4DRV update; the left stick is now axes 3/4.
```
- No changes
- No changes
- No changes

dingo: 0.1.8-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `ros_mscl` to `1.2.8-1`:
- previous version for package: `1.2.7-1`
- No changes
```
* Make the libmscl a normal depend, not just a build_depend.
* Use [ ... ] instead of [[ ... ]] in the postinst and postrm scripts
```

ros_mscl: 1.2.8-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `heron_robot` to `0.1.7-1`:
```
* Fix bugs related to the switch to CV5 (#11 <https://github.com/heron/heron_robot/issues/11>)
* Use relays instead of remap; remap doesn't work in an include.  Add additional necessary dependencies
* Set the IMU to operate in ENU mode instead of the default NED
* Rename the microstrain nodes to use "imu" instead of "cv5" to be more universal
```
- No changes
- No changes
```
* Fix bugs related to the switch to CV5 (#11 …
```

heron_robot: 0.1.7-1 in 'melodic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `jackal_firmware` to `0.4.3-3`:
- previous version for package: `0.4.3-2`
```
* Used integer for time rather then float.
```

jackal_firmware: 0.4.3-3 in 'noetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_tasks` to `0.0.2-1`:
- upstream repository: http://gitlab.clearpathrobotics.com/gps-navigation/cpr_gps_tasks.git
- release repository: http://gitlab.clearpathrobotics.com/gbp/cpr_gps_tasks-gbp.git
- No changes
- No changes
- No changes

cpr_gps_tasks: 0.0.2-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_common` to `0.1.8-1`:
```
```
- No changes
```
* Merge branch 'fix/autonomy_metrics' into 'master'
```
- No changes
- No changes
- No changes
```
* Merge branch 'autonomy_task' into 'master'
```
- No changes
- No changes
- No changes
- No changes

cpr_gps_common: 0.1.8-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.20-1`:
- previous version for package: `0.1.19-6`
```
* merge path planning constraints
```
```
* Merge branch 'feature/lidar_odometry' into 'master'
```
```
* merge path planning constraints
```
- No changes
```
* Contributors: Ebrahim Shahrivar, José Mastrangelo, Mike Hosmar
```
- No changes
- No changes

cpr_gps_navigation: 0.1.20-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `gps_mpc_navigation` to `0.1.9-1`:
- No changes
```
```
- No changes
- No changes

gps_mpc_navigation: 0.1.9-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_tasks` to `0.0.3-1`:
- upstream repository: http://gitlab.clearpathrobotics.com/gps-navigation/cpr_gps_tasks.git
- release repository: http://gitlab.clearpathrobotics.com/gbp/cpr_gps_tasks-gbp.git
```
* release changes
```
```
* release changes
```
```
* release changes
```

cpr_gps_tasks: 0.0.3-1 in 'melodic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `jackal_firmware` to `0.4.3-4`:
- previous version for package: `0.4.3-3`
```
* Used integer for time rather then float.
```

jackal_firmware: 0.4.3-4 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `jackal_firmware` to `0.4.5-1`:
- previous version for package: `0.4.3-4`
- No changes

jackal_firmware: 0.4.5-1 in 'noetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_docking` to `0.0.8-1`:
- previous version for package: `0.0.7-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Merge branch 'log_cleanup' into 'master'
```
- No changes
- No changes
```
* Merge branch 'devel' into 'master
```
- No changes
- No changes
- No changes
- No changes
```
* Merge branch 'log_cleanup' into 'master'
```

cpr_docking: 0.0.8-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_common` to `0.1.9-1`:
- No changes
- No changes
- No changes
- No changes
- No changes
```
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

cpr_gps_common: 0.1.9-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_tasks` to `0.0.4-1`:
- upstream repository: http://gitlab.clearpathrobotics.com/gps-navigation/cpr_gps_tasks.git
- release repository: http://gitlab.clearpathrobotics.com/gbp/cpr_gps_tasks-gbp.git
```
* fixed datetime error
```
- No changes
- No changes

cpr_gps_tasks: 0.0.4-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.21-1`:
- previous version for package: `0.1.20-1`
```
```
```
```
- No changes
```
```
```
```
```
```
```
* Merge branch 'log_cleanup' into 'master'
```

cpr_gps_navigation: 0.1.21-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_docking` to `0.0.9-1`:
- previous version for package: `0.0.8-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* yaml-cpp dependency
```

cpr_docking: 0.0.9-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `gps_mpc_navigation` to `0.1.10-1`:
- No changes
```
```
- No changes
- No changes

gps_mpc_navigation: 0.1.10-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `heron_robot` to `0.1.7-2`:
```
* Fix bugs related to the switch to CV5 (#11 <https://github.com/heron/heron_robot/issues/11>)
* Use relays instead of remap; remap doesn't work in an include.  Add additional necessary dependencies
* Set the IMU to operate in ENU mode instead of the default NED
* Rename the microstrain nodes to use "imu" instead of "cv5" to be more universal
```
- No changes
- No changes
```
* Fix bugs related to the switch to CV5 (#11 …
```

heron_robot: 0.1.7-2 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.22-1`:
- previous version for package: `0.1.21-1`
- No changes
- No changes
- No changes
- No changes
```
* Merge branch 'log_safety' into 'master'
```
- No changes
- No changes

cpr_gps_navigation: 0.1.22-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `ridgeback_robot` to `0.3.1-1`:
- No changes
```
* [ridgeback_bringup] Made ros service start after can-udp-bridge service.
* [ridgeback_bringup] Removed connman config.
```
- No changes

ridgeback_robot: 0.3.1-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_common` to `0.1.10-1`:
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Merge branch 'install_script' into 'master'
```
```
* Merge branch 'install_script' into 'master'
```
- No changes
- No changes
- No changes
- No changes
- No changes

cpr_gps_common: 0.1.10-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.4.9-1`:
- previous version for package: `0.4.8-1`
- No changes
```
* Fix the name of teh VLP16 launch file that gets included
```
```
* Remove the need to explicitly specify the laser_enabled, realsense_enabled, and urdf_extras arguments; use the envars to make it easier to simulate customized robots & use the moveit setup assistant.
```
```
* Remove the need to explicitly specify the laser_enabled, realsense_enabled, and urdf_extras arguments; use the …
```

husky: 0.4.9-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `warthog` to `0.1.4-2`:
- No changes
```
* CPR extras (#17 <https://github.com/warthog-cpr/warthog/issues/17>)
* cpr_extras
* cpr_extras
* remove cpr_extras.urdf
Co-authored-by: Ebrahim Shahrivar <mailto:eshahrivar@clearpath.ai>
* Add an envar to set the paint colour of the URDF (#16 <https://github.com/warthog-cpr/warthog/issues/16>)
* Add the WARTHOG_COLOR envar, with options 'yellow' (default) and 'olive_green'
* Simplify the paint options, add orange and sand as additional choices based on …
```

warthog: 0.1.4-2 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.4.10-1`:
- previous version for package: `0.4.9-1`
- No changes
- No changes
- No changes
```
* cpr urdf extras
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

husky: 0.4.10-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.7.6-1`:
- previous version for package: `0.7.5-1`
```
* Add envar support for adding a GX5 family IMU (#85 <https://github.com/jackal/jackal/issues/85>)
* Add an alternate EKF file that uses the secondary IMU.  Add the GX5 link to the URDF if necessary. Standard mounting location TBD, so don't merge this yet.
* Add a sane default we can use for mounting the GX5.  RSCI-10 is low-priority, so we may not finalize the default position. But this way Integration can at least start using the envars and ensure they set the xyz/rpy …
```

jackal: 0.7.6-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo` to `0.1.9-2`:
```
* Change where we load the joy_dev argument so it loads correctly
```
- No changes
- No changes
- No changes

dingo: 0.1.9-2 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `ros_mscl` to `1.2.9-1`:
- previous version for package: `1.2.8-1`
- No changes
```
* Add a polling loop to wait for the serial device to actually exist on-disk before opening it
```

ros_mscl: 1.2.9-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `warthog_robot` to `0.1.5-1`:
```
* Only update joint states when the robot is not e-stopped
* [warthog_base] Added topic relay to command MCU to go into low power mode.
* [warthog_robot] Remove unused RC teleo-op.
```
- No changes
- No changes

warthog_robot: 0.1.5-1 in 'melodic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.5.0-1`:
- No changes
```
* [husky_bringup] Switched microstrain_mips to ros_mscl.
* Fix the python-scipy dependency to refer to the python-3 version; python-scipy isn't installable on Focal
* Fix a bug where the UM7 and UM6 launch files don't work when installed to /etc/ros/*/ros.d; they fail to find the mag config files.
```
```
* Disabled multimaster.
* Add the link_name parameter to fix the interactive markers in rviz …
```

husky: 0.5.0-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.5.0-2`:
- previous version for package: `0.5.0-1`
- No changes
```
* [husky_bringup] Switched microstrain_mips to ros_mscl.
* Fix the python-scipy dependency to refer to the python-3 version; python-scipy isn't installable on Focal
* Fix a bug where the UM7 and UM6 launch files don't work when installed to /etc/ros/*/ros.d; they fail to find the mag config files.
```
```
* Disabled multimaster.
* Add the link_name parameter to fix the interactive markers in rviz …
```

husky: 0.5.0-2 in 'noetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.25-1`:
- previous version for package: `0.1.24-1`
- No changes
```
```
- No changes
```
```
- No changes
- No changes
- No changes
- No changes

cpr_gps_navigation: 0.1.25-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.26-1`:
- previous version for package: `0.1.25-1`
- No changes
- No changes
```
* added dependency to meta package
```
- No changes
- No changes
- No changes
- No changes
- No changes

cpr_gps_navigation: 0.1.26-1 in 'melodic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.5.1-1`:
- previous version for package: `0.5.0-2`
```
* Eliminate roslint errors
* Contributors: Lucas Walter, Tony Baltovski
```
```
* Fix the name of teh VLP16 launch file that gets included
* Add a missing colon to the install script
* Add VLP16, secondary LMS1xx support (#164 <https://github.com/husky/husky/issues/164>)
* Minimal refactor to add VLP16 + secondary LMS1xx support. Update defaults for the laser_enabled and realsense_enabled args to refer to the underlying envars to improve consistency when launching simulations. …
```

husky: 0.5.1-1 in 'noetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_common` to `0.1.11-1`:
```
* Merge branch 'led_indicators' into 'master'
Led indicators package
See merge request gps-navigation/cpr_gps_common!24
* Led indicators package
```

cpr_gps_common: 0.1.11-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_common` to `0.1.12-1`:
- previous version for package: `0.1.11-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* fix on the robot
```
- No changes
- No changes
- No changes

cpr_gps_common: 0.1.12-1 in 'melodic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `husky_robot` to `0.6.0-2`:
```
* Re-added husky_robot from husky.
```
```
* Re-added husky_robot from husky.
```
```
* Re-added husky_robot from husky.
```

husky_robot: 0.6.0-2 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.6.0-1`:
- previous version for package: `0.5.1-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

husky: 0.6.0-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.6.0-2`:
- previous version for package: `0.6.0-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

husky: 0.6.0-2 in 'noetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `jackal_robot` to `0.6.3-1`:
- previous version for package: `0.6.2-1`
```
* Merge pull request #33 <https://github.com/jackal/jackal_robot/issues/33> from ms-iot/init_windows
Fix Windows build
* Fix Windows build
* 0.6.2
* Update the changelogs ahead of release
* Contributors: Chris Iverach-Brereton, Lou Amadio, Tony Baltovski
```
```
* Merge pull request #37 <https://github.com/jackal/jackal_robot/issues/37> from luis-camero/melodic-devel
Added Velodyne HDL-32E driver launch file to the accessories launch
* Added Velodyne HDL-32E …
```

jackal_robot: 0.6.3-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo_robot` to `0.1.4-1`:
- No changes
```
* Setup scripts to automatically set DINGO_OMNI and DINGO_WIRELESS_INTERFACE envars (#8 <https://github.com/dingo-cpr/dingo_robot/issues/8>)
* Automatically triggering setup scripts in post_install()
* Add wireless interface and dingo config scripts
* Find setup scripts using find_in_workspaces, and trigger automatically
* Fix script names
Co-authored-by: Joey Yang <mailto:jyang@clearpathrobotics.com>
* Fix the name of teh VLP16 launch file that …
```

dingo_robot: 0.1.4-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.7.7-1`:
- previous version for package: `0.7.6-1`
```
* Enable roslaunch_add_file_check when CATKIN_ENABLE_TESTING=true
* Contributors: PN:Ruichao Wu2
```
```
* Fix the custom_example URDF file to the LMS1xx sensors don't throw errors
* Enable roslaunch_add_file_check when CATKIN_ENABLE_TESTING=true
* Added velodyne towers and HDL-32E sensor (#88)
* Contributors: Chris I-B, Luis Camero, PN:Ruichao Wu2
```
- No changes
```
* Enable roslaunch_add_file_check when CATKIN_ENABLE_TESTING=true
* Contributors: PN:Ruichao Wu2
```

jackal: 0.7.7-1 in 'melodic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.8.0-2`:
- previous version for package: `0.8.0-1`
```
* Merge branch 'noetic-devel-bkup' into noetic-devel
* Fix the link_name parameter for the interactive marker server; the default for the package includes a leading '/', which prevents the markers from working on Noetic.  We can revert this if/when the default for interactive_marker_twist_server is modified.
```
- No changes
- No changes
- No changes
- No changes

jackal: 0.8.0-2 in 'noetic/distribution.yaml' [bloom]

---

foxy/distribution.yaml

Increasing version of package(s) in repository `husky` to `1.0.0-1`:
```
* Initial Gazebo Classic changes.
* Updates to use ros2_control.
* [husky_base] Fixed comparison warnings.
* [husky_base] Fixed logging variable order.
* [husky_base] Populated hardware states and removed joints struct.
* Initial attempt at ros2_control.
* [husky_base] Updated horizon_legacy library for C++11.
* [husky_base] Linting changes to horizon_legacy library.
```
```
* Initial Gazebo Classic changes.
* [husky_control] Added basic localization …
```

husky: 1.0.0-1 in 'foxy/distribution.yaml' [bloom]

---

foxy/distribution.yaml

Increasing version of package(s) in repository `husky` to `1.0.0-2`:
```
* Initial Gazebo Classic changes.
* Updates to use ros2_control.
* [husky_base] Fixed comparison warnings.
* [husky_base] Fixed logging variable order.
* [husky_base] Populated hardware states and removed joints struct.
* Initial attempt at ros2_control.
* [husky_base] Updated horizon_legacy library for C++11.
* [husky_base] Linting changes to horizon_legacy library.
```
```
* Initial Gazebo Classic changes.
* [husky_control] Added basic localization …
```

husky: 1.0.0-2 in 'foxy/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `warthog` to `0.1.4-1`:
- No changes
```
* CPR extras (#17 <https://github.com/warthog-cpr/warthog/issues/17>)
* cpr_extras
* cpr_extras
* remove cpr_extras.urdf
Co-authored-by: Ebrahim Shahrivar <mailto:eshahrivar@clearpath.ai>
* Add an envar to set the paint colour of the URDF (#16 <https://github.com/warthog-cpr/warthog/issues/16>)
* Add the WARTHOG_COLOR envar, with options 'yellow' (default) and 'olive_green'
* Simplify the paint options, add orange and sand as additional choices based on …
```

warthog: 0.1.4-1 in 'noetic/distribution.yaml' [bloom]

---

foxy/distribution.yaml

Increasing version of package(s) in repository `husky` to `1.0.1-1`:
- previous version for package: `1.0.0-2`
- No changes
- No changes
```
* [husky_description] Removed testing.
```
```
* Bumped verisons of metapackages.
* Re-enabled metapackages.
```
- No changes
- No changes
```
* Bumped verisons of metapackages.
* [husky_robot] Disabled dependency on husky_bringup.
* Re-enabled metapackages.
```
```
* Bumped verisons of metapackages.
* Re-enabled metapackages.
```
- No …

husky: 1.0.1-1 in 'foxy/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `ros_mscl` to `1.2.9-1`:
- previous version for package: `1.2.7-3`
- No changes
```
* Add a polling loop to wait for the serial device to actually exist on-disk before opening it
```

ros_mscl: 1.2.9-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `camera_info_manager_py` to `0.3.1-1`:
- upstream repository: https://github.com/clearpathrobotics/camera_info_manager_py.git
- release repository: https://github.com/clearpath-gbp/camera_info_manager_py-release.git
```
* changelog
```

camera_info_manager_py: 0.3.1-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `acado` to `1.3.0-1`:
- upstream repository: https://github.com/clearpathrobotics/acado.git
- release repository: https://github.com/clearpath-gbp/acado-release.git
```
* Merge pull request #5 <https://github.com/clearpathrobotics/acado/issues/5> from jmastrangelo-cpr/tudelft-stable
Tudelft stable (melodic release)
* Contributors: Andres, Joachim Ferreau, Jonathan Jekir, Milan Vukov, Olzhas Adiyatov, Rafael Saback, Rien Quirynen, Ronald Ensing, Shahab Kaynama, Torstein I. Bø, Torstein Ingebrigtsen Bø, andrea.zanelli, jmastrangelo-cpr, nielsvd, rienq
```

acado: 1.3.0-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `microhard_snmp` to `0.0.2-1`:
```
* changes for Noetic release
* Contributors: Ebrahim, José Mastrangelo
```

microhard_snmp: 0.0.2-1 in 'noetic/distribution.yaml' [bloom]

---

rosdep/noetic.yaml

Add ROS2/Foxy dependencies needed by boxer_bringup and boxer_base to interact with Otto's ROS2 API
There may be a nicer way to do this, but if there is I'm not aware of it.

Add ROS2 dependencies needed by Boxer

---

noetic/distribution.yaml

Increasing version of package(s) in repository `wireless` to `0.1.2-1`:
- No changes
```
* Add wireless-tools as a dependency (#14 <https://github.com/clearpathrobotics/wireless/issues/14>)
```

wireless: 0.1.2-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `axis_camera` to `0.4.0-1`:
```
* upgraded cmakelist and package.xml, and setup.py for noetic (#70 <https://github.com/ros-drivers/axis_camera/issues/70>)
* Update the python files to be python-3 compliant.  Fix some bugs in the image data parsing needed as part of this update
* Merge pull request #55 <https://github.com/ros-drivers/axis_camera/issues/55> from sgemme-csa/master
KeyError in publishCameraState when camera is not ready on PTZ camera
* Merge branch 'master' of …
```

axis_camera: 0.4.0-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `boxer_desktop` to `0.1.1-1`:
- upstream repository: https://github.com/boxer-cpr/boxer_desktop.git
- release repository: https://github.com/clearpath-gbp/boxer_desktop-release.git
- No changes
- No changes

boxer_desktop: 0.1.1-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `boxer_simulator` to `0.1.1-1`:
- upstream repository: https://github.com/boxer-cpr/boxer_simulator.git
- release repository: https://github.com/clearpath-gbp/boxer_simulator-release.git
```
* Rename BOXER_SERIAL_NO to ROS_ROBOT_SERIAL_NO to match with incoming changes to the ISO
```
- No changes

boxer_simulator: 0.1.1-1 in 'noetic/distribution.yaml' [bloom]

---

foxy/distribution.yaml

Increasing version of package(s) in repository `husky` to `1.0.3-1`:
```
* [husky_base] Switched Boost static assert to C++ standard library.
```
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes

husky: 1.0.3-1 in 'foxy/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `boxer_robot` to `0.1.1-1`:
```
* Add the ROS2 and clearpath_api dependencies for the bridge
* Sort the dependencies
* Only try sourcing the ROS2 API if the directory exists
* Dynamically load the correct ROS2 path when starting the bridges
* Remove a duplicate diagnostic analyzer node
* Remove an unsatisfiable dependency
* Add the IMU filter dependency
* Rename BOXER_SERIAL_NO to ROS_ROBOT_SERIAL_NO to match with incoming changes to the ISO
* Update the build instructions to remove unneeded …
```

boxer_robot: 0.1.1-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `boxer_robot` to `0.1.2-1`:
```
* Remove the ROS2 Foxy exec_depends temporarily so we can get the core package built. Foxy dependencies will need to be installed manually for now
```
- No changes
- No changes

boxer_robot: 0.1.2-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `boxer_desktop` to `0.1.2-1`:
- upstream repository: https://github.com/boxer-cpr/boxer_desktop.git
- release repository: https://github.com/clearpath-gbp/boxer_desktop-release.git
- No changes
```
* Add a missing rosdep
```

boxer_desktop: 0.1.2-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `boxer_robot` to `0.1.3-1`:
```
* Remove the roslint tests; we've removed the source code that would otherwise need linting
```
- No changes
- No changes

boxer_robot: 0.1.3-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `boxer_robot` to `0.1.3-2`:
```
* Remove the roslint tests; we've removed the source code that would otherwise need linting
```
- No changes
- No changes

boxer_robot: 0.1.3-2 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `boxer_simulator` to `0.1.1-2`:
- upstream repository: https://github.com/boxer-cpr/boxer_simulator.git
- release repository: https://github.com/clearpath-gbp/boxer_simulator-release.git
```
* Rename BOXER_SERIAL_NO to ROS_ROBOT_SERIAL_NO to match with incoming changes to the ISO
```
- No changes

boxer_simulator: 0.1.1-2 in 'noetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.28-1`:
- previous version for package: `0.1.27-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* fix dependency
```
- No changes

cpr_gps_navigation: 0.1.28-1 in 'melodic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `boxer_robot` to `0.1.5-1`:
```
* Explicitly run the bridge scripts through bash
```
- No changes
- No changes

boxer_robot: 0.1.5-1 in 'noetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.29-1`:
- previous version for package: `0.1.28-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* fix build
```
- No changes

cpr_gps_navigation: 0.1.29-1 in 'melodic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `launch_delay` to `0.1.0-1`:
- upstream repository: http://gitlab.clearpathrobotics.com/research/launch_delay.git
- release repository: http://gitlab.clearpathrobotics.com/gbp/launch_delay-gbp.git
```
* Fixed README to augment job rather then replace.
* Minor changes to release this.
* README.md edited online with Bitbucket
* README.md edited online with Bitbucket
* README.md edited online with Bitbucket
* Made script executable.
* package.xml created online with Bitbucket
* CMakeLists.txt created online with Bitbucket
* launch_delay.sh created online with Bitbucket
* delayed_launch.launch created online with Bitbucket …
```

launch_delay: 0.1.0-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `boxer_robot` to `0.1.6-1`:
- No changes
```
* Make sure the ros-bridge-start script is marked as executable
```
- No changes

boxer_robot: 0.1.6-1 in 'noetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `heron_robot` to `0.1.8-1`:
- previous version for package: `0.1.7-2`
```
* Add support for a HERON_NO_WIRELESS envar to completely disable checking for wireless connectivity; if enabled, just tell the MCU the wireless is fine and suppress the slow-2-pulse
* Change the default IP address for the SNMP check to be the actual address of the base-station.
* Contributors: Chris I-B, Chris Iverach-Brereton, Tony Baltovski
```
- No changes
- No changes
- No changes

heron_robot: 0.1.8-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `heron_robot` to `0.1.9-1`:
```
* Add the no-wireless lights script to the install targets
```
- No changes
- No changes
- No changes

heron_robot: 0.1.9-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.30-1`:
- previous version for package: `0.1.29-1`
- No changes
- No changes
- No changes
- No changes
```
* fix mbf api update (mbf version 0.4.0)
```
- No changes
- No changes
- No changes
- No changes

cpr_gps_navigation: 0.1.30-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `earth_rover_piksi` to `1.8.3-1`:
- upstream repository: https://github.com/eshahrivar-cpr/earth_rover_piksi.git
- release repository: https://github.com/clearpath-gbp/earth_rover_piksi-release.git
- previous version for package: `1.8.2-1`
```
* changelog
```
```
* changelog
```
```
* version
* changelog
* upgrade msgs
* upgrade msgs to v1.11.0
```

earth_rover_piksi: 1.8.3-1 in 'melodic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `puma_motor_driver` to `0.3.1-1`:
```
* [puma_motor_driver] Made socketcan_interface a depend rather than build_depend.
```
- No changes

puma_motor_driver: 0.3.1-1 in 'noetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `ridgeback` to `0.3.1-1`:
```
* add predict_to_current_time param
* Add envar to set joy device (#44 <https://github.com/ridgeback/ridgeback/issues/44>)
* Add the RIDGEBACK_JOY_DEVICE envar, move the control_extras to the end of control.launch so it can be used to override anything
* Don't use the envar for the joy device when the PS3 flag is enabled
* Add the default device for the ps3 configuration
* Remove the joy device from the ps4 config; we explicitly set it with the envar
* …
```

ridgeback: 0.3.1-1 in 'melodic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `ridgeback` to `0.3.1-1`:
```
* add predict_to_current_time param
* Add envar to set joy device (#44 <https://github.com/ridgeback/ridgeback/issues/44>)
* Add the RIDGEBACK_JOY_DEVICE envar, move the control_extras to the end of control.launch so it can be used to override anything
* Don't use the envar for the joy device when the PS3 flag is enabled
* Add the default device for the ps3 configuration
* Remove the joy device from the ps4 config; we explicitly set it with the envar …
```

ridgeback: 0.3.1-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `ridgeback_firmware` to `0.2.0-1`:
```
* Apply fixes for Melodic+Bionic from Jackal
```

ridgeback_firmware: 0.2.0-1 in 'noetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.4.11-1`:
- previous version for package: `0.4.10-1`
- No changes
```
* Added Hokuyo UST10.
* Fix the compute_calibration script so it uses the correct name for the magnetic field attribute. Fixes https://github.com/husky/husky/issues/182
* Contributors: Chris Iverach-Brereton, Luis Camero
```
```
* Overwrite 'wheel_radius_multiplier' with env. var. HUSKY_WHEEL_MULTIPLIER
* predict odom->base_link tf to current time
* Contributors: Ebrahim Shahrivar, Luis Camero
```
```
* Added UST10 mesh
* Added Hokuyo UST10.
* [husky_description] …
```

husky: 0.4.11-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `ridgeback_desktop` to `0.1.3-1`:
- upstream repository: https://github.com/ridgeback/ridgeback_desktop
- release repository: https://github.com/clearpath-gbp/ridgeback_desktop-release.git
- No changes
```
* Add rqt directory and launch check
* Alphabetized and added rqt_gui as run_depend
* Add view_diagnostics.launch
* Use the RIDGEBACK_CONFIG envar as the default value for the config arg when viewing the model
* Contributors: Chris Iverach-Brereton, Luis Camero, luis-camero
```

ridgeback_desktop: 0.1.3-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo_desktop` to `0.1.1-1`:
- No changes
```
* Add rqt directory and launch file check
* Add rqt_gui as exec_depend
* Alphabetized and separated test_depend
* Changed run_depend to exec_depend
* Added view_diagnostics
* Contributors: Luis Camero, luis-camero
```

dingo_desktop: 0.1.1-1 in 'melodic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `ridgeback_robot` to `0.4.0-1`:
```
* Update the scipy dependency to Python3
```
- No changes
- No changes

ridgeback_robot: 0.4.0-1 in 'noetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `jackal_desktop` to `0.4.1-1`:
- upstream repository: https://github.com/jackal/jackal_desktop.git
- release repository: https://github.com/clearpath-gbp/jackal_desktop-release.git
- No changes
```
* Updated jackal_viz (#3 <https://github.com/jackal/jackal_desktop/issues/3>)
* Add rqt_gui as run_depend
* Add rqt directory and launch check
* Diagnostic Viewer (#2 <https://github.com/jackal/jackal_desktop/issues/2>)
* Added 'view_diagnostics.launch' to start rqt with console and robot monitor
* Added noetic .perspective, now are dependant on ROS_DISTRO
* Removed distro specific perspectives
```

jackal_desktop: 0.4.1-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo` to `0.1.10-1`:
- previous version for package: `0.1.9-2`
```
* set predict_to_current_time
```
```
* Add missing "xacro:" infront of "include"
```
- No changes
- No changes

dingo: 0.1.10-1 in 'melodic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `dingo` to `0.1.10-1`:
```
* set predict_to_current_time
```
```
* Add missing "xacro:" infront of "include"
```
- No changes
- No changes

dingo: 0.1.10-1 in 'noetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo_robot` to `0.1.5-1`:
- No changes
```
* Add "_secondary" suffix to secondary laser node
"RLException: roslaunch file contains multiple nodes named [/hokuyo]." is thrown if primary and secondary lasers are both enabled. This is because both envars launch an instance of the urg_node with the same name "hokuyo". Adding a "_secondary" suffix to the secondary laser node resolves this issue.
* Contributors: jyang-cpr
```
```
* Add dependency for dingo_tests
* Contributors: jyang-cpr
```

dingo_robot: 0.1.5-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.4.12-1`:
- previous version for package: `0.4.11-1`
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
- No changes
```
* Added view_diagnostics
* Add rqt directory
* Added rqt_gui dependencies
* Contributors: Luis Camero, luis-camero
```

husky: 0.4.12-1 in 'melodic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.6.1-1`:
- previous version for package: `0.6.0-2`
```
* Overwrite 'wheel_radius_multiplier' with env. var. HUSKY_WHEEL_MULTIPLIER
* Check launch file only if testing
When building husky_control, husky_description, husky_navigation or
husky_viz without tests, CMake fails as it does not find
catkin_run_tests_target command. This patch adds conditions to fix
this problem.
* predict odom->base_link tf to current time
* Contributors: Alexandre Iooss, Ebrahim Shahrivar, Luis Camero
```
```
* Fixed error in URDF
* Added Hokuyo
* Check …
```

husky: 0.6.1-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `husky_robot` to `0.6.1-1`:
- previous version for package: `0.6.0-2`
- No changes
```
* Added Hokuyo
```
- No changes

husky_robot: 0.6.1-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `jackal_robot` to `0.7.1-1`:
- previous version for package: `0.7.0-2`
```
* Fix some ROS lint errors
```
```
* Removed duplicate Hokuyo fender node launch
```
- No changes

jackal_robot: 0.7.1-1 in 'noetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `jackal_robot` to `0.6.4-1`:
- previous version for package: `0.6.3-1`
```
* Added analyzers for ekf_localization only when enabled
* Added analyzers to group twist mux
```
- No changes
- No changes

jackal_robot: 0.6.4-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.7.8-1`:
- previous version for package: `0.7.7-1`
```
* predict odom->base_link tf to current time
```
- No changes
- No changes
- No changes

jackal: 0.7.8-1 in 'melodic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.8.1-1`:
- previous version for package: `0.8.0-2`
```
* predict odom->base_link tf to current time
```
```
* Updated to match melodic-devel
```
- No changes
- No changes
- No changes

jackal: 0.8.1-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `ridgeback_desktop` to `0.1.3-1`:
- upstream repository: https://github.com/ridgeback/ridgeback_desktop
- release repository: https://github.com/clearpath-gbp/ridgeback_desktop-release.git
- No changes
```
* Add rqt directory and launch check
* Alphabetized and added rqt_gui as run_depend
* Add view_diagnostics.launch
* Use the RIDGEBACK_CONFIG envar as the default value for the config arg when viewing the model
* Contributors: Chris Iverach-Brereton, Luis Camero, luis-camero
```

ridgeback_desktop: 0.1.3-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `jackal_simulator` to `0.4.0-4`:
- upstream repository: https://github.com/jackal/jackal_simulator
- release repository: https://github.com/clearpath-gbp/jackal_simulator-release.git
- previous version for package: `0.4.0-2`
```
* Enable the joystick by default. Add yaw to the spawn_jackal launch file
* Add an additional parameter to enable teleop in the simulations
* Fix an accidental deletion of a closing tag
* Move the jackal-spawning into a separate launch file for compatibility with the new sim environments.  Add additional sim worlds: completely empty (useful for replaying bag files w/o risk of obstacle collisions!) and HRTAC since the world was in the repo, but not …
```

jackal_simulator: 0.4.0-4 in 'noetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `warthog_desktop` to `0.1.1-1`:
- upstream repository: https://github.com/warthog-cpr/warthog_desktop.git
- release repository: https://github.com/clearpath-gbp/warthog_desktop-release.git
- No changes
```
* [warthog_viz] Added rqt folder to be installed and add launch test for view_diagnostics.
* Alphabetized and added rqt_gui as run_depend
* Add view_diagnostics.launch
* Contributors: Luis Camero, Tony Baltovski, luis-camero
```

warthog_desktop: 0.1.1-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `warthog` to `0.1.5-1`:
- previous version for package: `0.1.4-2`
```
* Add support for WARTHOG_COLOR in gazebo (#18 <https://github.com/warthog-cpr/warthog/issues/18>)
* Move the headlights & taillights into their own links so we can apply the correct Gazebo materials to them (otherwise the robot looks symmetrical, which is confusing). Start applying different materials to the wheel diff links, depending on the paint colour. Sand & Olive are not yet supported
* Start trying to implement custom colours for the sand & olive materials. No …
```

warthog: 0.1.5-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `warthog_simulator` to `0.2.2-2`:
- upstream repository: https://github.com/warthog-cpr/warthog_simulator.git
- release repository: https://github.com/clearpath-gbp/warthog_simulator-release.git
```
* Use the new arg added in warthog_control to always enable the game controller input when using Gazebo.
```
- No changes

warthog_simulator: 0.2.2-2 in 'melodic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `warthog` to `0.1.5-1`:
```
* Add support for WARTHOG_COLOR in gazebo (#18 <https://github.com/warthog-cpr/warthog/issues/18>)
* Move the headlights & taillights into their own links so we can apply the correct Gazebo materials to them (otherwise the robot looks symmetrical, which is confusing). Start applying different materials to the wheel diff links, depending on the paint colour. Sand & Olive are not yet supported
* Start trying to implement custom colours for the sand & olive materials. No …
```

warthog: 0.1.5-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `dingo_desktop` to `0.1.1-1`:
- No changes
```
* Add rqt directory and launch file check
* Add rqt_gui as exec_depend
* Alphabetized and separated test_depend
* Changed run_depend to exec_depend
* Added view_diagnostics
* Contributors: Luis Camero, luis-camero
```

dingo_desktop: 0.1.1-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `warthog_desktop` to `0.1.1-1`:
- upstream repository: https://github.com/warthog-cpr/warthog_desktop.git
- release repository: https://github.com/clearpath-gbp/warthog_desktop-release.git
- No changes
```
* [warthog_viz] Added rqt folder to be installed and add launch test for view_diagnostics.
* Alphabetized and added rqt_gui as run_depend
* Add view_diagnostics.launch
* Contributors: Luis Camero, Tony Baltovski, luis-camero
```

warthog_desktop: 0.1.1-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `dingo_tests` to `0.2.0-1`:
- upstream repository: http://gitlab.clearpathrobotics.com/research/dingo_tests.git
- release repository: http://gitlab.clearpathrobotics.com/gbp/dingo_tests-gbp.git
```
* Change raw_input() to input() for Python3/Noetic
* Fix variable name errors
* Fix odometry linear displacement calculation by using magnitude of x and y vector
* Remove shebang for python3 since using catkin_install_python
* Python3 update
* Remove .py extension for ROS node
```

dingo_tests: 0.2.0-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `dingo_robot` to `0.2.0-1`:
```
* Update the scipy dependency to python3
```
- No changes
- No changes

dingo_robot: 0.2.0-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `yperio` to `0.1.1-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/research/yperio.git
- release repository: https://gitlab.clearpathrobotics.com/gbp/yperio-gbp.git
```
* Removed python3-wstool from dependencies
```

yperio: 0.1.1-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `warthog_simulator` to `0.2.2-1`:
- upstream repository: https://github.com/warthog-cpr/warthog_simulator.git
- release repository: https://github.com/clearpath-gbp/warthog_simulator-release.git
```
* Use the new arg added in warthog_control to always enable the game controller input when using Gazebo.
```
- No changes

warthog_simulator: 0.2.2-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `ridgeback_simulator` to `0.2.0-1`:
- upstream repository: https://github.com/ridgeback/ridgeback_simulator.git
- release repository: https://github.com/clearpath-gbp/ridgeback_simulator-release.git
- No changes
- No changes
```
* Update the libgazebo dependency to use gazebo11 instead of gazebo9
```
- No changes

ridgeback_simulator: 0.2.0-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `dingo_simulator` to `0.1.1-1`:
- upstream repository: https://github.com/dingo-cpr/dingo_simulator.git
- release repository: https://github.com/clearpath-gbp/dingo_simulator-release.git
```
* Remove the realsense-to-laser node, as it's been axed from the core robot_bringup too
* Add an accessories folder for launching additional nodes that would be part of the bringup on a real robot.  Currently populated with the corresponding realsense nodes from dingo_robot
* Enable passing the config argument to dingo_description
```
- No changes

dingo_simulator: 0.1.1-1 in 'noetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `heron_robot` to `0.1.10-1`:
```
* Refactor the base-station ping check to use a standard ping; the snmp check is consistently failing with our current configurations.
```
- No changes
- No changes
- No changes

heron_robot: 0.1.10-1 in 'melodic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `ridgeback_firmware` to `0.3.0-1`:
```
* Removed ros_lib and genpy deps.
```

ridgeback_firmware: 0.3.0-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `ros_mscl` to `1.2.9-2`:
- previous version for package: `1.2.9-1`
- No changes
```
* Add a polling loop to wait for the serial device to actually exist on-disk before opening it
```

ros_mscl: 1.2.9-2 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `husky_robot` to `0.6.2-1`:
- previous version for package: `0.6.1-1`
```
```
```
* Removed HUSKY_IMU_LINK since it can be strictly imu_link
* Removed udev rules from bringup package
* Removed references to microstrain_mips, now use ros_mscl
* Remove unnecessary PS4, Logitech udev rules.
These were previously removed from Melodic; not sure why they were re-added for Noetic, but I suspect it was a copy-paste error …
```

husky_robot: 0.6.2-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `husky` to `0.6.2-1`:
- previous version for package: `0.6.1-1`
```
```
```
* Added Wibotic mesh and STL
```
```
```
```
```
```
```
```
* Bump CMake …
```

husky: 0.6.2-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `jackal_robot` to `0.7.2-1`:
- previous version for package: `0.7.1-1`
```
* Add diagnostic analyzers for EKF localization and twist mux
```
```
* Updated Microstrain environment variables
* Added GX5 to jackal bringup
```
- No changes

jackal_robot: 0.7.2-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.8.2-1`:
- previous version for package: `0.8.1-1`
```
* Updated control.launch to new microstrain envvars and moved definition of ekf-localization paramaters into it
* Added Microstrain GX5 to jackal_control
```
```
* Moved microstrain link to accessories.urdf and updated envvars
* Added velodyne tower mesh
* Added Microstrain GX5 to description
* Removed unnecessary URDF
* Added Wibotic mesh and STL
```
- No changes
- No changes
- No changes

jackal: 0.8.2-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `canfestival_ros` to `0.10.0-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/research/canfestival_ros.git
- release repository: http://gitlab.clearpathrobotics.com/gbp/canfestival_ros-gbp.git
```
* CORE-16828: Python rosbag errors out when reading base bag
* CORE-16658: Create or fix i18n keys for diagnostics
* Adding missing include for uint8_t definition
* C++11-isms
* Add back canfestival-objdictedit as exec_depend.
* roslint to test_depend.
* Initialize parent struct instead of using memcpy.
* Bump min cmake version.
* Drop objdictedit dep.
* Add ROS logging on node change-of-state
* Contributors: Anthony Calandra, …
```

canfestival_ros: 0.10.0-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `sevcon_ros` to `0.2.0-1`:
- No changes
```
* C++11 changes following API change in canfestival_ros; update NodeStates to NodeState; explicitly cast NodeState enum class to integer type
* Explicitly build objdictgen using Python2 for Noetic
```

sevcon_ros: 0.2.0-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `warthog_robot` to `0.1.5-1`:
```
* Only update joint states when the robot is not e-stopped
* [warthog_base] Added topic relay to command MCU to go into low power mode.
* [warthog_robot] Remove unused RC teleo-op.
```
- No changes
- No changes

warthog_robot: 0.1.5-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `yperio` to `0.1.4-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/research/yperio.git
- release repository: https://gitlab.clearpathrobotics.com/gbp/yperio-gbp.git
```
* Updated Jackal microstrain variables and added microstrain to Husky
```

yperio: 0.1.4-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `husky_robot` to `0.6.3-1`:
- previous version for package: `0.6.2-1`
- No changes
```
* [husky_bringup] Removed udev folder from CMakeLists.txt.
```
- No changes

husky_robot: 0.6.3-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `sevcon_ros` to `0.2.1-1`:
- No changes
```
* [sevcon_traction] Fixed objdictgen path.
```

sevcon_ros: 0.2.1-1 in 'noetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `cpr_indoornav` to `0.1.1-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/cpr-indoornav/cpr_indoornav.git
- release repository: https://github.com/clearpath-gbp/cpr_indoornav-release.git
```
* Refactor the package structure, rename packages for clarity
```
- No changes
```
* Add initial network & ROS tests
```

cpr_indoornav: 0.1.1-1 in 'melodic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `cpr_indoornav` to `0.2.0-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/cpr-indoornav/cpr_indoornav.git
- release repository: https://github.com/clearpath-gbp/cpr_indoornav-release.git
```
* Merge branch 'melodic-devel' into noetic-devel
* Initial release for Noetic
```
```
* Merge branch 'melodic-devel' into noetic-devel
* Initial release for Noetic
```

cpr_indoornav: 0.2.0-1 in 'noetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `heron` to `0.4.0-1`:
- No changes
- No changes
- No changes

heron: 0.4.0-1 in 'melodic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `warthog_robot` to `0.2.1-1`:
- No changes
```
* [warthog_bringup] Updated CAN udev rule.
```
- No changes

warthog_robot: 0.2.1-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `cpr_robot_customizer` to `0.1.0-1`:
- upstream repository: https://github.com/clearpathrobotics/cpr_robot_customizer.git
- release repository: https://github.com/clearpath-gbp/cpr_robot_customizer-release.git
```
* Rename package to cpr_robot_customizer; separate Gazebo and Rviz launch files
* Add comments
* Combine gazebo and rviz into same launch file
* Remove ros controllers from Gazebo for simplicity; currently out of scope
* Add Gazebo support for generic robot example
* Add gazebo support for microstrain IMU URDF
* Log output of nodes to screen
* Add missing dependencies to package.xml
* Remove FLIR camera support for now since it …
```

cpr_robot_customizer: 0.1.0-1 in 'noetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `dingo_tests` to `0.1.2-1`:
- upstream repository: http://gitlab.clearpathrobotics.com/research/dingo_tests.git
- release repository: http://gitlab.clearpathrobotics.com/gbp/dingo_tests-gbp.git
```
* Use ip instead of ifconfig
* Fix print statement in rotateTest(); replace pass with time.sleep() in timeout while loops and add proper returns
(cherry picked from commit 0ef51e00318d0fa0f798ad64bb3df754d6a8d102)
* Fix variable name errors
* Fix odometry linear displacement calculation by using magnitude of x and y vector
* Contributors: Joey Yang, jyang-cpr
```

dingo_tests: 0.1.2-1 in 'melodic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `dingo_tests` to `0.2.1-1`:
- upstream repository: http://gitlab.clearpathrobotics.com/research/dingo_tests.git
- release repository: http://gitlab.clearpathrobotics.com/gbp/dingo_tests-gbp.git
```
* Use ip instead of ifconfig
(cherry picked from commit 715694b2db6e6fef75c1ccea7ea13170a5199a85)
* Fix print statement in rotateTest(); replace pass with time.sleep() in timeout while loops and add proper returns
```

dingo_tests: 0.2.1-1 in 'noetic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `cpr_robot_customizer` to `0.1.0-2`:
- upstream repository: https://github.com/clearpathrobotics/cpr_robot_customizer.git
- release repository: https://github.com/clearpath-gbp/cpr_robot_customizer-release.git
```
* Rename package to cpr_robot_customizer; separate Gazebo and Rviz launch files
* Add comments
* Combine gazebo and rviz into same launch file
* Remove ros controllers from Gazebo for simplicity; currently out of scope
* Add Gazebo support for generic robot example
* Add gazebo support for microstrain IMU URDF
* Log output of nodes to screen
* Add missing dependencies to package.xml
* Remove FLIR camera support for now since …
```

cpr_robot_customizer: 0.1.0-2 in 'noetic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `moose` to `0.1.2-1`:
- upstream repository: https://github.com/moose-cpr/moose.git
- release repository: https://github.com/clearpath-gbp/moose-release.git
```
* Move rosparam load outside the joy_teleop ns. (#5 <https://github.com/moose-cpr/moose/issues/5>)
* Move the joy parameters outside the joy_teleop ns to avoid duplicating the namespace. Resolves https://github.com/moose-cpr/moose/issues/4
* Move the rosparam load back into the teleop namespace, remove the namespace from the yaml file
```
- No changes
- No changes

moose: 0.1.2-1 in 'melodic/distribution.yaml' [bloom]

---

melodic/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.7.9-1`:
- previous version for package: `0.7.8-1`
```
* Updated Microstrain Environment Variables (#105 <https://github.com/jackal/jackal/issues/105>)
* Added JACKAL_IMU_MICROSTRAIN environment variable to accessories
* Updated variables in control.launch
```
- No changes
- No changes
- No changes

jackal: 0.7.9-1 in 'melodic/distribution.yaml' [bloom]

---

noetic/distribution.yaml

Increasing version of package(s) in repository `jackal` to `0.8.3-1`:
- previous version for package: `0.8.2-1`
- No changes
```
* Added the option to remove tower from VLP16 mount
* Added SICK TIM551 to URDF and package.xml
* Added UTM30 (#106 <https://github.com/jackal/jackal/issues/106>)
* Updated Navsat and LMS1xx mounts (#103 <https://github.com/jackal/jackal/issues/103>)
* Updated hokuyo_ust10_mount to include min and max angle
* Removed extra spaces
* Updated SICK LMS1XX mount and NAVSAT mount
* Maintained backward compatibility with LMS1xx standard upright poisition by adding mount …
```

jackal: 0.8.3-1 in 'noetic/distribution.yaml' [bloom]
