clearpathrobotics/public-rosdistro

- index.yaml
> Change distribution cache to ros_buildfarm

- index.yaml
- kinetic/distribution.yaml
- kinetic/doc-build.yaml
- kinetic/release-build.yaml
- kinetic/source-build.yaml
- rosdep/50-clearpath.list
- rosdep/indigo.yaml
- rosdep/kinetic.yaml
Any reservations? @mikepurvis @paulbovbel @tspicer01
> Added Kinetic distribution.

- kinetic/distribution.yaml
Increasing version of package(s) in repository `grizzly` to `0.4.0-0`:
- upstream repository: https://github.com/g/grizzly.git
- release repository: https://github.com/clearpath-gbp/grizzly-release.git
```
* Minor package.xml and CMakeList.txt clean-up.
* Fix vehicle dimensions for roscontrol
* Added urdf files and control config files for base.launch to run. Updated package.xml files and changelogs to match current version.
* Contributors: Michael Hosmar, Mohamed Elshatshat, Tony Baltovski
* Minor package.xml and CMakeList.txt clean-up.
* Fix vehicle dimensions for roscontrol
* Added urdf files and control config files for base.launch to run. Updated package.xml files and changelogs …
```
> grizzly: 0.4.0-0 in 'kinetic/distribution.yaml' [bloom]

- kinetic/distribution.yaml
Increasing version of package(s) in repository `grizzly_motor_driver` to `0.0.1-0`:
- upstream repository: https://github.com/g/grizzly_motor_driver.git
- release repository: https://github.com/clearpath-gbp/grizzly_motor_driver-release.git
```
* Ignored linter error.
* Removed tests and fixed linter errors.
* Added checking for the TPM being enabled during configuring and reduced logging.
* Added ability to detect disconnects. Slowed down status requests and cleaned-up logging.
* Added motor temperature sensing.
* Fixed motor voltage and current readings.
* Added new parameters for TPM400s.
* Added check runtime errors to state machine.  Added stopping state to aid with estop …
```
> grizzly_motor_driver: 0.0.1-0 in 'kinetic/distribution.yaml' [bloom]

- kinetic/distribution.yaml
Increasing version of package(s) in repository `grizzly_robot` to `0.3.0-0`:
```
* Updated Udev, maintainer and CAN bridge interface.
* [grizzly_base] Added check for MCU timeout.
* [grizzly_base] Fixed cooling logic.
* Remove temp subscriber.
* Fix dependancy on grizzly_motor_msgs. Remove references to puma_motor_msgs.
* Refine fault and estop handling.
* Added runtime fault handling.
* Changes to enable re-enabling motors after estop.
* Fixed static variable issue. First time CM moves wheels. Fixed direction.
* First steps to switch to …
```
> grizzly_robot: 0.3.0-0 in 'kinetic/distribution.yaml' [bloom]

- kinetic/distribution.yaml
Increasing version of package(s) in repository `heron` to `0.3.1-0`:
```
* Put in some missing dependencies and upgraded package.xml to format 2.0 (#5 <https://github.com/heron/heron/issues/5>)
* Merge pull request #2 <https://github.com/heron/heron/issues/2> from Nirzvi1/kinetic-devel
Added heron_control, changed heron_description to use with uuv_simulator
* Merge branch 'kinetic-devel' into kinetic-devel
* Fixing mistake from rebasing
* Made global covariance accessible from navsat/fix callback
* Allowed use of odometry yaw for simulation
* Fixed …
```
> heron: 0.3.1-0 in 'kinetic/distribution.yaml' [bloom]

- melodic/distribution.yaml
- noetic/distribution.yaml
so jenkins stops murdering them in reprepro
> Added debian to the distributions

- rosdep/kinetic.yaml
- rosdep/melodic.yaml
Forgot to include this one in the previous heron_firmware update
> Add the heron_avr package

- rosdep/extras.yaml
> Added libopenexr-dev for Ubuntu.

- melodic/distribution.yaml
Increasing version of package(s) in repository `cpr_docking` to `0.0.7-1`:
```
* Merge branch 'master' into 'devel'
See merge request gps-navigation/cpr_docking!15
```
```
* changes to resolve merge conflict between one_action and devel
See merge request gps-navigation/cpr_docking!15
```
```
* Merge branch 'master' into 'devel'
See merge request gps-navigation/cpr_docking!29
* Merge branch 'master' into …
```
> cpr_docking: 0.0.7-1 in 'melodic/distribution.yaml' [bloom]

- melodic/distribution.yaml
Increasing version of package(s) in repository `dingo_tests` to `0.1.1-1`:
- upstream repository: http://gitlab.clearpathrobotics.com/research/dingo_tests.git
- release repository: http://gitlab.clearpathrobotics.com/gbp/dingo_tests-gbp.git
```
* Update package dependencies
* Add details comments and descriptions to test scripts
* Update README instructions; update prompts
* Added colour coded text to output for clarity
* Add prerequisite step to README
* Update user prompts for clarity
* Prompt for user for battery type to determine expected battery voltage
* Replace 'is' with '==' for string equality comparison
* Fix function name
* Remove config scripts, move to dingo_robot …
```
> dingo_tests: 0.1.1-1 in 'melodic/distribution.yaml' [bloom]

- noetic/distribution.yaml
Increasing version of package(s) in repository `boxer` to `0.1.1-1`:
- upstream repository: https://github.com/boxer-cpr/boxer.git
- release repository: https://github.com/clearpath-gbp/boxer-release.git
```
* Remove the ds4drv dependency
* Fix the diagnostic analyzer node
* Rename BOXER_SERIAL_NO to ROS_ROBOT_SERIAL_NO to match with incoming changes to the ISO
* Squashed commit of the following:
commit 1b05ec542302a034dc62f85bd28513b43ef17223
Author: Chris Iverach-Brereton <mailto:civerachb@clearpathrobotics.com>
Date:   Wed Nov 10 09:54:43 2021 -0500
Remove old dependencies, add the joint state controller for use inside gazebo
commit 6cef209cd4cef2212a11ff85a403b9408fbc9054
Author: …
```
> boxer: 0.1.1-1 in 'noetic/distribution.yaml' [bloom]

- melodic/distribution.yaml
Increasing version of package(s) in repository `cpr_gps_navigation` to `0.1.27-1`:
- previous version for package: `0.1.26-1`
```
* merge conflicts with master
* Merge branch 'master' into 'devel'
Master
See merge request gps-navigation/cpr_gps_navigation!105
* Merge branch 'master' into 'devel'
Master
See merge request gps-navigation/cpr_gps_navigation!102
```
```
* Merge branch 'lidar_odometry' into 'master'
Lidar odometry
See merge request gps-navigation/cpr_gps_navigation!116
* Merge branch 'fix/CPATE238' …
```
> cpr_gps_navigation: 0.1.27-1 in 'melodic/distribution.yaml' [bloom]

- noetic/distribution.yaml
Increasing version of package(s) in repository `cpr_gazebo` to `0.2.3-1`:
```
* Merge pull request #18 <https://github.com/clearpathrobotics/cpr_gazebo/issues/18> from clearpathrobotics/world_position
Allow changing the world position
* Add world_{x|y|z|yaw} arguments and rename x|y|z|yaw to robot_{x|y|z|yaw} so we can reposition the world if desired.
```
```
* Merge pull request #18 <https://github.com/clearpathrobotics/cpr_gazebo/issues/18> from clearpathrobotics/world_position
Allow …
```
> cpr_gazebo: 0.2.3-1 in 'noetic/distribution.yaml' [bloom]

- humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `0.0.1-1`:
- upstream repository: https://gitlab.clearpathrobotics.com/research/clearpath_config.git
- release repository: https://gitlab.clearpathrobotics.com/research/clearpath_config-release.git
```
* Merge pull request #17 <https://github.com/clearpathrobotics/clearpath_config/issues/17> from clearpathrobotics/readme
Updated README with up-to-date configs
* Merge pull request #16 <https://github.com/clearpathrobotics/clearpath_config/issues/16> from clearpathrobotics/ros2
ROS2 Package
* Merge pull request #15 <https://github.com/clearpathrobotics/clearpath_config/issues/15> from clearpathrobotics/controller …
```
> clearpath_config: 0.0.1-1 in 'humble/distribution.yaml' [bloom]

- noetic/distribution.yaml
Increasing version of package(s) in repository `ptz_action_server` to `0.1.5-1`:
```
* Fix endline
* Restore limits_dome.yaml file as an example.
* Set the is_moving flag _after_ we send the command to the camera hardware, just to prevent possible issues with feedback kicking out early
* Add an additional check to make sure the camera hasn't stopped moving. Make setting self.is_moving atomic with a setter function and a lock
* Add a new config file for dome cameras mounted upside-down
* self.ptz_state.pan and .tilt …
```
> ptz_action_server: 0.1.5-1 in 'noetic/distribution.yaml' [bloom]

- rosdep/50-clearpath.list
- rosdep/foxy.yaml
- rosdep/galactic.yaml
Do not merge until packages are copied to our deb server
> Add Clearpath API packages for ROS 2 Foxy & Galactic to rosdep

- rosdep/humble.yaml
Add Otto ROS 2 API packages for Humble
> Humble Indoor Nav API

- humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `0.3.0-1`:
- previous version for package: `0.2.11-1`
```
* Changes.
* 0.3.0 Release Candidate with Main Changes (#81 <https://github.com/clearpathrobotics/clearpath_common/issues/81>)
* Added tests
* Added action to build from release and source
* Generator linting erros
* Customization linting errors
* Linting
* Fix: Remove IP address from discovery server launch so it listens on all NICs
* Changes.
* 0.2.8
* Add sysctl config file that changes ipfrag settings to support receiving large …
```
> clearpath_common: 0.3.0-1 in 'humble/distribution.yaml' [bloom]

- humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `1.0.0-2`:
```
* Remove battery_state from CMakeLists
* Move battery_state to clearpath_hardware_interfaces
```
```
* Update package paths in generator
* Fixed spelling
* Move battery_state to clearpath_hardware_interfaces
* Use clearpath_ros2_socketcan_interface launch files
* [Backport] Socket CAN Bridges (#93 …
```
> clearpath_robot: 1.0.0-2 in 'humble/distribution.yaml' [bloom]

- jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `2.1.0-1`:
- previous version for package: `2.0.3-1`
- No changes
- No changes
```
* Reduced angular velocity limits from joysticks (#160 <https://github.com/clearpathrobotics/clearpath_common/issues/160>)
* Feature/ekf diagnostics (#158 <https://github.com/clearpathrobotics/clearpath_common/issues/158>)
* Enable ekf node diagnostics
* Fix CI
* Diff drive parameter updates for improved odometry (#155 <https://github.com/clearpathrobotics/clearpath_common/issues/155>)
* Contributors: Hilary …
```
> clearpath_common: 2.1.0-1 in 'jazzy/distribution.yaml' [bloom]

- jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `2.1.0-1`:
- previous version for package: `2.0.4-1`
```
* Feature/diagnostics (#135 <https://github.com/clearpathrobotics/clearpath_robot/issues/135>)
* Initial port of diagnostics to C++
* Remap axis camera topics to match API
* Monitor MCU Status message frequency
* Added firmware version check
* Group MCU diagnostics together
* Improve messaging around firmware versions
* Disable MCU diagnostics for A200
```
```
* Jazzy Phidgets IMU Filter (#138 …
```
> clearpath_robot: 2.1.0-1 in 'jazzy/distribution.yaml' [bloom]

- jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_robot` to `2.2.0-1`:
- previous version for package: `2.1.2-1`
```
* Feature/generated agg yaml (#158 <https://github.com/clearpathrobotics/clearpath_robot/issues/158>)
* Clear out sensor categories that will be generated
* Improve logging and error handling
* Correction to dependencies
* Fix BMS frequency diagnostic (#157 <https://github.com/clearpathrobotics/clearpath_robot/issues/157>)
* Added Lynx motor driver diagnostics (#149 <https://github.com/clearpathrobotics/clearpath_robot/issues/149>)
* …
```
> clearpath_robot: 2.2.0-1 in 'jazzy/distribution.yaml' [bloom]

- humble/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `1.2.0-1`:
- previous version for package: `1.1.1-1`
- No changes
```
* Backport Fix: Sensor depends (#129 <https://github.com/clearpathrobotics/clearpath_common/issues/129>) (#167 <https://github.com/clearpathrobotics/clearpath_common/issues/167>)
* Remove the package initializations that depend on robot packages
* Add a copy of the imu_filter parameters from clearpath_sensors to clearpath_control. Change the default IMU filter config path to point to this file. Remove more unneeded …
```
> clearpath_common: 1.2.0-1 in 'humble/distribution.yaml' [bloom]

- jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_config` to `2.3.0-1`:
- previous version for package: `2.2.2-1`
```
* Added a single Hokuyo laser to default R100 sample. (#157 <https://github.com/clearpathrobotics/clearpath_config/issues/157>)
* Maintain default can adapters but allow overwriting if matching names (#155 <https://github.com/clearpathrobotics/clearpath_config/issues/155>)
* Feature: Wiferion Charger (#154 <https://github.com/clearpathrobotics/clearpath_config/issues/154>)
* Feature: Add CAN adapters  (#153 …
```
> clearpath_config: 2.3.0-1 in 'jazzy/distribution.yaml' [bloom]

- jazzy/distribution.yaml
Increasing version of package(s) in repository `clearpath_common` to `2.5.0-1`:
- previous version for package: `2.3.2-1`
```
* Disable symlink rule to rely on DS4DRV instead
```
- No changes
```
* Fix the velocity limits for Dingo-O using Logitech controllers (#207 <https://github.com/clearpathrobotics/clearpath_common/issues/207>)
* Increase A300 teleop normal speed to 0.4, reduce turbo speed to 1.5 (#206 <https://github.com/clearpathrobotics/clearpath_common/issues/206>)
```
- No changes
- No …
> clearpath_common: 2.5.0-1 in 'jazzy/distribution.yaml' [bloom]
